### ISSUE TITLE
ng generate incorrectly adds component to a module

### ISSUE THREAD

**Issue by DanielKucal** [angular/angular-cli#10030]
### Versions
```
Angular CLI: 1.7.2
Node: 7.7.4
OS: darwin x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

* `ng generate component components/whatever`
Video: https://youtu.be/sN_De_pC26I

### Observed behavior
Angular CLI misplaces component declaration, produces e.g.:
```
  declarations: [
    AppComponen,
    HomeComponentt,
  ],
```

### Desired behavior
I would expect:
```
  declarations: [
    AppComponent,
    HomeComponent,
  ],
```

### Mention any other details that might be useful (optional)
- `--lint-fix` doesn't matter here
- directory ("components/") doesn't matter as well

**Comment by Worthy7** [comment]
Bumb, kind of critical.

**Comment by mbtaCode** [comment]
Hi! Did you find a solution to this issue? I'm also experiencing the same thing when I create a component from the CLI, except it is moving the last 2 characters. I'm using VS 2018 as my IDE.

Thanks,
Mel

**Comment by Worthy7** [comment]
@mbtaCode Yea It's fixed in the later versions

**Comment by DanielKucal** [comment]
@mbtaCode, maybe you have different version of `@angular/cli` installed locally in the project?

**Comment by mbtaCode** [comment]
I ran ng v in my angular CLI project folder and the output is:

Angular CLI: 1.7.4
Node: 9.2.0
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

**Comment by DanielKucal** [comment]
@mbtaCode, I just checked it with the newest version and the bug is still present for me too.

**Comment by Worthy7** [comment]
This is fixed btw.

**Comment by mbtaCode** [comment]
@Worthy7 Thanks for letting me know. I haven't seen the issue reappear for a while. It does seem to be fixed.
