### ISSUE TITLE
[feature-request/regression] Allow to run tests/coverage directly from IDE

### ISSUE THREAD

**Issue by aszechlicki** [angular/angular-cli#10755]
### Versions
```
Angular CLI: 6.0.0
Node: 9.3.0
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

```

### Observed behavior
In previous versions I was able to run tests and coverage directly from WebStorm, which made our lives a lot easier since we could only launch specific tests just by clicking icon in the editor gutter, and had great integration of test and coverage results in IDE.
Upgrade to CLI v6 broke that, we now get error:
```
Error: The '@angular-devkit/build-angular/plugins/karma' karma plugin is meant to be used from within Angular CLI and will not work correctly outside of it.
    at init (C:\Users\arkad\source\project\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\packages\angular_devkit\build_angular\src\angular-cli-files\plugins\karma.ts:53:11)
```

### Desired behavior
I would like to be able to run tests and coverage directly from IDE, like I was able to in previous versions

**Comment by pgingras** [comment]
This would be really helpful to our team too! Makes a huge difference.

**Comment by AlexGS74** [comment]
It works in Webstorm 2018.2 EAP published yesterday.

**Comment by clydin** [comment]
Closing as resolved via Webstorm as indicated above.

**Comment by pgingras** [comment]
This issue seems to duplicate https://github.com/angular/angular-cli/issues/10703, so it's alright to close it, but I would like to mention that as indicated by the comment on the other issue Webstorm 2018.2 EAP does not seem to fix it.
