### ISSUE TITLE
ERR! extraneous

### ISSUE THREAD

**Issue by griffiti** [angular/angular-cli#1160]
> ## Please provide us with the following information:
> 1. OS?  **Windows 7**
1. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
       node --version
   And paste the result here.   **v6.2.2**
2. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   Installed latest NodeJS 6. Installed typings globally. Then installed angular-cli globally.
3. The log given by the failure. Normally this include a stack trace and some
   more information.

$ npm list -g --depth=0
C:\Users\Jonathan\AppData\Roaming\npm
+-- angular-cli@1.0.0-beta.6
`-- typings@1.3.0

npm ERR! extraneous: assertion-error@1.0.2 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\assertion-error
npm ERR! extraneous: deep-eql@0.1.3 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\deep-eql
npm ERR! extraneous: doctrine@1.2.2 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\doctrine
npm ERR! extraneous: escope@3.6.0 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\escope
npm ERR! extraneous: espree@3.1.4 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\espree
npm ERR! extraneous: file-entry-cache@1.2.4 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\file-entry-cache
npm ERR! extraneous: formatio@1.1.1 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\formatio
npm ERR! extraneous: growl@1.9.2 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\growl
npm ERR! extraneous: ignore@3.1.2 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\ignore
npm ERR! extraneous: is-resolvable@1.0.0 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\is-resolvable
npm ERR! extraneous: jade@0.26.3 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\jade
npm ERR! extraneous: lolex@1.3.2 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\lolex
npm ERR! extraneous: optionator@0.8.1 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\optionator
npm ERR! extraneous: pluralize@1.2.1 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\pluralize
npm ERR! extraneous: progress@1.1.8 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\progress
npm ERR! extraneous: require-uncached@1.0.2 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\require-uncached
npm ERR! extraneous: table@3.7.8 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\table
npm ERR! extraneous: text-table@0.2.0 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\text-table
npm ERR! extraneous: to-iso-string@0.0.2 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\to-iso-string
npm ERR! extraneous: type-detect@1.0.0 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\type-detect
npm ERR! extraneous: util@0.10.3 C:\Users\Jonathan\AppData\Roaming\npm\node_modules\angular-cli\node_modules\util

**Comment by manifestarium** [comment]
Same here /\

**Comment by griffiti** [comment]
It doesn't seem to prevent the use of angular-cli.

**Comment by oscar6echo** [comment]
Same here.
On OSX Yosemite.
From a clean install of node & npm with homebrew:
````
Olivier@Central:~ (72) $ node -v
v6.3.0
Olivier@Central:~ (69) $ npm list -g -depth=0
/usr/local/lib
└── npm@3.10.3
````

After running
````
npm install -g angular-cli
````
which works fine in spite of some WARNINGs
````
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
````
then the following list command
````
npm list -g -depth=0
````

displays some worrying npm errors:
````
Olivier@Central:~ (71) $ npm list -g -depth=0
/usr/local/lib
├── angular-cli@1.0.0-beta.10
└── npm@3.10.3

npm ERR! extraneous: assertion-error@1.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/assertion-error
npm ERR! extraneous: conventional-changelog-angular@1.2.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-angular
npm ERR! extraneous: conventional-changelog-atom@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-atom
npm ERR! extraneous: conventional-changelog-codemirror@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-codemirror
npm ERR! extraneous: conventional-changelog-core@1.5.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-core
npm ERR! extraneous: conventional-changelog-ember@0.2.2 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-ember
npm ERR! extraneous: conventional-changelog-eslint@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-eslint
npm ERR! extraneous: conventional-changelog-express@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-express
npm ERR! extraneous: conventional-changelog-jquery@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-jquery
npm ERR! extraneous: conventional-changelog-jscs@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-jscs
npm ERR! extraneous: conventional-changelog-jshint@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-jshint
npm ERR! extraneous: deep-eql@0.1.3 /usr/local/lib/node_modules/angular-cli/node_modules/deep-eql
npm ERR! extraneous: doctrine@1.2.2 /usr/local/lib/node_modules/angular-cli/node_modules/doctrine
npm ERR! extraneous: escope@3.6.0 /usr/local/lib/node_modules/angular-cli/node_modules/escope
npm ERR! extraneous: espree@3.1.6 /usr/local/lib/node_modules/angular-cli/node_modules/espree
npm ERR! extraneous: file-entry-cache@1.2.4 /usr/local/lib/node_modules/angular-cli/node_modules/file-entry-cache
npm ERR! extraneous: formatio@1.1.1 /usr/local/lib/node_modules/angular-cli/node_modules/formatio
npm ERR! extraneous: growl@1.9.2 /usr/local/lib/node_modules/angular-cli/node_modules/growl
npm ERR! extraneous: ignore@3.1.3 /usr/local/lib/node_modules/angular-cli/node_modules/ignore
npm ERR! extraneous: is-resolvable@1.0.0 /usr/local/lib/node_modules/angular-cli/node_modules/is-resolvable
npm ERR! extraneous: jade@0.26.3 /usr/local/lib/node_modules/angular-cli/node_modules/jade
npm ERR! extraneous: lolex@1.3.2 /usr/local/lib/node_modules/angular-cli/node_modules/lolex
npm ERR! extraneous: optionator@0.8.1 /usr/local/lib/node_modules/angular-cli/node_modules/optionator
npm ERR! extraneous: pluralize@1.2.1 /usr/local/lib/node_modules/angular-cli/node_modules/pluralize
npm ERR! extraneous: progress@1.1.8 /usr/local/lib/node_modules/angular-cli/node_modules/progress
npm ERR! extraneous: require-uncached@1.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/require-uncached
npm ERR! extraneous: rewire@2.5.2 /usr/local/lib/node_modules/angular-cli/node_modules/rewire
npm ERR! extraneous: sigmund@1.0.1 /usr/local/lib/node_modules/angular-cli/node_modules/sigmund
npm ERR! extraneous: table@3.7.8 /usr/local/lib/node_modules/angular-cli/node_modules/table
npm ERR! extraneous: text-table@0.2.0 /usr/local/lib/node_modules/angular-cli/node_modules/text-table
npm ERR! extraneous: to-iso-string@0.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/to-iso-string
npm ERR! extraneous: type-detect@1.0.0 /usr/local/lib/node_modules/angular-cli/node_modules/type-detect
npm ERR! extraneous: util@0.10.3 /usr/local/lib/node_modules/angular-cli/node_modules/util
````

What do these message mean ?
Anything to really worry about ?
Is is a version issue ?
Any indication welcome.

`angular-cli` seems to work but this is not enough to make me comfortable...

**Comment by filipesilva** [comment]
Does this still happen on more recent betas?

**Comment by sprypradeep** [comment]
The error is displayed on beta-9 and beta-10 as well for me. Xubuntu 16.04 node 6.2.2

**Comment by filipesilva** [comment]
This might be due to the use of npm shrinkwrap. @hansl do these errors seem familiar?

**Comment by m99coder** [comment]
It still happens with more recent betas @filipesilva 

Mac OS X:
```shell
$ sw_vers -productVersion
10.11.6
```

Node & npm:
```shell
$ node -v && npm -v
v6.3.1
3.10.5
```

Errors:
```shell
$ npm ls -g --depth=0
/usr/local/lib
└── angular-cli@1.0.0-beta.10

npm ERR! extraneous: assertion-error@1.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/assertion-error
npm ERR! extraneous: conventional-changelog-angular@1.2.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-angular
npm ERR! extraneous: conventional-changelog-atom@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-atom
npm ERR! extraneous: conventional-changelog-codemirror@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-codemirror
npm ERR! extraneous: conventional-changelog-core@1.5.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-core
npm ERR! extraneous: conventional-changelog-ember@0.2.2 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-ember
npm ERR! extraneous: conventional-changelog-eslint@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-eslint
npm ERR! extraneous: conventional-changelog-express@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-express
npm ERR! extraneous: conventional-changelog-jquery@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-jquery
npm ERR! extraneous: conventional-changelog-jscs@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-jscs
npm ERR! extraneous: conventional-changelog-jshint@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-jshint
npm ERR! extraneous: deep-eql@0.1.3 /usr/local/lib/node_modules/angular-cli/node_modules/deep-eql
npm ERR! extraneous: doctrine@1.2.2 /usr/local/lib/node_modules/angular-cli/node_modules/doctrine
npm ERR! extraneous: escope@3.6.0 /usr/local/lib/node_modules/angular-cli/node_modules/escope
npm ERR! extraneous: espree@3.1.6 /usr/local/lib/node_modules/angular-cli/node_modules/espree
npm ERR! extraneous: file-entry-cache@1.2.4 /usr/local/lib/node_modules/angular-cli/node_modules/file-entry-cache
npm ERR! extraneous: formatio@1.1.1 /usr/local/lib/node_modules/angular-cli/node_modules/formatio
npm ERR! extraneous: growl@1.9.2 /usr/local/lib/node_modules/angular-cli/node_modules/growl
npm ERR! extraneous: ignore@3.1.3 /usr/local/lib/node_modules/angular-cli/node_modules/ignore
npm ERR! extraneous: is-resolvable@1.0.0 /usr/local/lib/node_modules/angular-cli/node_modules/is-resolvable
npm ERR! extraneous: jade@0.26.3 /usr/local/lib/node_modules/angular-cli/node_modules/jade
npm ERR! extraneous: lolex@1.3.2 /usr/local/lib/node_modules/angular-cli/node_modules/lolex
npm ERR! extraneous: optionator@0.8.1 /usr/local/lib/node_modules/angular-cli/node_modules/optionator
npm ERR! extraneous: pluralize@1.2.1 /usr/local/lib/node_modules/angular-cli/node_modules/pluralize
npm ERR! extraneous: progress@1.1.8 /usr/local/lib/node_modules/angular-cli/node_modules/progress
npm ERR! extraneous: require-uncached@1.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/require-uncached
npm ERR! extraneous: rewire@2.5.2 /usr/local/lib/node_modules/angular-cli/node_modules/rewire
npm ERR! extraneous: sigmund@1.0.1 /usr/local/lib/node_modules/angular-cli/node_modules/sigmund
npm ERR! extraneous: table@3.7.8 /usr/local/lib/node_modules/angular-cli/node_modules/table
npm ERR! extraneous: text-table@0.2.0 /usr/local/lib/node_modules/angular-cli/node_modules/text-table
npm ERR! extraneous: to-iso-string@0.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/to-iso-string
npm ERR! extraneous: type-detect@1.0.0 /usr/local/lib/node_modules/angular-cli/node_modules/type-detect
npm ERR! extraneous: util@0.10.3 /usr/local/lib/node_modules/angular-cli/node_modules/util
```

It would be great if you could manage to fix this.

**Comment by osenvosem** [comment]
`ng -v`
```
(node:21180) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 1.0.0-beta.10
node: 6.3.1
os: darwin x64
```

The error occurred while `npm -g list --depth=0`:
```
npm ERR! extraneous: assertion-error@1.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/assertion-error
npm ERR! extraneous: conventional-changelog-angular@1.2.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-angular
npm ERR! extraneous: conventional-changelog-atom@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-atom
npm ERR! extraneous: conventional-changelog-codemirror@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-codemirror
npm ERR! extraneous: conventional-changelog-core@1.5.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-core
npm ERR! extraneous: conventional-changelog-ember@0.2.2 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-ember
npm ERR! extraneous: conventional-changelog-eslint@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-eslint
npm ERR! extraneous: conventional-changelog-express@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-express
npm ERR! extraneous: conventional-changelog-jquery@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-jquery
npm ERR! extraneous: conventional-changelog-jscs@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-jscs
npm ERR! extraneous: conventional-changelog-jshint@0.1.0 /usr/local/lib/node_modules/angular-cli/node_modules/conventional-changelog-jshint
npm ERR! extraneous: deep-eql@0.1.3 /usr/local/lib/node_modules/angular-cli/node_modules/deep-eql
npm ERR! extraneous: doctrine@1.2.2 /usr/local/lib/node_modules/angular-cli/node_modules/doctrine
npm ERR! extraneous: escope@3.6.0 /usr/local/lib/node_modules/angular-cli/node_modules/escope
npm ERR! extraneous: espree@3.1.6 /usr/local/lib/node_modules/angular-cli/node_modules/espree
npm ERR! extraneous: file-entry-cache@1.2.4 /usr/local/lib/node_modules/angular-cli/node_modules/file-entry-cache
npm ERR! extraneous: formatio@1.1.1 /usr/local/lib/node_modules/angular-cli/node_modules/formatio
npm ERR! extraneous: growl@1.9.2 /usr/local/lib/node_modules/angular-cli/node_modules/growl
npm ERR! extraneous: ignore@3.1.3 /usr/local/lib/node_modules/angular-cli/node_modules/ignore
npm ERR! extraneous: is-resolvable@1.0.0 /usr/local/lib/node_modules/angular-cli/node_modules/is-resolvable
npm ERR! extraneous: jade@0.26.3 /usr/local/lib/node_modules/angular-cli/node_modules/jade
npm ERR! extraneous: lolex@1.3.2 /usr/local/lib/node_modules/angular-cli/node_modules/lolex
npm ERR! extraneous: optionator@0.8.1 /usr/local/lib/node_modules/angular-cli/node_modules/optionator
npm ERR! extraneous: pluralize@1.2.1 /usr/local/lib/node_modules/angular-cli/node_modules/pluralize
npm ERR! extraneous: progress@1.1.8 /usr/local/lib/node_modules/angular-cli/node_modules/progress
npm ERR! extraneous: require-uncached@1.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/require-uncached
npm ERR! extraneous: rewire@2.5.2 /usr/local/lib/node_modules/angular-cli/node_modules/rewire
npm ERR! extraneous: sigmund@1.0.1 /usr/local/lib/node_modules/angular-cli/node_modules/sigmund
npm ERR! extraneous: table@3.7.8 /usr/local/lib/node_modules/angular-cli/node_modules/table
npm ERR! extraneous: text-table@0.2.0 /usr/local/lib/node_modules/angular-cli/node_modules/text-table
npm ERR! extraneous: to-iso-string@0.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/to-iso-string
npm ERR! extraneous: type-detect@1.0.0 /usr/local/lib/node_modules/angular-cli/node_modules/type-detect
npm ERR! extraneous: util@0.10.3 /usr/local/lib/node_modules/angular-cli/node_modules/util
```

**Comment by Yonet** [comment]
I was getting the same error, this fixed it for me:
npm i -g angular-cli@1.0.0-beta.11-webpack.2

**Comment by christiandreher** [comment]
I am also facing this problem. ubuntu@16.04, angular-cli@1.0.0-beta.10

**Comment by oscar6echo** [comment]
Like @Yonet I followed the instructions [Upgrading from angular-cli@1.0.0-beta.10 to the angular-cli@webpack](https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md).

Then the problem I mentioned disappeared but is replaced by another error msg:
````
$ npm list -g --depth=0
/usr/local/lib
├── angular-cli@1.0.0-beta.11-webpack.2
├── eslint@3.2.2
├── npm@3.10.3
├── rxjs@5.0.0-beta.10
├── rxjs-es@5.0.0-beta.10
├── ts-node@1.2.2
├── typescript@1.8.10
└── typings@1.3.2

npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: typescript@^1.8.0 || ^1.9.0-dev, required by tsickle@0.1.6
````

And even if I install the requested typescript versions, I still get the same error:
````
$ npm list -g --depth=0
/usr/local/lib
├── angular-cli@1.0.0-beta.11-webpack.2
├── eslint@3.2.2
├── npm@3.10.3
├── rxjs@5.0.0-beta.10
├── rxjs-es@5.0.0-beta.10
├── ts-node@1.2.2
├── typescript@1.9.0-dev.20160409
└── typings@1.3.2

npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: typescript@^1.8.0 || ^1.9.0-dev, required by tsickle@0.1.6
````
But when I inspect one level below I see an UNMET PEER DEPENDENCY that does not come out as an `npm ERR`:
````
$ npm list -g --depth=1
/usr/local/lib
├─┬ angular-cli@1.0.0-beta.11-webpack.2
│ ├── @angular/tsc-wrapped@0.2.2
│ ├── @types/lodash@4.14.30
│(...)
│ ├── tslint@3.14.0
│ ├── tslint-loader@2.1.5
│ ├── typedoc@0.4.4
│ ├── UNMET PEER DEPENDENCY typescript@2.0.0
│ ├── url-loader@0.5.7
│ ├── webpack@2.1.0-beta.18
│ ├── webpack-dev-server@2.1.0-beta.0
│ ├── webpack-md5-hash@0.0.5
│ └── webpack-merge@0.14.1
├─┬ eslint@3.2.2
│ ├── chalk@1.1.3
│(...)
│ ├── text-table@0.2.0
│ └── user-home@2.0.0
├─┬ npm@3.10.3
│ ├── abbrev@1.0.9
│ ├── ansi-regex@2.0.0
│(...)
│ ├── which@1.2.10
│ ├── wrappy@1.0.2
│ └── write-file-atomic@1.1.4
├─┬ rxjs@5.0.0-beta.10
│ └── symbol-observable@1.0.1
├─┬ rxjs-es@5.0.0-beta.10
│ └── symbol-observable@1.0.1
├─┬ ts-node@1.2.2
│ ├── arrify@1.0.1
│(...)
│ └── xtend@4.0.1
├── typescript@1.9.0-dev.20160409
└─┬ typings@1.3.2
  ├── any-promise@1.3.0
│(...)
  └── xtend@4.0.1

npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: typescript@^1.8.0 || ^1.9.0-dev, required by tsickle@0.1.6
````
So the error msg is about `typescript@2.0.0` which does not exist (the latest version being [1.8.10](https://www.npmjs.com/package/typescript) as of 15aug16)

And if I go 2 levels deep, I see an additional UNMET PEER DEPENDENCY, the one that is caught by `npm ERR`:
````
$ npm list -g --depth=2
/usr/local/lib
├─┬ angular-cli@1.0.0-beta.11-webpack.2
│ ├─┬ @angular/tsc-wrapped@0.2.2
│ │ ├── tsickle@0.1.6
│ │ └── UNMET PEER DEPENDENCY typescript@^1.8.0 || ^1.9.0-dev
│ ├── @types/lodash@4.14.30
│ ├── @types/rimraf@0.0.25-alpha
(...)
````
Does somebody know what's going on ?
It does not look consistent to me..

**Comment by Yonet** [comment]
@oscar6echo I have the same error message about typescript. It is just a warning. I ignored it and my app works fine so far.

**Comment by filipesilva** [comment]
Since this doesn't happen with the webpack releases and they are not using npm shrinkwrap, it definitely seems related.

@oscar6echo those peerDep errors turn to warnings in npm 3. We hadn't listed npm 3 as needed in the readme, but it most definitely is for A2 development. https://github.com/angular/angular-cli/pull/1748 adds it there.

@Yonet :wave:

**Comment by hansl** [comment]
Yeah probably related to shrinkwrap. I'll try to figure out what's going. There's probably a way to clean up the shrinkwrap file.

**Comment by RigaNik** [comment]
Any solution for this? I got the same problem.
OS: El Capitan 
node -v 6.5
npm 3.10.3

sudo npm i -g angular-cli@1.0.0-beta.11-webpack.2

"sudo npm list -g --depth=0" gives the following: 
`npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: typescript@^1.8.0 || ^1.9.0-dev, required by tsickle@0.1.6`

And when i try to type anything that start with "ng" in the terminal, it says "ng: command not found."

**Comment by christiandreher** [comment]
That's not related to this issue @RigaNik. The issue mentions extraneous errors, you get missing peer dependency errors. If something does not work for you, google it or open a new issue. If everything works as expected, you can ignore the error, since some packages still rely on older versions of typescript, but that doesn't prevent them from working in most cases

**Comment by hansl** [comment]
Closing this as obsolete. We fixed a lot of our dependencies now and shouldn't have extraneous ones.

**Comment by zh-wowtv** [comment]
```
npm ERR! extraneous: tsickle@0.2.5 /usr/local/lib/node_modules/@angular/cli/node_modules/@angular-cli/ast-tools/node_modules/tsickle
npm ERR! extraneous: path-array@1.0.1 /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/path-array
npm ERR! extraneous: has-color@0.1.7 /usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/has-color
```

How can I remove unnecessary module?

**Comment by sajidali** [comment]
@hansl 
still having similar issues with `1.0.0-beta.30`
```
$ npm ls -g --depth=0
├── @angular/cli@1.0.0-beta.30

npm ERR! extraneous: tsickle@0.2.5 /home/sajid/.nvm/versions/node/v6.9.4/lib/node_modules/@angular/cli/node_modules/@angular-cli/ast-tools/node_modules/tsickle
```
```
$ ng --version
@angular/cli: 1.0.0-beta.30
node: 6.9.4
```

**Comment by spjeff** [comment]
Yes, I still see this message but only for "tsickle" now.

npm list -g --depth=0
+-- angular-cli@1.0.0-beta.28.3

npm ERR! extraneous: tsickle@0.2.5 ...\node_modules\angular-cli\node_modules\@angular-cli\ast-tools\node_modules\tsickle

![2017-02-06_13-58-38](https://cloud.githubusercontent.com/assets/5648223/22663976/62294ebe-ec74-11e6-9013-f745130c0ed1.png)
