### ISSUE TITLE
 Cannot find module 'exists-sync'

### ISSUE THREAD

**Issue by cre8** [angular/angular-cli#1186]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
os: Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
angular-cli: 1.0.0-beta.8
node: 6.2.2
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I updated to the latest cli version (beta 8). When I run ng outside the project it shows me all the options. But when I run it inside my project I get an error.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\foo1\node_modules\angular-cli\node_modules\ember-cli\lib\models\project.js:11:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by elliott-davis** [comment]
I hit this too and got around it by running a `npm install`

**Comment by scrivy** [comment]
I still get the same error after running npm install :-/

node v4.4.5
npm 2.15.4

**Comment by Rafi993** [comment]
I did npm install in the nodemodules and it generated new project but when I typed
` ng serve --port 4201 --live-reload-port 49153`   It shows  the same error again 

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Desktop\ngTest\node_modules\angular-cli\node_modules\ember-cli\lib\models\project.js:11:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

```

**Comment by tieppt** [comment]
go to `angular-cli` installed directory ex: `C:\xampp\htdocs\foo1\node_modules\angular-cli` run `npm i`

**Comment by crzyjcky** [comment]
I ran "npm install" twice:

1. For "ng new" to work:
cd /usr/lib/node_modules/angular-cli
sudo npm install

2. For "ng serve" to work:
cd <project folder>/node_modules/angular-cli
npm install

**Comment by littleStudent** [comment]
just had the same problem on macOS
running `npm install` did solve it.

**Comment by KarlPurk** [comment]
Just hit this problem too.  Should the readme be updated to reflect this as it doesn't instil confidence for newcomers?  The first thing the readme shows is:

```
ng new PROJECT_NAME
cd PROJECT_NAME
ng serve
```

and that doesn't work due to this issue.

**Comment by ernestocortes** [comment]
#469 

try runnign npm install exists-sync --save-dev in the project folder. that fixed it for me.

**Comment by Codermar** [comment]
Re-installing the CLI (to beta8) and starting a brand new project, I had to do additional npm installs before I was able to run the app.

npm i -D exists-sync
npm i -D object-assign
npm i -D minimatch
npm i -D walk-sync
npm i -D through

**Comment by M4RTO** [comment]
you have to go  inside the directory of angular cli , inside of node and npm install

**Comment by Codermar** [comment]
That's right, I had to do that too but still had to do the additional installs after ng new in the project itself.

**Comment by M4RTO** [comment]
Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Martin\Documents\project\newProject\project\node_modules\angular-cli\node_modules\ember-cli\lib\models\project.js:11:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)


algo asi ? 

en esta carpeta dale npm install y fue .. Users\Martin\Documents\project\newProject\project\node_modules\angular-cli\node_modules\

**Comment by rijine** [comment]
got same problem, npm install --save works for me

**Comment by david-lee** [comment]
ran npm install and worked for me

**Comment by academiasemillas** [comment]
npm install and worked for me
Thanks!

**Comment by juampi** [comment]
Thanks @crzyjcky ! Worked like magic.

**Comment by dtereshenko** [comment]
@crzyjcky It also solve my issues. Thanks!

**Comment by leagan** [comment]
`npm i ` fix it for me

**Comment by madhusudhand** [comment]
I guess this is the problem with NPM itself.

ember-cli has a dependency "exists-sync": "0.0.3" and angular-cli has the same as devDependency.
as npm install -g ignore devDependencies of angular-cli, this isn't installed. Where as it should install inside ember-cli. But it din't install.
Moving devDependency to dependencies should solve the issue. But Ideally we should not be doing so as it isn't a --prod dependency of angular-cli

**Comment by manuelfink** [comment]
@madhusudhand how than can the dependencies for angular-cli / ember-cli be installed?

**Comment by manuelfink** [comment]
+1 

However `npm instal` did not solve the problem for me. I do have to run it as root on mac `sudo npm install` which seems to be really bad practice for me.

I'm running on node 6.2.2 with latest npm 3.10.2

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.2
npm ERR! path ../typescript/bin/tsc
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '../typescript/bin/tsc' -> '/Users/manuelfink/git/angular-2-test/node_modules/angular-cli/node_modules/.bin/tsc'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, symlink '../typescript/bin/tsc' -> '/Users/manuelfink/git/angular-2-test/node_modules/angular-cli/node_modules/.bin/tsc'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../typescript/bin/tsc',
npm ERR!   dest: '/Users/manuelfink/git/angular-2-test/node_modules/angular-cli/node_modules/.bin/tsc',
npm ERR!   parent: 'angular-cli' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.2
npm ERR! path npm-debug.log.2854708998
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
```

**Comment by Rafi993** [comment]
In linux or mac OS you need sudo while running npm if you want to run without sudo you should use [nvm](https://github.com/creationix/nvm) or follow the instructions given in [here](https://docs.npmjs.com/getting-started/fixing-npm-permissions). This is not an issue and it is not related to angular-cli

**Comment by Rafi993** [comment]
@cre8  please close the issue if it is solved.

**Comment by manuelfink** [comment]
@Rafi993 it seems to be that this is not resolves as of now.

* .beta8 is missing the above dependencies, which must be manually installed to get angular cli running and than be manually installed within every project.
* I do agree that root is necessary for installing global packages. However running npm within a project as sudo seems weird to me. Still I'm anyhow not even understanding why I need root privileges for a subfolder which belongs to my user. Maybe just a problem of my mac.

**Comment by PascalPrecht** [comment]
This comment https://github.com/angular/angular-cli/issues/1186#issuecomment-228691834 describes the actual issue very well.

@filipesilva are we planning to add those dependencies to `dependencies` ? Otherwise the command is simply globally broken.

**Comment by filipesilva** [comment]
Hi everyone, apologies for taking so long to address this issue. First of all, thank you for all the comments and proposed temporary solutions. 

Reading through the thread allowed me to zone into the real issue - the way `ng new` ran `npm`. Turns out it was using a 2.x.x npm internally. This is why when you did `npm install` things just worked again, your global npm version was more recent. 

Simply adding these missing dependencies to the project was not the solution, because the problem was that npm wasn't correctly installing them in the first place.

I created a PR that updates the local npm to 3.10.2. That should fix all these issues.

**Comment by warapitiya** [comment]
I get the same when `ng new projectName`

Ubuntu 16.04 LTS
Nodejs v4.4.7 LTS
npm v2.15.8

**Comment by jackvial** [comment]
Updating to the latest version of npm then reinstalling angular-cli worked for me.

**Comment by senayar** [comment]
Fresh install right now Windows 10
versions : 
 - node : 4.4.7
 - npm : 2.15.8
 Can't create new project returning error : 

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'through'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new UI (C:\Users\seny\AppData\Roaming\npm\node_modules\angular-cli\node_modules\ember-cli\lib\ui\index.js:37:19)
    at module.exports (C:\Users\seny\AppData\Roaming\npm\node_modules\angular-cli\node_modules\ember-cli\lib\cli\index.js:41:12)
    at module.exports (C:\Users\seny\AppData\Roaming\npm\node_modules\angular-cli\lib\cli\index.js:106:10)
    at C:\Users\seny\AppData\Roaming\npm\node_modules\angular-cli\bin\ng:31:5
    at C:\Users\seny\AppData\Roaming\npm\node_modules\angular-cli\node_modules\resolve\lib\async.js:46:14
    at process (C:\Users\seny\AppData\Roaming\npm\node_modules\angular-cli\node_modules\resolve\lib\async.js:173:43)
```


So go in : `C:\Users\senayar\AppData\Roaming\npm\node_modules\angular-cli`

and run `npm i`

problem fixed.

**Comment by Splaktar** [comment]
@senayar yes that is still needed until beta.9 is released if you aren't using the `master` version.

**Comment by ddagone** [comment]
I get this error message when I try to create new ng project | Os X El Capitan 

ng new tg
module.js:327
    throw err;
    ^

Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/lib/models/project.js:11:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by filipesilva** [comment]
As @Splaktar mentioned, the fix will be out in the next beta (beta.9).

Meanwhile what you can do is to delete `node_modules` inside your project and run `npm install`. That should fix every missing module.

**Comment by msiddiqi** [comment]
Updating npm to the latest version fixe the issue for me too.

**Comment by rbnzdave** [comment]
fresh install of windows 10, new download of node.js, while it installed ng without a problem it hit the sync issue immediately. I've got no package.json file to run, just following a tutorial to 
`npm install -g angular-cli

ng help`

and i get the errors.

**Comment by tieppt** [comment]
@rbnzdave scroll up, then install dev dependencies for angular-cli :up:

**Comment by ddagone** [comment]
New shit happens, I downloaded the node 6.x.x latest version it works fine for the ng new project command, but when I type ng serve it pops up an throw error 

Envoyé de mon iPhone

**Comment by msiddiqi** [comment]
Just do npm install in your project. That fixed it for me.

**Comment by ddagone** [comment]
I did it in /node_modules and in my project, So I really don’t understand


On 4 juillet 2016 at 21:30:50, Muhammad Siddiqi (notifications@github.com)
wrote:

Just do npm install in your project. That fixed it for me.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/angular/angular-cli/issues/1186#issuecomment-230345286>,
or mute the thread
<https://github.com/notifications/unsubscribe/AKTOFMbBepH69dFIPy2aAnvrll2fuYu6ks5qSV9pgaJpZM4I9KfJ>
.

**Comment by rbnzdave** [comment]
@tieppt yeah was going to do that today, was just pointing out that a fresh install of everything wasn't working either so wasnt just "update npm" :)

**Comment by rbnzdave** [comment]
using npm i -D [items] didnt work for me, i had to
```
npm install -g exists-sync
npm install -g object-assign
npm install -g minimatch
npm install -g walk-sync
npm install -g through
```

and now npm new reddit-clone is actually doing something for me. (following r33 tutorial mp4 from ng-book2. totally recommend)

**Comment by samirthebti** [comment]
Hi all : 
This problem is seriously blocker any help !!

**Comment by ddagone** [comment]
Ok, so to all the people who had this problem, please make sure you got the latest & current version of node installed (at this time : node : 6.2.2 and npm : 3.9.5) then install angular-cli by typing 
`npm install -g angular-cli` (sudo if you get warns) 
then go to `/node_modules`, find the angular-cli folder, and run `npm install` (`sudo` may be required) 
then, start a project `ng new projectname` go into the new created project folder and type ` npm i `. 
Peace !

**Comment by mchamo** [comment]
@ddagone is there a dependency on node 6.2.2?  I may have missed it, but, I don't see that stated on angular cli website or this git repo?

**Comment by ddagone** [comment]
I haven't missed any dependecies, I haven't installed the correct version
of node

**Comment by ctrl-brk** [comment]
Upgraded to the latest npm 5.0.3 and had
`angular cli cannot find module 'rsvp'`
Going to node_modules/angular/cli and running nmp i fixed it but...

**Comment by BenRacicot** [comment]
I can confirm the issue from @ctrl-brk however I cannot get it to work by `npm i` the cli #showstopper
