### ISSUE TITLE
angular-cli installation fails renaming /usr/local/lib/node_modules/.staging/abbrev 

### ISSUE THREAD

**Issue by manuelfink** [angular/angular-cli#1190]
## Environment

Mac on latest El Capitan
node v6.2.2 with npm 3.10.2
## Repro steps.
- trying to upgrading to latest cli tools (`sudo npm install -g angular-cli` or `sudo npm update -g angular-cli` not sure which i run)
- angular-cli / npm broken
- reintalling node
- trying to install angular-cli again
- intallation allways fails
## Error

```
$  sudo npm install -g angular-cli
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.2
npm ERR! path /usr/local/lib/node_modules/.staging/abbrev-432cdd5a
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-432cdd5a' -> '/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-432cdd5a' -> '/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/manuelfink/git/angular-2-cli-test/ContentFlows/npm-debug.log
npm ERR! code 1
```

**Comment by mikeybyker** [comment]
+1

**Comment by manuelfink** [comment]
But somehow its pretty weird, seems angular-cli is somehow breaking node installation.

Manual fix, hope i didn't forget anything:

````
# uninstalling globally installed libs
sudo npm uninstall -g angular-cli
sudo npm uninstall -g all-other-libraries

# uninstalling node
sudo rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/{npm*,node*,man1/node*}

# reinstall node

# update npm to ladest
sudo npm install -g npm

# reinstall angular-cli
sudo npm install -g angular-cli
```

**Comment by kylecordes** [comment]
Related to this: the procedure in the "upgrade guide":

https://github.com/angular/angular-cli#updating-angular-cli

is very off-putting, a negative quality signal. Many, many developers upgrade many NPM packages every day, without throwing away their NPM cache (!!).

To make these instruction confidence-inspiring, there should be:

* Explanation, even brief, of *why* this package (unlike countless others) requires throwing away the whole NPM cache for each upgrade.
* Hopefully a pointer to some known NPM defect that temporarily justifies the instructions.

**Comment by ciesielskico** [comment]
+1, Windows 10, running cmd as admin

npm v3.8.1
node v5.7.0

**Comment by hellobasti** [comment]
+1
El Capitan,
npm 3.9.5,
node 6.2.2

**Comment by filipesilva** [comment]
@manuelfink Very weird that it's breaking the global npm... I'll flag this as urgent but I don't have a linux machine to debug myself.

@kylecordes Angular-CLI uses the same upgrade guide as Ember-CLI because it is essentially an Ember-CLI addon. See https://github.com/ember-cli/ember-cli/releases

**Comment by geezhawk** [comment]
+1 
El Capitan, 
npm 3.10.5
node 6.3.0

**Comment by aebrow4** [comment]
+1
Yosemite
npm 3.5.3
node 5.5.0

kylecordes link works for fix:
https://github.com/angular/angular-cli#updating-angular-cli

**Comment by nikokosh** [comment]
I had the same problem on El Capitan
node 6.2.1
npm 3.9.3.

It was solved by simple uninstall of angular-cli:
`sudo npm uninstall -g angular-cli`

And its immediate reinstalling: 
`sudo npm install -g angular-cli`

Without npm reinstalling you can keep your cash and all the dependencies as it was.

**Comment by davidrensh** [comment]
Solved by (nothing else):
npm uninstall -g angular-cli
npm install -g angular-cli

**Comment by MacBaird** [comment]
+1 
Windows 10 64 bit

Also solved by @davidrensh  solution:
npm uninstall -g angular-cli
npm install -g angular-cli

**Comment by roelvanlisdonk** [comment]
This problem was also solved by @davidrensh solution:
npm uninstall -g angular-cli
npm install -g angular-cli

windows 10 64 bit
node v6.4.0
npm v3.10.3

**Comment by looselytyped** [comment]
@nikokosh and @davidrensh solution worked for me as well. No need to reinstall `npm`, or `node`. Simply `npm uninstall -g angular-cli` then `npm install -g angular-cli`

**Comment by ShadowManu** [comment]
The fixes mentioned here work for me too, but they happen again as soon as I try to run `npm install` or `npm update` after the fix. Can someone confirm if this happens too?

**Comment by makkart** [comment]
+1
El Capitan,
npm 3.10.7,
node 6.5.0

**Comment by manuelfink** [comment]
@filipesilva @ShadowManu I can confirm, still having the same issue every time I try to update angular-cli I ran across the problem.

**Comment by shubhangisheel** [comment]
In my case, I first changed my node version to 6.6.0 with nam 3.10.3. And then I changed my permissions of the location where node is located using the help of this link : https://docs.npmjs.com/getting-started/fixing-npm-permissions
I again got an error similar to this trail and then i finally uninstalled and installed my application using npm, it worked !

**Comment by lorenjerickson** [comment]
I can also confirm that after a failed angular-cli install due to this problem, if you uninstall angular-cli via npm and then reinstall angular-cli globally it works (or worked...for me...once).  

Window 10
Node 6.x
Npm 3.x

**Comment by prujohn** [comment]
@manuelfink The uninstall/reinstall worked for me on Windows 10 with node 6.x/npm 3.x.  Weird, but whatevs, it's working.  Thank you.

**Comment by anisa07** [comment]
Reinstall  -g angular-cli doesn't help me on win 8.1, node 4+, npm 3+. I get the same error. In the same time if I open location of angular-cli, on my pc and start ng new path\to\app from this location it actually creates folder and install dependencies

**Comment by irthos** [comment]
+1 on sierra

**Comment by hansl** [comment]
Closing this as obsolete. This is an NPM issue.

**Comment by tmcpro** [comment]
fixed by updating npm

**Comment by n-sikka** [comment]
Fixed the same error in multiple locations by deleting `node_modules`, `package-lock.json` and running `npm i` again. 
I was haiving these errors due to bumping up versions on dependencies i had.
