### ISSUE TITLE
Module not found: Error: Can't resolve 'xxx'

### ISSUE THREAD

**Issue by HarelM** [angular/angular-cli#16640]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Maybe, but it wasn't broken recently...

### Description

 A clear and concise description of the problem...
When importing an interface that is not in use inside a class, production build fails while debug build succeeds.

## 🔬 Minimal Reproduction

I'm not entirely sure, I think it's more complicated than a minimal reproduction.
Having said that, the following appvayor build fails with the relevant error message:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/30035366/job/hexmayblho5divm7
While the following succeeds:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/30041191/job/kambg0o4pinm408w
The following is the only change (removed unused interface from import statement):
https://github.com/IsraelHikingMap/Site/commit/d18ce4800e08c24f7bbf292ccd7627ee95abd8b3
Repository can be found here:
https://github.com/IsraelHikingMap/Site/
Relevant directory is the `IsraelHiking.Web`.

## 🔥 Exception or Error
I expect the production build to either fail with a meaningful error message or not fail at all.
I have spent several days to understand what was wrong the first time I encountered this issue. Fixing it will reduce other developers' frustrations.

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.0.3
Node: 10.15.3
OS: win32 x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cdk                      8.0.1
@angular/cli                      8.0.3
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.0.1
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
Can you try with the latest version of 8.x (currently 8.3.22)?

**Comment by HarelM** [comment]
I'll try, assuming it will not cost me the entire night to upgrade angular to the latest version...

**Comment by clydin** [comment]
`npm i -D @angular/cli@8.3.22` & `npm i -D @angular-devkit/build-angular@0.803.22` should be sufficient to test the issue.

**Comment by HarelM** [comment]
@clydin Thanks for the quick response and guidance! 
Seems like the issue was resolved in latest version.
I'll run a clean build using my CI server and if everything is working as expected I'll close this issue.

**Comment by HarelM** [comment]
Well, not surprisingly, After doing the above upgrade my tests started to fail with a different error message:
`Cannot read property 'ngMetadataName' of undefined`
Probably related to https://github.com/angular/angular-cli/issues/14888
I remembered there was a reason I didn't upgrade from 8.0.3 although when upgrading 8.0.4 was available...
Build is here:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/30086131/job/4b5cip9aw124u7kp

**Comment by clydin** [comment]
Updating Angular to at least 8.1 should fix that error.

**Comment by HarelM** [comment]
I'll try it tonight and update. I can't say that the error messages are developer friendly... :-/

**Comment by HarelM** [comment]
@clydin Thanks for your support. Seems like this doesn't reproduce in latest versions.

**Comment by clydin** [comment]
No problem.  Good to hear everything is working now.

**Comment by HarelM** [comment]
Seems like this issue still exists:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/30572655/job/6wok34p8kpw1rl1o
The following commit solved it failing build:
https://github.com/IsraelHikingMap/Site/commit/c2894e615dec2516b2066cb98f1b21d03fe53e88
My editor "grays out" unused types, but the build should not fail when this is the case, I believe.

**Comment by alan-agius4** [comment]
@HarelM is this still reproducible with version 9?

**Comment by HarelM** [comment]
I can't continue upgrading to see that the issue is resolved...
Please use my repo and commit above to upgrade and test it.
Feel free to send a PR of the upgrade if it succeeds ;-P

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
