### ISSUE TITLE
Error aSource is not in the SourceMap

### ISSUE THREAD

**Issue by chosroes** [angular/angular-cli#1982]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16.04

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: local (v1.0.0-beta.11-webpack.8, **branch: master**)
node: 6.5.0
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I updated to master branch and tried to build or serve

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
/home/test/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:704
      throw new Error('"' + aSource + '" is not in the SourceMap.');
            ^
Error: "/home/test/angular-cli/node_modules/angular2-template-loader/index.js!/var/www/html/public/project/src/app/app.component.ts" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/home/test/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:704:13)
    at /home/test/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:133:40
    at Array.forEach (native)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/home/test/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:132:32)
    at SourceMapSource.node (/home/test/angular-cli/node_modules/webpack-sources/lib/SourceMapSource.js:42:20)
    at ReplaceSource.node (/home/test/angular-cli/node_modules/webpack-sources/lib/ReplaceSource.js:66:29)
    at CachedSource.node (/home/test/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:12:23)
    at /home/test/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/test/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /home/test/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/test/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /home/test/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/test/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /home/test/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/test/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at ConcatSource.proto.sourceAndMap (/home/test/angular-cli/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:18)
    at CachedSource.sourceAndMap (/home/test/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:51:28)
    at Compilation.<anonymous> (/home/test/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:57:32)
```

5. Mention any other details that might be useful.

**Comment by chosroes** [comment]
When I set a new project with `ng new foo --link-cli`, the proble doesn't occur.

**Comment by Chabane** [comment]
I have the same issue on Mac OS X Yosemite.

**Comment by rokde** [comment]
The same on:
- angular-cli: 1.0.0-beta.14
- node: 6.4.0
- os: linux x64

**Comment by divid3byzero** [comment]
I have the same issue with:

- angular-cli: 1.0.0-beta.15
- node: 6.4.0
- os: darwin x64 (El Capitan 10.11.6)

**Comment by joao-fidalgo** [comment]
Having the same issue.

**Comment by MartinNuc** [comment]
Same issue.

angular-cli: 1.0.0-beta.15
node: 6.6.0
os: OSX 10.12 Sierra

**Comment by MartinNuc** [comment]
According to https://github.com/angular/angular-cli/issues/2319 you can solve it by `ng init`. So I tried that and compared what changed. There was nothing important in sources but looks like `ng init` clears `node_modules` and runs `npm install`. After that that it worked for me.

I got into this probably after replacing locally installed angular-cli with global one (`npm uninstall angular-cli`). So I guess something was left in `node_modules`.

**Comment by cloxure** [comment]
Same on Mac os El Capitan:

angular-cli: 1.0.0-beta.15
node: 6.6.0
os: darwin x64

**Comment by brianmadden** [comment]
Same issue.
angular-cli: 1.0.0-beta.15
node: 4.2.6
os: Ubuntu 16.04 x64

**Comment by CalebMacdonaldBlack** [comment]
@brianmadden Thank you so much! this worked for me

**Comment by ewu-youngb** [comment]
@brianmadden Thanks, that helped!

**Comment by svensp** [comment]
For us this happens when we give the node_modules as symlink instead of a folder inside the source. Presumably the webpack tries to include `node_modules/..` into the sourcemap.
Since it is a symlink `app/node_modules/..` is not actualy the same as `app/` so the app directory is not included in the sourcemap.

**Comment by filipesilva** [comment]
I'm having some trouble understanding this issue. So this happens when using the master branch directly, right? What else are you doing? Can you give me very explicit instructions for me to repro it?

I use the master branch every day and haven't ever seen this happen, so I'm wondering what the setup is, and how it differs from mine.

**Comment by brianmadden** [comment]
I think my case was caused by re-using an existing directory for my project. When I initially set the project up I re-used my existing project directory. Prior to initializing the cli project I did a `rm -rf *` in the project directory and everything worked on that computer. 

I then pushed to github and pulled on my laptop. This is where I believe things went wrong. There were files left over on my laptop from the old project, but they weren't tracked by git so weren't deleted when I pulled. I think the problem was the lingering files, and this is why the `git clean` and re-run of `npm install` fixed the issue for me.

**Comment by rokde** [comment]
@svensp said, that we are using a symlinked "node_modules" folder. And running the build process does not handle the correct resolvement of the "../node_modules" (in webpack) to get the correct real path.

This happens in our docker node environment where the node_modules folder is just a symlink from within the docker image/container. So your project dir has not the node_modules content, only the symlink.

**Comment by filipesilva** [comment]
This might solve it then, can you test making this change manually? https://github.com/angular/angular-cli/pull/2291

**Comment by chosroes** [comment]
I updated to latest angular-cli (no master anymore).
What I've done:
sudo npm uninstall -g angular-cli
sudo npm cache clean
sudo npm install -g angular-cli@latest
rm -rf node_modules dist tmp
npm link angular-cli
ng init

Then ng serve. And I still have the error.

I do not have angular-cli/models/webpack-build-common.ts file in my node_modules.

My project was initiated on beta.11-webpack.8 version. And I updated regularly the code.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/2291

**Comment by vinchauhan** [comment]
Same issue

**Comment by vinchauhan** [comment]
For some of us the command - ng new app-name - needs to be run with sudo

**Comment by derailed** [comment]
Having the exact same issue building a docker image. Using Node:6.7.0 and CLI:1.0.0-beta.19-3. It works fine in dev mode but when I change NODE_ENV=production, $ ng build, fails with the following error:

/usr/lib/node_modules/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:704
      throw new Error('"' + aSource + '" is not in the SourceMap.');

**Comment by doliver3** [comment]
I have the same problem on linux with a brand new folder and use of ng init and latest version of node 7.  This issue is not fixed.

**Comment by mayakwd** [comment]
Any workaround? Same issue

**Comment by JSMike** [comment]
For docker users. Are your node_modules being shared from the host machine? there may be an issue with how docker follows the sym-links in your mounted directories. Look into installing node_modules with --no-bin-links

**Comment by valterbarros** [comment]
@JSMike how can install with `--no-bin-links,` it's a flag in **ng**? Thank you

**Comment by JSMike** [comment]
it's an NPM flag, you can do `ng new --skip-npm` and then `npm install --no-bin-links`

**Comment by valterbarros** [comment]
@JSMike Thank it's work here
