### ISSUE TITLE
ng serve: compile time 10x slower with tailwind 2.2.x

### ISSUE THREAD

**Issue by gianmd** [angular/angular-cli#21228]
# 🐞 Bug report

### Command (mark with an `x`)

- [x]  serve

### Is this a regression?

Problematic Angular-cli version: `^11.2.10`

Previous TailwindCSS version with no problem: `TailwindCSS@2.1.2`

Problematic Version: `TailwindCSS@2.2.4`

### Description

Since Angular-cli `v11.2` started supporting TailwindCSS natively, we decided to upgrade our codebase to use TailwindCSS instead of custom css on the most part of our app. 

We use tailwindCSS with JIT mode enabled, and we haven't had any problems until now.

Recently TailwindCSS upgraded to version `2.2.4` and bringing [more features](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0), and a[ New dependency tracking system](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0#changes-and-deprecations) for Just-in-Time mode. The latest tracking system dependency is compatible with *webpack 4* and *webpack 5* (using the latest `postcss-loader@^4` and `postcss-loader@^5`),  So we decided to upgrade to this version and now we are experiencing x10 compilation times.

Our application is quite large and typically experience ~5 incremental compile times with `ng serve`.  With the new version of `tailwindcss@2.2.4` this compiling times are now ~65seconds on each save.

## 🔬 Minimal Reproduction

Since our app is large, it is hard to replicate the problem on a new repo. I'm attaching the CPU Profiles comparing the 2 tailwindCSS versions.

[CPU Profiles ZIP](https://github.com/angular/angular-cli/files/6728125/Archive.zip)

### CPU profile screenshots
![With TailwindCss 2.1.2](https://user-images.githubusercontent.com/1205734/123676941-8823f180-d812-11eb-9b66-993709ef17ce.png)
![With TailwindCss 2.2.4](https://user-images.githubusercontent.com/1205734/123676949-89edb500-d812-11eb-948e-4239e3bfe3f1.png)

***Our test goes like this***

1. Run `ng serve` ( `node --max_old-space-size=12000 ./node_modules/@angular/cli/bin/ng serve` )
2. Add a tailwind class to any div element (`class="bg-red-500"`)
3. Save file

## 🌍 Your Environment

```yaml
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.2.10
Node: 14.16.1
OS: darwin x64

Angular: 11.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.10
@angular-devkit/build-angular      0.1102.10
@angular-devkit/core               11.2.10
@angular-devkit/schematics         11.2.10
@angular/cdk                       11.2.10
@angular/cli                       11.2.10
@angular/fire                      6.1.4
@angular/google-maps               11.2.10
@angular/material                  11.2.10
@angular/material-moment-adapter   11.2.10
@schematics/angular                11.0.1
@schematics/update                 0.1102.10
ng-packagr                         11.0.2
rxjs                               6.6.7
typescript                         4.0.5
webpack                            4.44.2
```

**Anything else relevant?**

[TailwindCSS 2.2.0 Changelog on JIT mode](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0#changes-and-deprecations)

**Comment by alan-agius4** [comment]
The first thing I noticed is that there are a large number of Sass compilations which take around 16.4s.

From some debugging I noticed that tailwind is adding a virtual directory
```
/var/folders/mp/zsgl3srd389_js72bk4_bkgh0000gn/T/tmp-40075-H4BHLbbaPPgx
```

This has a dependency on all the component stylesheets. 
```
/Users/alanagius/cli-reproductions/tailwinds/src/app/app.component.scss
/Users/alanagius/cli-reproductions/tailwinds/src/app/foo/foo.component.scss
/Users/alanagius/cli-reproductions/tailwinds/src/app/foo/zar/zar.component.scss
/Users/alanagius/cli-reproductions/tailwinds/src/app/foo/bar/bar.component.scss
```

This directory is being invalidated with on every change which cause all components will invalidated and recompiled.

**Comment by gianmd** [comment]
@alan-agius4 Let me know if you need something else from me

**Comment by karptonite** [comment]
Just ran into this problem myself. So in case you were wondering, it isn't just you. I'll be reverting to the older tailwindcss for now, I think.

**Comment by alan-agius4** [comment]
@karptonite, are you using Angular CLI 11 as well? If so, can you please update to the latest version and try again?

I tried to replicate this issue using the latest version of tailwindcss, webpack and Angular CLI and I am unable.

Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

**Comment by karptonite** [comment]
I am on Angular CLI 11. If this is fixed in 12, that is great, and I can give it a try once our other dependencies are updated for Angular 12. Do you happen to know if it was fixed in the CLI 11 branch later than 11.2.10?

**Comment by gianmd** [comment]
Just tested our app with `angular/cli@v12.1.0` and `tailwindcss@2.2.4` vs `tailwindcss@2.1.2`  and the **issue still present.** 

Times on Angular v12 are faster than v11 but still considerably longer with the lower version of tailwindcss. ~3seconds vs ~30seconds between each save.

Here the cpu profiles recorded of  the 2 tailwind versions with `Angular 12.1.0`

## Angular v12.1.0 - TailwindCSS v.2.1.2 

![image](https://user-images.githubusercontent.com/1205734/124011564-25675d00-d9ae-11eb-8972-976d34a1725d.png)

## Angular v12.1.0 - TailwindCSS v.2.2.4

![image](https://user-images.githubusercontent.com/1205734/124011674-429c2b80-d9ae-11eb-9bd8-406facc128b8.png)

Recorded CPU profiles 
[Angular12-Tailwind- CPU Profiles.zip](https://github.com/angular/angular-cli/files/6743149/Angular12-Tailwind-.CPU.Profiles.zip)

Hope this helps @alan-agius4

**Comment by alan-agius4** [comment]
Hi @gianmd,

Can you try to add the below in `node_modules/@ngtools/webpack/src/ivy/plugin.js` Line 153 and see if it helps?

```diff
for (const changedFile of [...compiler.modifiedFiles, ...compiler.removedFiles]) {
+    if (!require('path').extname(changedFile)) {
+        continue;
+   }

    const normalizedChangedFile = paths_1.normalizePath(changedFile);
    // Invalidate file dependencies
    this.fileDependencies.delete(normalizedChangedFile);
    // Invalidate existing cache
    cache.invalidate(normalizedChangedFile);
    changedFiles.add(normalizedChangedFile);
}
```

**Comment by gianmd** [comment]
Hi @alan-agius4 
Just tried your suggestion, **unfortunately, no change in serving times.** 

|                                | Test 1 | Test 2 |
|--------------------------------|:-----------------:|:-----------------:|
| Angular CLI Version                |      12.11.0      |      12.11.0      |
| TailwindCSS Version                |      2.1.2      |      2.2.4     |
| Profile Screenshot                    |    ![image](https://user-images.githubusercontent.com/1205734/124136266-9b250480-da52-11eb-8003-5ef00295658f.png)   |   ![image](https://user-images.githubusercontent.com/1205734/124136440-c7408580-da52-11eb-83e6-f726ed688562.png)   |
| Compiling time on file change |         ~6s        |         ~26s        |


[Profiles-PluginChange.zip](https://github.com/angular/angular-cli/files/6748687/Profiles-PluginChange.zip)

**Comment by alan-agius4** [comment]
Can you try to provide a minimal reproduction? 

I am having some trouble replicating this behaviour with version 12.

**Comment by gianmd** [comment]
@alan-agius4  I was able to recreate a minimal reproduction on a fresh angular project.
for the demo, I had to create multiple components using a lot of tailwind classes

You can clone the repo here https://github.com/gianmd/tailwindcss-angular12-replica

1. Clone [Repo](https://github.com/gianmd/tailwindcss-angular12-replica)
2. npm install
3. ng serve
4. on `master` branch (`Angular CLI 12.1.0` -` TailwindCSS 2.2.4`) you can add a line on any HTML template and you will see increated compiling times.

You can compare compiling times with `tailwind-2.1.2` branch inside the repo. (be sure to remove node_modules and npm install again)
bigger the app, compilation times increased. on this demo, times went from ~700ms per save to ~8seconds per save

Bellow the result of the tests with this reproduction repo
|                                | Test 1 | Test 2 |
|--------------------------------|:-----------------:|:-----------------:|
| Branch               |     tailwind-2.1.2      |      master      |
| Angular CLI Version                |      12.11.0      |      12.11.0      |
| TailwindCSS Version                |      2.1.2      |      2.2.4     |
| Profile Screenshot                    |    ![image](https://user-images.githubusercontent.com/1205734/124168387-10083680-da73-11eb-9aaa-8f12de1343ed.png)   |   ![image](https://user-images.githubusercontent.com/1205734/124168319-fb2ba300-da72-11eb-957a-e33d6837173c.png)   |
| Compiling time on file change |         ~700ms        |         ~8s        |

Profiles files
[profiles-reproduction-demo.zip](https://github.com/angular/angular-cli/files/6749932/profiles-reproduction-demo.zip)

**Comment by alan-agius4** [comment]
@gianmd thanks for the repro, I’ll look into it, in the next couple of days.
