### ISSUE TITLE
ng build error: Invalid version: "15.2-15.3"

### ISSUE THREAD

**Issue by shakeri** [angular/angular-cli#22606]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 When i build project with Angular CLI, I get this error:

`An unhandled exception occurred: Transform failed with 1 error:
error: Invalid version: "15.2-15.3"
See "C:\Users\MOHAMM~1\AppData\Local\Temp\ng-JBqIfM\angular-errors.log" for further details.`

And in `angular-errors.log` file:
```
[error] HookWebpackError: Transform failed with 1 error:
error: Invalid version: "15.2-15.3"
    at makeWebpackError (E:\workingfolder\test-app\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at E:\workingfolder\test-app\node_modules\webpack\lib\Compilation.js:3057:12
    at eval (eval at create (E:\workingfolder\test-app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:98:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
Error: Transform failed with 1 error:
error: Invalid version: "15.2-15.3"
    at failureErrorWithLog (E:\workingfolder\test-app\node_modules\@angular-devkit\build-angular\node_modules\esbuild\lib\main.js:1557:15)
    at E:\workingfolder\test-app\node_modules\@angular-devkit\build-angular\node_modules\esbuild\lib\main.js:1346:29
    at E:\workingfolder\test-app\node_modules\@angular-devkit\build-angular\node_modules\esbuild\lib\main.js:637:9
    at handleIncomingPacket (E:\workingfolder\test-app\node_modules\@angular-devkit\build-angular\node_modules\esbuild\lib\main.js:734:9)
    at Socket.readFromStdout (E:\workingfolder\test-app\node_modules\@angular-devkit\build-angular\node_modules\esbuild\lib\main.js:604:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 13.2.0
Node: 16.13.2
Package Manager: npm 8.4.0
OS: win32 x64

Angular: 13.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.0
@angular-devkit/build-angular   13.2.0
@angular-devkit/core            13.2.0
@angular-devkit/schematics      13.2.0
@schematics/angular             13.2.0
rxjs                            7.5.2
typescript                      4.5.5
</code></pre>

**Comment by idwebmedia** [comment]
Literally was coming here to post the exact error. thanks

**Comment by jmbarbier** [comment]
This comes from browserslist

`npx browserslist`

```
and_chr 97
and_ff 95
and_qq 10.4
and_uc 12.12
android 97
baidu 7.12
chrome 97
chrome 96
chrome 95
chrome 94
edge 97
edge 96
firefox 96
firefox 95
firefox 94
firefox 91
firefox 78
ie 11
ios_saf 15.2-15.3
ios_saf 15.0-15.1
ios_saf 14.5-14.8
ios_saf 14.0-14.4
ios_saf 12.2-12.5
kaios 2.5
op_mini all
op_mob 64
opera 82
opera 81
safari 15.2-15.3
safari 15.1
safari 14.1
safari 13.1
samsung 16.0
samsung 15.0
```
The versions interval comes from here :
```
ios_saf 15.2-15.3
```
clearing .browserslistrc makes compilation happy again but this is not a real solution !

**Comment by idwebmedia** [comment]
> This comes from browserslist
> 
> `npx browserslist`
> 
> ```
> and_chr 97
> and_ff 95
> and_qq 10.4
> and_uc 12.12
> android 97
> baidu 7.12
> chrome 97
> chrome 96
> chrome 95
> chrome 94
> edge 97
> edge 96
> firefox 96
> firefox 95
> firefox 94
> firefox 91
> firefox 78
> ie 11
> ios_saf 15.2-15.3
> ios_saf 15.0-15.1
> ios_saf 14.5-14.8
> ios_saf 14.0-14.4
> ios_saf 12.2-12.5
> kaios 2.5
> op_mini all
> op_mob 64
> opera 82
> opera 81
> safari 15.2-15.3
> safari 15.1
> safari 14.1
> safari 13.1
> samsung 16.0
> samsung 15.0
> ```
> 
> The versions interval comes from here :
> 
> ```
> ios_saf 15.2-15.3
> ```
> 
> clearing .browserslistrc makes compilation happy again but this is not a real solution !

works. thanks

**Comment by cvandradg** [comment]
Removing content or properly configurating .browserslistrc file fixes it indeed. Thanks @idwebmedia

**Comment by danielehrhardt** [comment]
> Removing content or properly configurating .browserslistrc file fixes it indeed. Thanks @idwebmedia

But i mean i want to have the configuration from the Browserlistrc file?

**Comment by abf7d** [comment]
This doesn't solve my problem. I am building a library, not an app. The library doesn't have a `.browserlistrc` file. There's no `.browserlistrc` in the root folder either. When I run `ng build my-library` I get the following:
```
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'my-library'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
Transform failed with 1 error:
error: Invalid version: "15.2-15.3"
```
Any ideas?

**Comment by abadakhshan** [comment]
@abf7d 

add a .browserlistrc with this content to your library

```
# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
# For additional information regarding the format and rule options, please see:
# https://github.com/browserslist/browserslist#queries

# For the full list of supported browsers by the Angular framework, please see:
# https://angular.io/guide/browser-support

# You can see what browsers were selected by your queries by running:
#   npx browserslist

last 1 Chrome version
last 1 Firefox version

Firefox ESR
not IE 11 # Angular supports IE 11 only as an opt-in. To opt-in, remove the 'not' prefix on this line.
```

**Comment by AlienAggressor** [comment]
package.json

```
{
...
  "browserslist": [
    "and_chr 97",
    "and_ff 95",
    "and_qq 10.4",
    "and_uc 12.12",
    "android 97",
    "baidu 7.12",
    "chrome 97",
    "chrome 96",
    "chrome 95",
    "chrome 94",
    "edge 97",
    "edge 96",
    "firefox 96",
    "firefox 95",
    "firefox 94",
    "firefox 91",
    "firefox 78",
    "ie 11",
    "ios_saf 15.0-15.1",
    "ios_saf 14.0-14.4",
    "kaios 2.5",
    "op_mini all",
    "op_mob 64",
    "opera 82",
    "safari 13.1",
    "samsung 16.0",
    "samsung 15.0"
  ],
  ...
}
```

Works for me.

**Comment by abf7d** [comment]
> add a `.browserlistrc` with this content to your library

This worked for me. Thanks!

**Comment by henrikdahl8240** [comment]
Are you serious, Angular apps cannot run on the newest versions of IOS anymore?

Should it really be an improvement?

I suppose this has passed the internal tests, i.e. deemed fine that Angular apps cannot run on the newest versions of IOS anymore.

I must say, that I totally disagree on that position.

Is this going to remain, because then I must revert to the previous version of Angular.

Is it the official policy of Angular, that going forward support for IOS should be discontinued?

**Comment by nhhockeyplayer** [comment]
this isnt fun

https://github.com/nrwl/nx/issues/8768

with .browserslistrc
or without .browserslistrc
or an empty .browserslistrc

nothing works

nx fails out of the box when a project is attempted to be created with `npx create-nx-workspace@latest`

**Comment by alan-agius4** [comment]
@henrikdahl8240, this is just a bug in the parsing logic of Safari browser versions which needs to be corrected.

We expect browserslist to return an entry for each version (`"safari 15.2", "safari 15.3"`) instead of a range  (`"safari 15.2-15.3"`). 

This issue is also causing by a change in a transitive dependency which was released over the weekend `caniuse-lite` which as a result is also causing our (angular-cli) CI to be red.

I should be able to land a fix for this tomorrow.

**Comment by henrikdahl8240** [comment]
@alan-agius4 OK. So will it be version 13.2.1 so we can just run update once more?

**Comment by alan-agius4** [comment]
Yes, once release `13.2.1`should contain the fix for this issue…

**Comment by henrikdahl8240** [comment]
@alan-agius4 , do you think it may also be released tomorrow or when do you think it may be released?

My real point obviously is, if I should rollback or just wait until tomorrow.

**Comment by rashad-farajullayev** [comment]
I resolved the problem. 
Create a file in the root directory with the name ".browserslistrc"
and put into it the following content:
```
# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
# For additional information regarding the format and rule options, please see:
# https://github.com/browserslist/browserslist#queries

# For the full list of supported browsers by the Angular framework, please see:
# https://angular.io/guide/browser-support

# You can see what browsers were selected by your queries by running:
#   npx browserslist

last 1 Chrome version
last 1 Firefox version
last 2 Edge major versions
last 2 Safari major versions
last 2 iOS major versions
Firefox ESR
not IE 9-10 # Angular support for IE 9-10 has been deprecated and will be removed as of Angular v11. To opt-in, remove the 'not' prefix on this line.
not IE 11 # Angular supports IE 11 only as an opt-in. To opt-in, remove the 'not' prefix on this line.
not ios_saf 15.2-15.3
not safari 15.2-15.3
```

**Comment by nhhockeyplayer** [comment]
> @henrikdahl8240, this is just a bug in the parsing logic of Safari browser versions which needs to be corrected.
> 
> We expect browserslist to return an entry for each version (`"safari 15.2", "safari 15.3"`) instead of a range (`"safari 15.2-15.3"`).
> 
> This issue is also causing by a change in a transitive dependency which was released over the weekend `caniuse-lite` which as a result is also causing our (angular-cli) CI to be red.
> 
> I should be able to land a fix for this tomorrow.

ok it seems apple gang flanked and no one knew it could happen. After releasing my app thrut heir playstore process I deemed apple a failed organization. Execs stole all the money and they left nothing to make their R&D ripe. so beware of the apple gang as well.

**Comment by nhhockeyplayer** [comment]
> I resolved the problem. Create a file in the root directory with the name ".browserslistrc" and put into it the following content:
> 
> ```
> # This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
> # For additional information regarding the format and rule options, please see:
> # https://github.com/browserslist/browserslist#queries
> 
> # For the full list of supported browsers by the Angular framework, please see:
> # https://angular.io/guide/browser-support
> 
> # You can see what browsers were selected by your queries by running:
> #   npx browserslist
> 
> last 1 Chrome version
> last 1 Firefox version
> last 2 Edge major versions
> last 2 Safari major versions
> last 2 iOS major versions
> Firefox ESR
> not IE 9-10 # Angular support for IE 9-10 has been deprecated and will be removed as of Angular v11. To opt-in, remove the 'not' prefix on this line.
> not IE 11 # Angular supports IE 11 only as an opt-in. To opt-in, remove the 'not' prefix on this line.
> not ios_saf 15.2-15.3
> not safari 15.2-15.3
> ```

this solutions did not work for my nx/angular

thanks for trying

**Comment by nhhockeyplayer** [comment]
my suggestion is to roll it back
all fluff no stuff
and no huff

re-think what the ground conditions are
and proceed with caution

simple

if you can create an nx project and run nx report and compile an nx project... that should be a flag ship unit test

**Comment by nhhockeyplayer** [comment]
regular expressions are fairly fail safe if modeled properly... bulletproof
any version logic should rightfully be using regular expressions
just another helpful suggestion
if you have any snippets Im happy to assist

**Comment by abadakhshan** [comment]
> Yes, once released `13.2.1`should contain the fix for this issue.

It should be fixed in Angular 12 too.

Thank you.

**Comment by mshima** [comment]
This workaround seems to work:
```
npm install caniuse-lite@1.0.30001303 --save-dev --save-exact
```
If don't, add to npm `overrides` or yarn `resolutions`.

**Comment by otmos** [comment]
To resolve the issue , edit the browser list on Package.json file , the browserlistrc file isn't taken into consideration.

and use a configuration that explicitly specifies not to build for these Browser versions , like this one : 
"browserslist": [
    "android 97",
    "chrome 97",
    "chrome 96",
    "chrome 95",
    "chrome 94",
    "edge 97",
    "edge 96",
    "firefox 96",
    "firefox 95",
    "firefox 94",
    "firefox 91",
    "firefox 78",
    "ios_saf 15.0-15.1",
    "ios_saf 14.0-14.4",
    "kaios 2.5",
    "opera 82",
    "safari 13.1",
    "samsung 16.0",
    "samsung 15.0"
  ]

You can verify if the modification is taken into account by running the following command : npx browserslist

**Comment by alan-agius4** [comment]
@abadakhshan, the fix will also be back ported to version 12.

**Comment by veronika-prokopiv** [comment]
Had the same issue, using Angular v.13.1.1. Removing the line "last 2 Safari major versions" from the file .browserslistrc fixed this issue for me.

**Comment by nhhockeyplayer** [comment]
> To resolve the issue , edit the browser list on Package.json file , the browserlistrc file isn't taken into consideration.
> 
> and use a configuration that explicitly specifies not to build for these Browser versions , like this one : "browserslist": [ "android 97", "chrome 97", "chrome 96", "chrome 95", "chrome 94", "edge 97", "edge 96", "firefox 96", "firefox 95", "firefox 94", "firefox 91", "firefox 78", "ios_saf 15.0-15.1", "ios_saf 14.0-14.4", "kaios 2.5", "opera 82", "safari 13.1", "samsung 16.0", "samsung 15.0" ]
> 
> You can verify if the modification is taken into account by running the following command : npx browserslist

this solution still fails nx project

package.json
```
{
...
  "browserslist": [
    "android 97",
    "chrome 97",
    "chrome 96",
    "chrome 95",
    "chrome 94",
    "edge 97",
    "edge 96",
    "firefox 96",
    "firefox 95",
    "firefox 94",
    "firefox 91",
    "firefox 78",
    "ios_saf 15.0-15.1",
    "ios_saf 14.0-14.4",
    "kaios 2.5",
    "opera 82",
    "safari 13.1",
    "samsung 16.0",
    "samsung 15.0"
  ]
}
```

meanstack02@admin lmig % nx run-many --all --target build

    ✔  nx run api:build (4s)

    ✖  nx run lmds:build:production
✔ Browser application bundle generation complete.
       Transform failed with 1 error:
       error: Invalid version: "15.2-15.3"
       

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 2 projects (5s)
 
    ✖    1/2 failed
    ✔    1/2 succeeded [0 read from cache]
 
   See Nx Cloud run details at https://nx.app/runs/AenVG4NCJI0

**Comment by JKennedy24** [comment]
Also seeing this issue Angular 12

**Comment by GregoireLgt** [comment]
> This workaround seems to work:
> 
> ```
> npm install caniuse-lite@1.0.30001303 --save-dev --save-exact
> ```
> 
> If don't, add to npm `overrides` or yarn `resolutions`.

Having this error after using this workaround
![image](https://user-images.githubusercontent.com/47480030/151814619-a5a28d9c-949b-44bb-9ad5-ad17aaae33de.png)

**Comment by Shan7anu** [comment]
Facing same issue in Angular 12 @alan-agius4

**Comment by dgp1130** [comment]
Fix is merged and we're triggering a release now, should be out soon.

**Comment by dgp1130** [comment]
This is fixed in v12.2.16 and v13.2.1, please update if you are experiencing this issue. Users on v11 shouldn't be affected.

**Comment by nhhockeyplayer** [comment]
ok this looks good now... thank you for the response to this

nx is building

**Comment by sass1997** [comment]
> This is fixed in v12.2.16 and v13.2.1, please update if you are experiencing this issue. Users on v11 shouldn't be affected.

I do also have to problem in v13.1.x do I need to upgrade to v13.2.x or will it also be fixed in this version

**Comment by alan-agius4** [comment]
@sass1997, you will need to update to v13.2.1.

**Comment by gkTim** [comment]
I have updated to 13.2.1 but still got this error.

**Comment by gkTim** [comment]
@henrikdahl8240 okay maybe it is currently not available I only thought it is about the angular-cli package and this is available in version 13.2.1

**Comment by henrikdahl8240** [comment]
@gkTim , yes, since yesterday evening, Danish time, but it is not.

**Comment by alan-agius4** [comment]
You need to update `@angular/cli` and @angular-devkit/build-angular` to version `13.2.1` and not `@angular/core`.

You can run the below command:
```
ng update @angular/cli
```

**Comment by JKennedy24** [comment]
@alan-agius4 what about if we are running angular 12? Running the command `ng update @angular/cli` pushed all my libs up to angular 13. But we need to stay on 12

**Comment by henrikdahl8240** [comment]
@JKennedy24 Perhaps you should have used @angular/cli@TheVersionYouPreferred?

**Comment by t-ricci-delta** [comment]
For anyone using NX it's tracked here: https://github.com/nrwl/nx/issues/8768

**Comment by KirillMetrik** [comment]
> I have updated to 13.2.1 but still got this error. (Nx repo maybe also an existing error there?)

I confirm the same - using Nx and after upgrading to 13.2.1 nothing changed. Still the same error.

**Comment by JKennedy24** [comment]
I had to run:
`ng update @angular/cli@12.2.16
ng update @angular-devkit/build-angular@12.2.16 --legacy-peer-deps`

And this worked

**Comment by henrikdahl8240** [comment]
@alan-agius4 I would like to confirm, that after I have run `ng update @angular/cli` compilation goes without any issue.

**Comment by Ketec** [comment]
12.2.6 upgrade alone does not work for those building libraries.
ng-packager also needs an update (12.2.7 worked)

**Comment by campelo** [comment]
> I resolved the problem. Create a file in the root directory with the name ".browserslistrc" and put into it the following content:
> 
> ```
> # This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
> # For additional information regarding the format and rule options, please see:
> # https://github.com/browserslist/browserslist#queries
> 
> # For the full list of supported browsers by the Angular framework, please see:
> # https://angular.io/guide/browser-support
> 
> # You can see what browsers were selected by your queries by running:
> #   npx browserslist
> 
> last 1 Chrome version
> last 1 Firefox version
> last 2 Edge major versions
> last 2 Safari major versions
> last 2 iOS major versions
> Firefox ESR
> not IE 9-10 # Angular support for IE 9-10 has been deprecated and will be removed as of Angular v11. To opt-in, remove the 'not' prefix on this line.
> not IE 11 # Angular supports IE 11 only as an opt-in. To opt-in, remove the 'not' prefix on this line.
> not ios_saf 15.2-15.3
> not safari 15.2-15.3
> ```

This worked for me! Thanks.

**Comment by DevilishMan** [comment]
added the following lines to the default .browserslistrc, and it was resolved.

not ios_saf 15.2-15.3
not safari 15.2-15.3

**Comment by henrikdahl8240** [comment]
@Sampath-Lokuge Please allow me to ask you a question, which is a bit off topic. I would say that I am rather mastering Angular and I have a master's degree in computer science. I could also be interested in developing native IOS and Android apps, e.g. using Ionic. Therefore I would like to kindly ask you, is it relatively easy and quick to learn or is it a huge field it requires many, many hours for studying in order to do something meaningful, i.e. professional app, when considering the Ionic contribution in workload?

**Comment by Sampath-Lokuge** [comment]
Hi @henrikdahl8240 
If you know Angular then learning Ionic is super easy. I would like to help you here. i.e. I can recommend good courses and etc. to you. You can find out my email on my Git profile.

**Comment by Sampath-Lokuge** [comment]
Hi @henrikdahl8240 
Yes, I have developed around 30 Native Ionic/Angular apps within the last 6 years for the USA and European clients. So we can have almost any native feature using Capacitor and Cordova plugins. It has that much of a huge list of native plugins.

Cordova Plugins: https://ionicframework.com/docs/native

Capacitor Plugins: https://github.com/riderx/awesome-capacitor

**Comment by panchazo** [comment]
Updating with ng update didnt resolve it, in my case adding the 2 lines in .browserslistrc did

> added the following lines to the default .browserslistrc, and it was resolved.
> 
> not ios_saf 15.2-15.3 not safari 15.2-15.3

**Comment by tonovarela** [comment]
It works
Thanks

**Comment by nimatrazmjo** [comment]
hello guys,

adding all of the above solution didnt work for me.

So I had to run `npm audit fix --force` after updating `.browserslistrc`, and it worked for me.

**Comment by fredand44** [comment]
Hello guys, I am really new to angular (but have used maven a lot). 
I would like to learn how to pack a angular app with maven and run it from a app-server like weblogic for eg.
If I remeber correct used this tutorial (or any plain vanilla angular-app I guess would work as well):

https://vorozco.com/blog/2019/2019-09-11-Packagin-Angular-8-Apps-War.html

But during this work I run into the same problem as in this thread.

I did not have a .browserlistrc file.
But I had a package.json-file.
I just took a wild stab in the dark and changed the following in that file:

  "devDependencies": {
    "@angular-devkit/build-angular": "~13.1.2",
    "@angular/cli": "~13.1.2",

to
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.2.1",
    "@angular/cli": "~13.2.1",

Voila it builds.

Please comment if this is a bad solution.
How ever it now seems to be able to pack witk maven and run from my weblogic 14.1.1
Best regards
Fredrik

**Comment by lukzard** [comment]
What is the impact of the built artefacts when excluding iOS Safari and Safari from the list of browsers please? Any negative impact we should be aware of?

And, i understand this to be a work-around, think the right solution is to make transitive dependencies work in the build process. Any perspectives and timelines here?

Cheers,

**Comment by harisiltifat** [comment]
you should yourself create .browserlistsrc file incase it is not present in your project folder.

**Comment by contributorpw** [comment]
So editing `.browserslistrc` is a nonsense. Just update your `ng` upto 13.2. Check your global and local versions of Angular CLI.

**Comment by Santoshah** [comment]
> # This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
> # For additional information regarding the format and rule options, please see:
> # https://github.com/browserslist/browserslist#queries
> 
> # For the full list of supported browsers by the Angular framework, please see:
> # https://angular.io/guide/browser-support
> 
> # You can see what browsers were selected by your queries by running:
> #   npx browserslist
> 
> last 1 Chrome version
> last 1 Firefox version
> 
> Firefox ESR
> not IE 11 # Angular supports IE 11 only as an opt-in. To opt-in, remove the 'not' prefix on this line.

I had to remove 

> package.json
> 
> ```
> {
> ...
>   "browserslist": [
>     "and_chr 97",
>     "and_ff 95",
>     "and_qq 10.4",
>     "and_uc 12.12",
>     "android 97",
>     "baidu 7.12",
>     "chrome 97",
>     "chrome 96",
>     "chrome 95",
>     "chrome 94",
>     "edge 97",
>     "edge 96",
>     "firefox 96",
>     "firefox 95",
>     "firefox 94",
>     "firefox 91",
>     "firefox 78",
>     "ie 11",
>     "ios_saf 15.0-15.1",
>     "ios_saf 14.0-14.4",
>     "kaios 2.5",
>     "op_mini all",
>     "op_mob 64",
>     "opera 82",
>     "safari 13.1",
>     "samsung 16.0",
>     "samsung 15.0"
>   ],
>   ...
> }
> ```
> 
> This worked for me.

I had to remove Android 97 to make this work.

**Comment by bedoya199712** [comment]
> Resolví el problema. Cree un archivo en el directorio raíz con el nombre ".browserslistrc" y coloque en él el siguiente contenido:
> 
> ```
> # This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
> # For additional information regarding the format and rule options, please see:
> # https://github.com/browserslist/browserslist#queries
> 
> # For the full list of supported browsers by the Angular framework, please see:
> # https://angular.io/guide/browser-support
> 
> # You can see what browsers were selected by your queries by running:
> #   npx browserslist
> 
> last 1 Chrome version
> last 1 Firefox version
> last 2 Edge major versions
> last 2 Safari major versions
> last 2 iOS major versions
> Firefox ESR
> not IE 9-10 # Angular support for IE 9-10 has been deprecated and will be removed as of Angular v11. To opt-in, remove the 'not' prefix on this line.
> not IE 11 # Angular supports IE 11 only as an opt-in. To opt-in, remove the 'not' prefix on this line.
> not ios_saf 15.2-15.3
> not safari 15.2-15.3
> ```

Eres Dios bro, muchas gracias.

**Comment by hamza124** [comment]
Hello Guys
i try npm audit fix --force after updated, browserlist file with below.
last 2 Chrome version
last 2 Firefox version
last 2 Edge major versions
last 2 Safari major versions
last 2 iOS major versions
Firefox ESR
not IE 11 # Angular supports IE 11 only as an opt-in. To opt-in, remove the 'not' prefix on this line.
it's resolved with me

**Comment by eemt** [comment]
> Yes, once released `13.2.1`should contain the fix for this issue.

That's great.  Thanks.  Any chance the fix is going to be pushed into Angular 12?
Using the latest Angular 12 (12.2.16) compiler also has this issue.

**Comment by dgp1130** [comment]
@eemt, this should be fixed in 12.2.16. Can you confirm that all your Angular packages are updated? If you still see the error, can you post `ng version`?

**Comment by eemt** [comment]
@dgp1130 I had updated @angular/compiler, @angular/cli & @angular/compiler-cli to 12.2.16, but I hadn't updated core and common (12.2.15).  Now that I updated core and common to 12.2.16, the error is indeed gone.

Thanks!

**Comment by alessiostalla** [comment]
I'm using Angular 13.2.6 and still have the problem in our CI build (not locally, though).

**Comment by chalkplum** [comment]
I still get this error 13.1.4 with range in browserlist 

Angular CLI: 13.1.4
Node: 16.13.0
Package Manager: npm 8.1.4
OS: win32 x64

Angular: 13.1.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            13.1.4
@angular-devkit/schematics      13.1.4
@angular/cdk                    13.2.6
@angular/cli                    13.1.4
@schematics/angular             13.1.4
rxjs                            7.4.0
typescript                      4.5.5

i cant go above as i have peer dependency, nice update there i will have to roll back angular to lower version as was ok there,

**Comment by alessiostalla** [comment]
> I have solved that by doing:
> 
> ```
> ng update @angular/core @angular/cli
> ng update
> ```
> 
> Hope it helps.

Didn't work for me

**Comment by strarsis** [comment]
My approach for this rather unknown starter project:

`grep -R 'last 2 Safari major' .`
````
./node_modules/@angular-devkit/build-angular/src/utils/supported-browsers.js:        'last 2 Safari major versions',
./node_modules/@schematics/angular/library/files/.browserslistrc.template:last 2 Safari major versions
./node_modules/@schematics/angular/application/files/.browserslistrc.template:last 2 Safari major versions
````

`npm ls @angular-devkit/build-angular`
````
[...]
└── @angular-devkit/build-angular@13.1.4
````

`npm ls @schematics/angular`
````
[...]
└─┬ @angular/cli@13.1.4
  └── @schematics/angular@13.1.4
````

`david | grep @angular-devkit/build-angular`
````
│ @angular-devkit/build-angular │ ~13.1.0  │ 13.3.2  │
````
`npm install --legacy-peer-deps --save @angular-devkit/build-angular@13.3.2`

`david | grep @angular/cli`
````
│ @angular/cli                  │ ~13.1.0  │ 13.3.2  │
````
`npm install --legacy-peer-deps --save-dev @angular/cli@13.3.2`

Luckily these updates were enough to also update the browser support configurations in the affected dependencies.

**Comment by chamikasandamal** [comment]
run `npm audit fix --force` or update `@angular-devkit/build-angular`

**Comment by leonardon397** [comment]
> run `npm audit fix --force` or update `@angular-devkit/build-angular`

I tried run this command, but I had unsuccessful.

**Comment by martinmolema** [comment]
> ng update @angular/core @angular/cli

First updated to Angular using `npm install -g @angular/cli` **outside** the project folder.
```
Angular CLI: 13.3.4
Node: 14.17.5
Package Manager: npm 8.3.0
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.4 (cli-only)
@angular-devkit/core         13.3.4 (cli-only)
@angular-devkit/schematics   13.3.4 (cli-only)
@schematics/angular          13.3.4 (cli-only)
```

Then in my project:
Had to remove the node_modules and package-lock.json after updating the version numbers. After that ran `npm install` again and all is working now. 


In my package.json:
```
  "dependencies": {
    "@angular/animations": "~13.3.5",
    "@angular/cdk": "^13.3.4",
    "@angular/common": "~13.3.5",
    "@angular/compiler": "~13.3.5",
    "@angular/core": "~13.3.5",
    "@angular/forms": "~13.3.5",
    "@angular/material": "^13.3.4",
    "@angular/material-moment-adapter": "^13.3.4",
    "@angular/platform-browser": "~13.3.5",
    "@angular/platform-browser-dynamic": "~13.3.5",
    "@angular/router": "~13.3.5",

```


I do **not** have a `.browserslistrc` in my project folder
