### ISSUE TITLE
ng build and ng serve not detecting file changes

### ISSUE THREAD

**Issue by jshthornton** [angular/angular-cli#2356]
Ubuntu 16.04
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: linux x64
watchman: 4.7.0

Run either `ng build --watch` or `ng serve`. Change any file inside of src, no changes detected.

**Comment by samuelcalan** [comment]
Same here. Since update to 1.0.0-beta.15 it doesn't work. It used to work with beta.14.

**Comment by jshthornton** [comment]
Didn't work for me in beta 14 either.
Didn't work using node events nor watchman.

**Comment by udr013** [comment]
I noticed when i make a new project in a folder containing white spaces in the name/path some files are missing in node-modules (970 folders)and auto update doesn't work. When creating a project in a folder without white spaces everything works fine, node-modules(978 folders). (This is on Linux mint).

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli/issues/1610#issuecomment-251995850

**Comment by anbublacky** [comment]
I'm using agular cli to create and serve a project, after editing a file it doesnot auto update the server, i have to restart the ng serve again.

I tried ng serve and ng build --watch , both not working

Output of ng -v

angular-cli: 1.0.0-beta.18
node: 6.2.2
os: linux x64

**Comment by hamayunaziz** [comment]
just remove spaces and special characters from all root directories of project directory(inclusive).

**Comment by mabdeen84** [comment]
I'm using agular cli to create and serve a project, after editing a file it doesnot auto update the server, i have to restart the ng serve again.

I tried ng serve and ng build --watch , both not working

re install npm install , also i checked the folder names but still not working

**Comment by schmorrison** [comment]
No problems here with ng build --watch

```
~$: ng version --verbose
angular-cli: 1.0.0-beta.25.5
http_parser: 2.7.0
node: 7.4.0
v8: 5.4.500.45
uv: 1.10.1
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2j
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: linux x64
```

**Comment by hectorMurillo** [comment]
For those who use windows:

It is a bug in the latest CLI. 
Execute the following command in your project folder:
"npm install --save @ngtools/webpack@1.2.4"
and  npm start or ng serve.

And it should work fine

**Comment by ulymor** [comment]
I faced with the same problem on **Ubuntu 16.04** and angular CLI **1.0.0-beta.30**

The problem was related with Inotify Watches Limit on Linux.
To solve to issue I increased  the watches limit to 512K
```
sudo sysctl fs.inotify.max_user_watches=524288
sudo sysctl -p --system
```
After that I restarted my IDE (WebStorm in my case) and after that the change detection started to work.

**Comment by bhawin-bigstep** [comment]
@hamayunaziz  , Is it because i have a .git folder in my root directory

"just remove spaces and special characters from all root directories of project directory(inclusive)."

**Comment by RPGillespie6** [comment]
@ulymor Thank you, your comment helped me find the root issue. Apparently Sublime 3 has a [known bug](https://github.com/SublimeTextIssues/Core/issues/1195) that uses up all of the inotify watches. Once I closed Sublime, suddenly `ng serve` started working properly again.

**Comment by janmohammadi** [comment]
@hectorMurillo 
After executing "npm install --save @ngtools/webpack@1.2.4" i got this Error:

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined

**Comment by LaOwlLol** [comment]
Anyone finding this on Google:

I encountered this issue on Ubuntu 16.04 with Angular/cli 1.0.3 while using Sublime Text 3. 

From reading @RPGillespie6 comment, I close all my instances of Sublime Text, ctrl + c on running ng serve.  Restart ng serve and reopen Sublime Text.  I modify a file and save and everything works fine.  

Before closing out Sublime Text I had tried restarting ng serve multiple attempts did not fix the problem.

**Comment by kasireddie** [comment]
when i am using ng -v:
i am getting this:
Mg++ version:
	Mg++ 1.5beta1 (formerly MicroGnuEmacs Adv.)
and ng serve;
-----Mg: serve                            (fundamental)----All------------------
 


  what i need to do to work ng serve  ?

**Comment by CerebroVasconcelos** [comment]
Thank you @ulymor for https://github.com/angular/angular-cli/issues/2356#issuecomment-278298550

**Comment by blackgeeknerd** [comment]
@kasireddie  use nvm ..google on it

**Comment by alexcyber** [comment]
@ulymor i have tried lot of ways to resolve it but your comments helped.... Thanks a lot.

**Comment by piyarulps** [comment]
hello guys,
this the problem was related with Inotify Watches Limit on Linux.
this command run and issue is solved,
===
cho 65536 | sudo tee -a /proc/sys/fs/inotify/max_user_watches

and run ng serve or ng build .
====
And it should work fine

**Comment by RPGillespie6** [comment]
The problem is that other programs are competing for inotifies as well (VSCode, etc.) and angular-cli doesn't tell you that you are out, it just silently fails. Sometimes the solution is that you need to close another program that is using up inotifies...

**Comment by owlstack** [comment]
I'm having this issue not on Linux but Windows 10 machine and VS Code.

**Comment by l-tree** [comment]
Reporting that this is still an issue with @angular/cli: 1.7.4 on Windows 10.
In my case I need to close Visual Studio Code for the changes to get picked up in the build.

Angular CLI: 1.7.4
Node: 8.9.4
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

**Comment by j-frost** [comment]
Increasing inotify watches and restarting `ng serve` did not help me.

**Comment by pgfepale** [comment]
> `sudo ng serve` works!

Works me to..

**Comment by HongshanLi** [comment]
same issue here with angular 6. I resolved it using 
ng serve --watch

**Comment by hhsissi** [comment]
> when i am using ng -v:
> i am getting this:
> Mg++ version:
> Mg++ 1.5beta1 (formerly MicroGnuEmacs Adv.)
> and ng serve;
> -----Mg: serve (fundamental)----All------------------
> 
> what i need to do to work ng serve ?

Hi,
Did you manage to solve that behaviour ?

**Comment by Anyoks** [comment]
I had the same issue working on Vagrant vm on Ubuntu 16.04 LTS. 
```
Angular CLI: 6.0.8
Node: 11.10.0
OS: linux x64
Angular: 6.1.7
```
I tried all solutions, increasing `notify watches`, using `--watch` reinstalling npm and node. Nothing worked.
This is what solved it for me. adding `--poll=2000` like so:

`ng serve --poll=2000 --host 0.0.0.0`

**Comment by hwh7** [comment]
Ubuntu 18.04 with Angular CLI(7.3.7).

"echo 65536 | sudo tee -a /proc/sys/fs/inotify/max_user_watches" works for me as @piyarulps suggested.

**Comment by lflores** [comment]
> `sudo ng serve` works!

Works for me, in Linux 18.01, thanks @pgfepale
