### ISSUE TITLE
Ng serve rebuild on change is not working

### ISSUE THREAD

**Issue by Gold3nFox** [angular/angular-cli#27073]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 16

### Description

I recently updated to Angular 17 and everything works fine, The only issue is that when I change files on development mode of ng serve it stucks on ⠋ Changes detected. Rebuilding... sometimes it rebuilds and refreshs my browser for couple of times but it breaks after two or three times and I need to cancel and run ng serve again.
I'm using @angular-devkit/build-angular:dev-server as serve builder and @angular-devkit/build-angular:application for build.
                

  
Tried fresh install angular 17 on my mac with the same angular.json and package.json and same thing happens, Everything works fine but on ng serve I need to cancel and run the command again on file changes because it gets stuck on rebuilding and nothing happens..

### Minimal Reproduction

sudo n 20
npm install -g @angular/cli
ng new test-app
copy angular.json and package.json which i pasted in description to this new app
npm install
ng serve
add a new line to app.component.html

### Exception or Error

```text
Rebuild on file change and apply changes to app
```

### Your Environment

```
ng v:
Angular CLI: 17.1.3
Node: 20.11.0
Package Manager: npm 10.4.0
OS: darwin arm64

Angular: 17.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.3
@angular-devkit/build-angular   17.1.3
@angular-devkit/core            17.1.3
@angular-devkit/schematics      17.1.3
@schematics/angular             17.1.3
rxjs                            7.8.1
typescript                      5.2.2
webpack                         5.90.1
zone.js                         0.14.3`

angular.json:
"serve": {
                    "builder": "@angular-devkit/build-angular:dev-server",
                    "options": {
                      "buildTarget": "karlancer:build"
                    },
                    "configurations": {
                        "production": {
                          "buildTarget": "karlancer:build:production"
                        },
                        "development": {
                          "buildTarget": "karlancer:build:development"
                        }
                    }
                }
                
package.json:
"devDependencies": {
    "@angular-devkit/build-angular": "^17.1.2",
    "@angular/cli": "^17.1.2",
    "@angular/compiler-cli": "^17.1.2",
    "@types/express": "^4.17.17",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0-next.1",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.9",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "npm-run-all": "^4.1.2",
    "protractor": "~7.0.0",
    "purgecss": "^4.0.3",
    "ts-loader": "^4.2.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~5.2.2",
    "webpack-cli": "^5.1.4",
    "webpack-node-externals": "^2.5.0"
  }
```

**Comment by alan-agius4** [comment]
Hi @Gold3nFox, unfortunately I am unable to replicate the problem using the steps provided above.

**Comment by Gold3nFox** [comment]
@alan-agius4 Hello, Thanks my problem is resolved.
Your answer made me check what is the different with the minimal reproduction I mentioned and my project. So I rechecked the files and found out these things where different so I changed them in my main project and it worked!
So I'm providing the changes if it helped others having this problem
These are changed in my package.json
<img width="1108" alt="Screenshot 2024-02-13 at 10 44 28 AM" src="https://github.com/angular/angular-cli/assets/25108979/820bd5ec-8d0d-4429-8f64-43f2423f4778">
This is the change in angular.json
<img width="1148" alt="Screenshot 2024-02-13 at 10 44 50 AM" src="https://github.com/angular/angular-cli/assets/25108979/42b0e049-9a51-4ea7-9ff8-a6ca9df5125f">
Which my old polyfills.ts file had two lines:
`
import '@angular/localize/init';
import 'zone.js';
`

**Comment by Gold3nFox** [comment]
I thought it is fixed but I found out that this problem doesn't happen if I change import lines at the top of my components.
It rebuild and refreshes the browser really fast. Even if i start with changing an import that changing a little bit of ts files it rebuilds but if I take a pause and change a HTML file after that the problem comes back and it stucks on Changes detected. Rebuilding...

on the reproduced version this doesn't happen and the only different with reproduction version and my main version is that it has 450 components and its a super large application.

Could it be related to my project being large and the number of files that it should check is high ?

**Comment by ggombau** [comment]
I have the same problem on a project I updated from a previous version to Angular 17. 

I compared the differences between my project and another created from scratch and tried different solutions but the problem still there. 

After changes on any  HTML, SCSS or .ts files `⠋ Changes detected. Rebuilding...` never finishes. The only solution is to stop and start `ng serve` again.

It's difficult to see a pattern because every time I try a different solution it seems to work but then it happens again.

**Comment by alan-agius4** [comment]
Without a reproduction, it's impossible to discern what is happening. Unfortunately, without one, we won't be able to investigate this issue any further.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Gold3nFox** [comment]
@ggombau Yeah I'm using SSR but I'm using the new builder `@angular-devkit/build-angular:application`.
The problem doesn't exist in new built project, It only exists in my main project which is a huge Angular app with over 4000 pages and with the same settings ( package.json / angular.json / ts.config / .. ) the problem doesn't happen on new repo so I don't know what to do.

**Comment by ggombau** [comment]
@Gold3nFox I'm creating a project in angular 15, I'll add SSR and then updating it to v17 to see if I can reproduce the error. 

I have another project created using esbuild without any problems.

**Comment by Segdo** [comment]
I think I had the same problem few days ago on the latest rc, but without ssr in a medium size project. Not sure what triggered it though because it only happend occasionally.

**Comment by ilijaag** [comment]
Happened to me too, not sure what is the issue. I have huge project the build with `ng serve` is successful, works fine and after a change in any file and save it gets stuck on -> `Changes detected. Rebuilding...` and I need to kill the server and run again. Its with Angular 17 + SSR. On smaller demo projects works fine.

**Comment by ggombau** [comment]
The issue persist in v17.2.1. I can't reproduce it in a new project

**Comment by ggombau** [comment]
I just deleted a message saying the problem persists in Angular v17.2.1 but I was not doing it right. 

It works ok now. I'll test it a bit more tomorrow. 

I was unable to reproduce the problem in a new project

**Comment by saipilli** [comment]
Here is my approach.
`index.html` changes are not detected by cli even if we save and waiting for the changes to see on browser.
In you component `.ts` or `.html` file changes are detected and reloads the page.

I guess workaround until it got fixed to do empty space in the any `.ts` or`.html` in your component file to check your live `index.html` changes.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
