### ISSUE TITLE
Unable to resolve relative path in url in SCSS files after Angular 18 upgrade

### ISSUE THREAD

**Issue by NavneetVaid** [angular/angular-cli#28638]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hi, I am trying to upgrade from angular 17 to angular 18. When i am trying to build i am getting errors of preprocessor where it is not able to resolve some relative paths. ![Image](https://github.com/user-attachments/assets/b4163bbb-582d-4518-bf27-c0b62c465c01)
So if you see it is not able to resolve the path inside url. Has something changed the way we need to import or add some configuration. 

If i try to change the path from **../../images/profile-bg.png** to **/images/profile-bg.png** it works fine. As this scss file is copied from a library present inside node_modules and pasted directly into our app, we cannot modify the path in scss. 

I already have node_modules as a value in my stylePreprocessorOptions in angular.json

### Please provide the exception or error you saw

✘ [ERROR] Could not resolve "../../images/profile-bg.png" [plugin angular-css-resource]

    <stdin>:10120:20:
      10120 │ ...background: url("../../images/profile-bg.png") top left no-r...
            ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.2.8
Node: 22.6.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 18.2.7
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1802.7
@angular-devkit/build-angular      18.2.7
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/build-optimizer    0.1302.1
@angular-devkit/build-webpack      0.1802.7
@angular-devkit/core               18.2.7
@angular-devkit/schematics         18.2.7
@angular/cli                       18.2.8
@schematics/angular                18.2.7
ng-packagr                         18.2.1
rxjs                               7.8.1
typescript                         5.5.4
zone.js                            0.14.3

**Comment by alan-agius4** [comment]
Without a reproduction, it's difficult to determine the cause of the issue. However, if the SCSS file is copied from the library to your application, it's expected that the resource references may break.

Most libraries that offer SCSS and assets typically provide a method to configure the paths. 

For example: 

```scss
$images-path: '@example/styles/assets/images';
@import '@example/styles/scss/main';
```

**Comment by NavneetVaid** [comment]
Hi @alan-agius4 so basically its not third party library but one of the other projects of our org only we use it as a dependency and we are not just copying the scss files we are actually copying there whole folder which holds assets and scss files. So essentially you can assume it is like a folder created with Symbolic link and the same folder is present in node_modules. The thing is it all worked before upgrade and as i gave the example above it breaks when the path is relative and it works when i take out ../../ out of the path. I can understand that it is difficult to help without reproduction but can you help me with what areas i can look into it to understand the config changes. Like the package responsible for scss path resolving and all. We are using @angular-devkit/build-angular:browser as an executor

**Comment by alan-agius4** [comment]
The error suggests you’re not utilizing `@angular-devkit/build-angular:browser`. Instead, you may be using either `@angular-devkit/build-angular:browser-esbuild` or `@angular-devkit/build-angular:application`. 

The plugin responsible for resolving CSS resources can be found here: https://github.com/angular/angular-cli/blob/main/packages/angular/build/src/tools/esbuild/stylesheets/css-resource-plugin.ts#L32

**Comment by NavneetVaid** [comment]
Where i can find this file in node_modules ? and how to know the file which contains them ? What configurations can help in changing the behavior of css resolution ?

**Comment by alan-agius4** [comment]
> Where i can find this file in node_modules ?

`node_modules/@angular/build/src/tools/esbuild/stylesheets/css-resource-plugin.js`

> (Keep in mind that the esbuild pipeline resolution of CSS resources is relative to the file that contains them) Can you please elaborate 

URLs defined in SCSS files are resolved relative to the location of the SCSS file. For example, consider the following project structure:
```
src/
  ├── styles/
  │   ├── main.scss
  │   └── images/
  │       └── logo.png
```
In main.scss, if you write:
```scss
.header {
    background-image: url('./images/logo.png');
}
```

The `logo.png` will resolve to `src/styles/images/logo.png` when compiled.

> What configurations can help in changing the behavior of css resolution ?

There are no configurations available to alter this behavior. However, you can prefix the URL with a `/`, which will instruct the build system to treat the file as an asset that should be copied using the `assets` option, instead of being copied and fingerprinted by the build system.

**Comment by NavneetVaid** [comment]
I dont have anything like the path you mentioned in my node_modules 

![Image](https://github.com/user-attachments/assets/1d428795-99f8-4a88-81a7-7ee680bbcd9e)

If the way it resolves then it should be able to 

![Image](https://github.com/user-attachments/assets/449e0843-5474-47e3-954e-b766310642d4)

This is the structure and ![Image](https://github.com/user-attachments/assets/84c1607d-c1b8-4988-81c5-d532a1deee14)

This is how the scss file refers the url. So ideally it should convert to src/resources/fonts and this is present

**Comment by alan-agius4** [comment]
You can use `npm ls @angular/build` to find the package.

**Comment by NavneetVaid** [comment]
I think you missed my second question 

So my structure is 

src -> resources -> core-saas-theme -> fonts.scss
src -> resources -> fonts -> font files (which is being referenced) 

  1.)   url('../fonts/roboto-v20-latin-ext_latin-regular.woff2') ----> this doesn't work ( compile time issue ) 
  2.) url('/fonts/roboto-v20-latin-ext_latin-regular.woff2') ----> this work ( compile time ) 

If the way the scss is resolved ideally the 1.) one have resolved src/resources/fonts/... and should have worked.

**Comment by alan-agius4** [comment]
The first one should work, but again without an exact minimal reproduction it's hard to tell what it happening. 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by NavneetVaid** [comment]
Okay i will try if i can replicate, one question more. This is Nx monorepo, and the folder core-saas-theme is a symbolic-link folder.

**Comment by NavneetVaid** [comment]
Hi @alan-agius4 , I just the saw that this issues exist since long and few people got it for previous versions. I was wondering there might be something which is solely responsible for this and i saw that there is some resolve-url-loader available for this but as we are using angular-devkit can you help us know if we can pass this resolve-url-loader somewhere ? Configure our builder ? We are using NX mono repo

**Comment by alan-agius4** [comment]
Based on the stack trace, it appears the issue is occurring during a library build.

`resolve-url-loader` can't be added in my-packagr.

This appears to be the same root cause of https://github.com/ng-packagr/ng-packagr/issues/2918

**Comment by NavneetVaid** [comment]
So what is the solution to this ? In the tagged issue i dont see the solution. I agree it is the same issue.

**Comment by alan-agius4** [comment]
There is no workaround yet.

**Comment by NavneetVaid** [comment]
> There is no workaround yet.

Are we planning to fix this in next update ? What is the ETA ? This is blocking our upgrade
