### ISSUE TITLE
Stylesheet assets arent loaded from the same source as specified in the --deploy-url

### ISSUE THREAD

**Issue by stnor** [angular/angular-cli#28657]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I'm trying to migrate to esbuild from webpack + custom-webpack on 18.2.

I want to serve index.html from and make http requests to https:/mydomain/ but I want to load scripts/images/styles from //cdn.local/ which all work fine. But for some reason the url-assets in the stylesheets arent loaded from mycdn...

With webpack all style resources was loaded from the same host as the base stylesheet and scripts.. With esbuild this seems broken?

### Please provide a link to a minimal reproduction of the bug

https://github.com/stnor/cdn-app

### Please provide the exception or error you saw

When using `ng build --deploy-url=//cdn.local:4300/`

Expected behaviour:
`background-image: url(/some/url)` should load relative to the deploy url.

Actual:
Using base-href?

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.2.9
Node: 20.11.1
Package Manager: yarn 1.22.22
OS: darwin arm64

Angular: 18.2.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.9
@angular-devkit/build-angular   18.2.9
@angular-devkit/core            18.2.9
@angular-devkit/schematics      18.2.9
@angular/cli                    18.2.9
@schematics/angular             18.2.9
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by stnor** [comment]
Instructions are in the README.md in the minimal-reproduction-repo

**Comment by alan-agius4** [comment]
This is working as intended: only CSS resources with relative paths are managed by the build system. Meaning they are fingerprinted, automatically copied, and prepended with the deploy URL. All absolute paths remain unchanged.

This is also same behaviour of the webpack based builder.

**Comment by alan-agius4** [comment]
> Are you saying a resource in a stylesheet shouldn't be loaded relative to the document location of the stylesheet? In my experience that's not how the web works :) Also the "path" of a resource in the style sheet is a relative url and not an (absolute) path.

`./` is considered relative to the stylesheet, whereas `/` is treated as an absolute path from the document root. Therefore, `background-image: url(/some/url)` correctly loads from the document root, as it’s specified as an absolute path. 

Would you like any further refinements to this version?

 > Do you have any recommendations to solve my specific use case?

You can use relative paths and let the build system handle the css resources for you. (IE: instead of placing them in the `public` folder, move next to the `.scss` file or another diretory that is copied via the "assets" options. These files will than be emitted in the "media" directory.

**Comment by clydin** [comment]
Component stylesheets are emitted into the JavaScript for a given component and then at runtime Angular inlines the stylesheets as `<style>` elements. Inline styles resolve URLs based on the document location. This differs from external CSS files where URLs are resolved from the location of the CSS file.

Using a relative path and allowing the build system to manage the files also has caching advantages: https://web.dev/articles/http-cache#versioned-urls

**Comment by stnor** [comment]
> `./` is considered relative to the stylesheet, whereas `/` is treated as an absolute path from the document root. Therefore, `background-image: url(/some/url)` correctly loads from the document root, as it’s specified as an absolute path.
> 

Thanks for the suggestions. I'll see what I can do.

However, I still do not quite understand why `/` is treated as an absolute path from the document root.
Shouldn't it be relative to `deployUrl` regardless let say if the `deployUrl` is `//somehost//foo`?

**Comment by alan-agius4** [comment]
Absolute URLs, those starting with `/`— as per the URL spec are meant to load from the document root. It seems you're trying to achieve the behavior of relative paths but are currently using absolute paths.

**Comment by stnor** [comment]
I see now what you're saying @alan-agius4. This is an ancient massive project originally developed in backbonejs then incrementally migrated to angularjs then migrated to angular9 so there are som quirks and legacy handling of stuff.

I'll move the resources out from the assets/public folder and place them with the components. As you point of @clydin, that's great for cache busting as well.

My only problem wuld be locally served webfonts then iirc.
