### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'newLine' of undefined

### ISSUE THREAD

**Issue by hozefam** [angular/angular-cli#3781]
ERROR in multi main
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localho
st:4200/' in 'D:\Hozefa\Ang\FirstApp\TestApp'
 @ multi main

Anyone?

### OS?
Windows 7

### Versions.
angular-cli: 1.0.0-beta.24
node: 4.4.6
os: win32 x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

### The log given by the failure.
ERROR in multi main
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localho
st:4200/' in 'D:\Hozefa\Ang\FirstApp\TestApp'
 @ multi main

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (D:\Hozefa\Ang\FirstApp\TestApp\node_modules\t
ypescript\lib\typescript.js:8062:20)
    at Object.createCompilerHost (D:\Hozefa\Ang\FirstApp\TestApp\node_modules\ty
pescript\lib\typescript.js:44978:26)
    at Object.ngcLoader (D:\Hozefa\Ang\FirstApp\TestApp\node_modules\@ngtools\we
bpack\src\loader.js:171:31)
 @ multi main

**Comment by filipesilva** [comment]
Can you provide repro steps please?

**Comment by bstaley** [comment]
I've solved it on my side by adding the required AotPlugin item to my plugins

``` 
import {AotPlugin} from '@ngtools/webpack'

exports = { /* ... */
  plugins: [
    new AotPlugin({
      tsConfigPath: 'path/to/tsconfig.json',
      entryModule: 'path/to/app.module#AppModule'
    })
  ]
}
```

check out the usage for more information on the options
https://github.com/angular/angular-cli/tree/master/packages/%40ngtools/webpack

**Comment by donvadicastro** [comment]
Where webpack configuration is placed inside bootstrapped project?

**Comment by toverux** [comment]
I've located the source of that error at, https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/loader.ts#L186

The instanceof check fails. Therefore, the `else` is executed, and because the loader has no options (it should not enter the `else` because we have the plugin), and the undefined options propagates to TypeScript, and boom.

The instanceof fails because it seems that the export (of plugin.ts) is executed two times in the compiled JavaScript vendor source, leading to similar AotPlugin ctors, but not strictly equal.

**Comment by phamlehoaian** [comment]
Hello!
I faced same error! So anyone can guide me how to fix it? I have read above comments but I don't know how and where to change. Thank you!

**Comment by toverux** [comment]
@phamlehoaian In most cases, this is simply because you forgot to add the AotPlugin.

**Comment by phamlehoaian** [comment]
@toverux Can you please tell me how to add AotPlugin? I did not forget! I have no experience about this! Please help me! Thank you.

**Comment by filipesilva** [comment]
This doesn't seem to be a problem with the `AoTPlugin` because that would mean you're trying to use it separately.

As far as I can tell, @hozefam and @phamlehoaian were having problems with `angular-cli` usage itself.

My bet is that this is dependency problem. Are you *absolutely sure* you followed https://github.com/angular/angular-cli#updating-angular-cli when upgrading?

I'm testing a new project right now and don't get this. But I know this can happen with outdated dependencies, and that happens if you don't follow the upgrade guide.

**Comment by phamlehoaian** [comment]
@filipesilva I faced this problem in fresh new installed nodejs and angular-cli. So I think that it is not related with upgrading. BTW, in project folder, I noticed that the file webpack.config.js is not existed. Is it right?

**Comment by filipesilva** [comment]
@phamlehoaian yes that is right, you shouldn't have `webpack.config.js` in your project.

Can you tell me **exactly** what you did so I can reproduce the error? The exact commands please, and if you changed any files in the project.

**Comment by phamlehoaian** [comment]
@filipesilva Okay, I will remove all nodejs as this guide [http://stackoverflow.com/questions/38602808/uninstall-node-js-windows-10](http://stackoverflow.com/questions/38602808/uninstall-node-js-windows-10), then I will install new, keep all commands and send to you. Please wait.

**Comment by filipesilva** [comment]
@phamlehoaian no need to do all that, these steps are enough: https://github.com/angular/angular-cli#updating-angular-cli

**Comment by phamlehoaian** [comment]
@filipesilva It's so strange! After I uninstall all things and start new install to this command `npm install -g angular-cli`, then the new created project is working perfect!

**Comment by filipesilva** [comment]
@phamlehoaian sometimes these things happen and there are dependency problems. I'm glad it's working correctly for you now :D

**Comment by deepakkadarivel** [comment]
Had to update my npm and angular cli. After that is done. Delete your project folder, clone it back again. Run npm install. And things should work.

**Comment by bkottapally** [comment]
@deepakkadarivel new clone idea worked for now

**Comment by hnrchrdl** [comment]
`rm -rf node_modules/` in your project to get rid of all npm stuff and then `npm cache clean` followed by `npm install` should also resolve this issue. Also, make sure the versions of the cli locally and globally match. In my case this issue appeared as of an old version of `angular-cli` which still got installed extraneous through my shrinkwrap while I was using the new `@angular/cli` packages.

**Comment by elfleat** [comment]
Thanks @hnrchrdl, that worked for me.

**Comment by mmathys** [comment]
thanks @hnrchrdl

**Comment by ndkcha** [comment]
go through this, this might help.

https://github.com/angular/angular-cli#updating-angular-cli

**Comment by mmathys** [comment]
shorthand of @hnrchrdl's solution:

```
rm -rf node_modules && npm cache clean && npm uninstall --save angular-cli && npm uninstall -g angular-cli && npm i --save @angular/cli && npm i -g @angular/cli && npm i && npm start
```

**Comment by hnrchrdl** [comment]
@mmathys your command got truncated

**Comment by tomjon** [comment]
@mmathys I needed 'sudo' for the -g installs/uninstallls, otherwise, just what I needed :)

**Comment by manuelreina** [comment]
In my case, this error was because I updated to beta.32 and I didn't noticed that the node_modules folder was not completely removed.
After removing the folder manually, I got it working.

**Comment by jiangyaqi2** [comment]
it need delete node_module
,uninstall -g angular-cli and and angular/cli
and  install @angular/cli

**Comment by QuantumInformation** [comment]
why do we need the cli locally and globally?

**Comment by mmathys** [comment]
Because for example when you're building the project, you want to use `ng build` (not `./node_modules/@angular/cli/bin/ng build`).

**Comment by egervari** [comment]
I am getting the same error, but on circle/ci. Everything works fine locally on my mac.

```
ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/home/ubuntu/angular2-ngrx-example/node_modules/typescript/lib/typescript.js:9426:20)
    at Object.createCompilerHost (/home/ubuntu/angular2-ngrx-example/node_modules/typescript/lib/typescript.js:62475:26)
    at Object.ngcLoader (/home/ubuntu/angular2-ngrx-example/node_modules/@ngtools/webpack/src/loader.js:329:31)
 @ multi ./src/main.ts

ERROR in ./src/polyfills.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/home/ubuntu/angular2-ngrx-example/node_modules/typescript/lib/typescript.js:9426:20)
    at Object.createCompilerHost (/home/ubuntu/angular2-ngrx-example/node_modules/typescript/lib/typescript.js:62475:26)
    at Object.ngcLoader (/home/ubuntu/angular2-ngrx-example/node_modules/@ngtools/webpack/src/loader.js:329:31)
 @ multi ./src/polyfills.ts

ERROR in ./src/test.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/home/ubuntu/angular2-ngrx-example/node_modules/typescript/lib/typescript.js:9426:20)
    at Object.createCompilerHost (/home/ubuntu/angular2-ngrx-example/node_modules/typescript/lib/typescript.js:62475:26)
    at Object.ngcLoader (/home/ubuntu/angular2-ngrx-example/node_modules/@ngtools/webpack/src/loader.js:329:31)
28 02 2017 12:47:04.259:ERROR [karma]: { Error: no such file or directory
    at MemoryFileSystem.readFileSync (/home/ubuntu/angular2-ngrx-example/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at MemoryFileSystem.(anonymous function) [as readFile] (/home/ubuntu/angular2-ngrx-example/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:300:34)
    at doRead (/home/ubuntu/angular2-ngrx-example/node_modules/@angular/cli/node_modules/karma-webpack/lib/karma-webpack.js:205:29)
    at Plugin.readFile (/home/ubuntu/angular2-ngrx-example/node_modules/@angular/cli/node_modules/karma-webpack/lib/karma-webpack.js:210:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/_karma_webpack_/src/polyfills.ts' }
28 02 2017 12:47:04.269:ERROR [karma]: { Error: no such file or directory
    at MemoryFileSystem.readFileSync (/home/ubuntu/angular2-ngrx-example/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at MemoryFileSystem.(anonymous function) [as readFile] (/home/ubuntu/angular2-ngrx-example/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:300:34)
    at doRead (/home/ubuntu/angular2-ngrx-example/node_modules/@angular/cli/node_modules/karma-webpack/lib/karma-webpack.js:205:29)
    at Plugin.readFile (/home/ubuntu/angular2-ngrx-example/node_modules/@angular/cli/node_modules/karma-webpack/lib/karma-webpack.js:210:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/_karma_webpack_/src/test.ts' }
npm ERR! Test failed.  See above for more details.
```

**Comment by phil294** [comment]
you might want to check angular-cli.json and package.json for outdated local angular-cli versions. at least I am getting a different error now..

**Comment by jlouros** [comment]
I'm seeing exactly the same error as @egervari reported. I'm writing my code on a Windows 8.1, build, test, e2e and lint works perfectly. Once I push my code to CI (using a Linux build agent) it fails with the following errors:
```
ERROR in AppModule is not an NgModule[39m[22m

[1m[31mERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/var/lib/jenkins/workspace/Intelliflo/Microservice.DeveloperHub/IP-14137/node_modules/typescript/lib/typescript.js:9514:20)
    at Object.createCompilerHost (/var/lib/jenkins/workspace/Intelliflo/Microservice.DeveloperHub/IP-14137/node_modules/typescript/lib/typescript.js:63770:26)
    at Object.ngcLoader (/var/lib/jenkins/workspace/Intelliflo/Microservice.DeveloperHub/IP-14137/node_modules/@ngtools/webpack/src/loader.js:329:31)
 @ multi ./src/main.ts[39m[22m

[1m[31mERROR in ./src/polyfills.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/var/lib/jenkins/workspace/Intelliflo/Microservice.DeveloperHub/IP-14137/node_modules/typescript/lib/typescript.js:9514:20)
    at Object.createCompilerHost (/var/lib/jenkins/workspace/Intelliflo/Microservice.DeveloperHub/IP-14137/node_modules/typescript/lib/typescript.js:63770:26)
    at Object.ngcLoader (/var/lib/jenkins/workspace/Intelliflo/Microservice.DeveloperHub/IP-14137/node_modules/@ngtools/webpack/src/loader.js:329:31)
```

## OS?

Windows 8.1

## Versions.

angular-cli: 1.0.0-rc.1
node: 6.10.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/compiler-cli: 2.4.9
typescript: 2.2.1

**Comment by filipesilva** [comment]
This specific error (`TypeError: Cannot read property 'newLine' of undefined`) seems to appear due to different versions of either TypeScript. If you're experiencing different behaviour on different machines, make sure you're using the same TS version everywhere.

You can test this by running `npm ls typescript` on your project. It's likely you have a bad mix of TS versions.

Angular version 2 works only with Typescript 2.0, while Angular version 4 works with 2.1 and up.

**Comment by jlouros** [comment]
@filipesilva thanks for your response. I was actually able to figure out the problem. As you stated on previous comments, this error is reported when an older version of Angular-CLI is installed. For me it was always picking angular-cli@1.0.0-beta.26 instead of rc.1. I was able to figure that out when I ran ```npm ls``` on build agent workspace. This was happening even when I followed the uninstall guide.

To fix this problem for me I had to:
- after ```npm install``` run ```npm ls``` just to double check the installed angular-cli
- ask a member from DevOps (or somebody with 'sudo' access on the build agent) to wipe-out the entire workspace and run ```npm cache clear```

Hopefully this can you @egervari

**Comment by chebum** [comment]
For me the problem was solved by local installation of angular-cli. So I have to have two versions on my computer: one installed globally with -g tag and another one installed locally.

**Comment by MartinFreire** [comment]
Hi
I'm having the same issue. My SO is W10, and I created the project two weeks ago.
I was working fine until today, I copied my code to make a new repo and cleand the "node_modules" folder, run **npm install** and doesn't work since then. 
My main problem is that I also clean the original folder so I had to run **npm install** on both projects
I've tried every solution I could find and of course the angular-cli update guide. Nothing works. 
I get this message and can't run any of my two projects.
This is my **ng version**:
```
@angular/cli: 1.0.0-rc.2
node: 6.10.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9
@ngtools/webpack: 1.2.13
```

**Comment by gamalielhere** [comment]
@egervari I'm not sure why but I rebuilt the built without cache and it passed on circleci. Hope it helps.

**Comment by MartinFreire** [comment]
Ok, so I could make it work. 
I tried multiple times the steps in the update guide and didn't work form me. 

This is the last set of steps I do and it works in my case:
1) Unistall NodeJS (yes I did that)
2) Delete all the folders in **C:\Users\{user}\AppData\Local\Temp** that stars with npm
3) Delete the folder **C:\Users\{user}\AppData\Roaming\npm**
4) Delete the folder **C:\Users\{user}\AppData\Roaming\npm-cache**
6) Delete the folder **node_module** in both projects
5) Restart my PC (because I detected that W10 has some folders lock and that didn't let me run **nmp cache clean**
7) Install NodsJs
8) Run **npm install --save-dev @angular/cli@latest**
9) Run **npm install**
10) Run **npm install --save-dev @angular/cli@latest** AGAIN

I only repeated the **npm install --save-dev @angular/cli@latest** after the **npm install** once, so I don't know if had anything to do with the problem. After the second time I run this command I see that the library has changed (it was on yellow) **`-- @angular/cli@1.0.0-rc.2** (I guess this is wath I was doing wrong)

Hope it works for someone else!

**Comment by jbeckton** [comment]
I had the same issue, after reading this entire thread and trying everything the problem still existed. Turns out that the cli was using a different version of webpack than what my project is using. Once I got those version in sync then the error went away. I have a new Angular 4 project Universal demo so the webpack outside the cli was for server side code i guess.

**Comment by dancancro** [comment]
@egervari Have you had any luck with this? I think I'm in the same boat. Locally, [my angular 2.4.5, cli 1.0.0-rc1 app](https://github.com/dancancro/great-big-angular2-example) runs fine with either Typescript 2.0.0 and 2.2.1, but neither work on TravisCI.

**Comment by thisisbb** [comment]
FYI. Had this issue too, cli migration guides etc did not help .
Solved the problem removing "@ngtools/webpack" and "webpack" from my package.json dependencies.
Hope it can save couple of hour of your time :)

**Comment by doubletriplezero** [comment]
Ran into this issue today. In our case it resulted from a mismatch of peer dependencies because we had almost all @angular packages at 4.0.0, @angular/cli at 1.0.0, but **@angular/compiler-cli** at ^4.0.0 which resulted in 4.0.2 being installed for that package. ng build failed with "Cannot read property 'newLine' of undefined" error.

**Comment by playground** [comment]
Have similar issue with tests on Travis-CI...with @angular/cli 1.0.0 & @angular 4.0.0

locally the tests ran fine.

Travis-CI
Uncaught TypeError: Cannot read property 'apply' of undefined


![image](https://cloud.githubusercontent.com/assets/243495/25032727/9e3cd81c-20a4-11e7-896e-78f83d0380a0.png)

**Comment by wcainboundary** [comment]
We avoid using global commands (we only use local `ng`) for this and other reasons, as we believe build determinism is important, as is consistency between development and production build environments. I did encounter the error `TypeError: Cannot read property 'newLine' of undefined` today in one of my recently revived development environments, apparently due to old dependencies, as suggested above. Removing `node_modules` in the project and rerunning `npm install`, as recommended above, resolved the problem. The current dependencies of the project include:
```
    "@angular/cli": "1.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/platform-server": "4.0.0",
    "@angular/router": "4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "~5.0.3",
    "typescript": "^2.1.4",
    "zone.js": "^0.8.4"
```

But it had been updated and rebuilt from older versions of `angular` (2.x) and `angular-cli` (1.x beta).

**Comment by nathanBrenner** [comment]
I had the same `Module build failed: TypeError: Cannot read property 'newLine' of undefined` on a cloned copy of the app.

I have  been working on a local version that had Angular 4.0.2, and when another developer pulled the latest version, they started getting that error.  I made another cloned copy and was getting that error.  I tried a bunch of the suggestions above.

Turned out all of the angular dependancies were on 4.1.0 but the `@angular/cli` was on 1.0.0.  In my package.json, I had angular dependacies as `^4.0.0`, and `@angular/cli` at 1.0.0.  I changed `"@angular/cli": "^1.0.1", ran `npm install` and the app is back to compiling as expected.

**Comment by Elastep** [comment]
I have a project with exact same error, using @angular 4.1.3 and @angular/cli 1.1.0-rc.0 (tried 1.04 as well with the same result). So the project builds fine with 
` ng build  --prod --aot=false `
but fails with this error using ng build --prod. 

I did some debugging of \node_modules\@ngtools\webpack\src\loader.js

And it turns out it breaks on these lines:

```
function ngcLoader() { 
...
const sourceFileName = this.resourcePath; //here is index.ts file, I'll show it later
const plugin = this._compilation._ngToolsWebpackPluginInstance; //plugin === undefined here!
if (plugin && plugin instanceof plugin_1.AotPlugin) { //and of course this is false
...
} else {
const options = loaderUtils.getOptions(this) || {}; //and options are {} here...
...
const compilerHost = ts.createCompilerHost(compilerOptions); //and of cource it breaks here
...
}
}
```

And the file on which it fails is index.ts:
`export * from './GJLog.component';`

I've also checked all the versions of all packages, cleaned cache, reinstalled node.. Everything.. But still the same problem in AOT mode. In the same time, it perfectly compiles with aot=false...

Any hints on what to debug next, which direction to investigate?

Thank you!

**Comment by Elastep** [comment]
Even more, the project builds just fine like this:
`npm run ng build -- --aot=true --environment=prod --output-hashing=all --sourcemaps=false --extract-css=true`

But does not build like this:
`npm run build -- --prod --aot=true`

Let's read the docs:

> --prod also sets the following non-flaggable settings:
>+ Adds service worker if configured in .angular-cli.json.
>+ Replaces process.env.NODE_ENV in modules with the production value (this is needed for some libraries, like react).
>+Runs UglifyJS on the code

I don't have any service workers, I don't use any process.env.NODE_ENV.

So this must be related to UglifyJS? 

Can I somehow disable running uglify js just to make sure it's the reason?

**Comment by j-nord** [comment]
We have the same issue. With every new loader in webpack you get a new bug. Nothing is really tested :-(

**Comment by Elastep** [comment]
I've just opened a separate issue for this... So probably it'll attract more attention...

**Comment by NayabHussain** [comment]
Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter while doing ng serve , previously it was working from today it is giving problem

**Comment by Elastep** [comment]
Please also leave a note about your issue here:
https://github.com/angular/angular-cli/issues/6426

**Comment by Elastep** [comment]
There's some undocumented or badly documented things that --aot --prod does with your code. For example, cssnano is also run,  
Please take a look https://github.com/angular/angular-cli/issues/6426 here for my solution.

Probably you made the same mistake as I did...

**Comment by lasath** [comment]
Oh this is a painful bug.Uninstall reinstall more than 100 times but still not resolved

Module build failed: TypeError: Cannot read property 'newLine' of undefined.

Some one please help! :(

**Comment by Elastep** [comment]
That's probably a bug in syntax like the one I had... 
In my case it had nothing to do with dependencies...
Does it build in debug mode?

**Comment by brainbolt** [comment]
I just encountered this error today after adding a component via angular cli to a working app, and then discarding the changes via github for desktop before committing. Git shows no changes between the working app and the broken app. Could this be related to changes cli made to an ignored file? Here is my .gitignore for the project.

```
# See http://help.github.com/ignore-files/ for more about ignoring files.

# compiled output
/dist
/tmp
/out-tsc

# dependencies
/node_modules

# IDEs and editors
/.idea
.project
.classpath
.c9/
*.launch
.settings/
*.sublime-workspace

# IDE - VSCode
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json

# misc
/.sass-cache
/connect.lock
/coverage/*
/libpeerconnection.log
npm-debug.log
testem.log
/typings

# e2e
/e2e/*.js
/e2e/*.map

#System Files
.DS_Store
Thumbs.db
src/environments/environment.ts
src/environments/environment.prod.ts
```

**Comment by mejmo** [comment]
Same here, it worked. I am still using 1.0.0 version, week ago everything fine, currently I got the `newLine` error.

**Comment by mrtrash** [comment]
someone solve this error?
I have still trying to solve the next errors when I run `ng serve`

```
ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localhost:4200' in '/Users/codebo1/Projects/monitor-client/client'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/main.ts
Module build failed: Error: Cannot find module 'webpack/lib/dependencies/ContextElementDependency'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/codebo1/Projects/monitor-client/client/node_modules/@ngtools/webpack/src/plugin.js:9:34)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/codebo1/Projects/monitor-client/client/node_modules/@ngtools/webpack/src/index.js:30:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/polyfills.ts
Module build failed: Error: Cannot find module 'webpack/lib/dependencies/ContextElementDependency'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/codebo1/Projects/monitor-client/client/node_modules/@ngtools/webpack/src/plugin.js:9:34)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/codebo1/Projects/monitor-client/client/node_modules/@ngtools/webpack/src/index.js:30:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
 @ multi ./src/polyfills.ts
webpack: Failed to compile.
```

**Comment by JosepAlacid** [comment]
Same here. 
Recovered from backup that was really working fine: error.
All combinations of cache clean, uninstall, update: error!

**Comment by jongunter** [comment]
I've spent 16 hours working on this problem with a angular-cli project. I've tried every solution listed here, with nothing that gets it working. I wish I could provide a repro, but doesn't seem to happen with any other CLI project on my machine.

I feel pretty frustrated because I thought the Angular team had ironed out most of the issues with the CLI. But after this, I'm still not convinced it's a stable platform yet. The project in question had been left alone for 3 months, then cloning it onto my computer and reinstalling the npm dependencies causes the "newline" error message when I try to `ng serve` it.

**Comment by Elastep** [comment]
Did you check my solution?

**Comment by jongunter** [comment]
Yeah, I `grep`ed my entire project for `url("")` and nothing came back, if that's what you mean.

I'm guessing it could be some other CSS-related syntax issue then? Unfortunately, I have over 100 components. Trying to debug which CSS file is causing the problem is going to take a while.

**Comment by Delysid** [comment]
I've spent a lot of time on this problem. But it solved just by update angular-cli from v1.1.0 to v1.1.1

**Comment by mejmo** [comment]
Guys you have to completely delete npm packages, in Windows it is in your
user profile. This problem caused the npm update on my machine. When I
cleaned all the packages previously downloaded in global, it works like a
charm.

**Comment by jongunter** [comment]
Thanks for your responses. I tried the following on my Mac and PC with no solution:

- Uninstalling node/npm and reinstalling 
- Removing all my global packages and reinstalling them
- Removing all my local npm packages and reinstalling
- Updating the CLI to v1.1.1
- Followed the entire CLI migration guide
- Deleted and re-cloned the project from source control
- Updated node to the latest version (8.1.0)

Furthermore, this project in question seems to be working on one of my colleague's Macs, which is strange because it doesn't work on my Mac, which is the exact same model with the exact same MacOS version. I `npm shrinkwrap`ed the dependencies there and tried to remove all local/global `node modules` and reinstall on other machines. Still doesn't work. 

We spent months putting this project together for a demo. I think I might be at my wits end with Angular right now. The fact that there's no useful error message or stack trace here is particularly infuriating for me.

**Comment by jongunter** [comment]
This seems to be a dependency issue, as copying the same `package.json` file into one of my blank "sandbox" cli projects yields the same error. 

Check out my repro...this is broken on my machine, and I hope other people can reproduce this:
https://github.com/jongunter/broken-ng-cli

**Comment by andreaslancom** [comment]
I have the same issue:

ng -v

@angular/cli: 1.0.3
node: 8.0.0
os: linux x64
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/core: 4.2.3
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.0.3
@angular/compiler-cli: 4.2.3
@ngtools/webpack: 1.4.1

tsc -v

Version 2.3.4

Errors: ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/var/www/education/client-apps/node_modules/typescript/lib/typescript.js:9514:20)
    at Object.createCompilerHost (/var/www/education/client-apps/node_modules/typescript/lib/typescript.js:63770:26)
    at Object.ngcLoader (/var/www/education/client-apps/node_modules/@ngtools/webpack/src/loader.js:397:33)
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/polyfills.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/var/www/education/client-apps/node_modules/typescript/lib/typescript.js:9514:20)
    at Object.createCompilerHost (/var/www/education/client-apps/node_modules/typescript/lib/typescript.js:63770:26)
    at Object.ngcLoader (/var/www/education/client-apps/node_modules/@ngtools/webpack/src/loader.js:397:33)
 @ multi ./src/polyfills.ts

Are there any solutions?

**Comment by jongunter** [comment]
@filipesilva , this issue should be reopened. I have a reproducible test case posted above (if it's not reproducing the error for you, please let me know). Even if this is deemed as case of "operator error", there should be a more helpful error message to let the user know what's going on.

**Comment by shahmhussain** [comment]
I had this bug today because i was i had angular/cli version 1.1.2 installed, i resolved it by installing @angular/cli@1.1.0

**Steps include:**
npm uninstall @angular/cli
npm install @angular/cli@1.1.0

Hope that helps.

**Comment by jongunter** [comment]
If anyone was wondering, I have resolved this issue by `ng new`ing a new project, and merging it with my old non-working project (and trying to keep the dependencies from the new project). Luckily, everything worked, even though it meant a forced upgrade to Angular 4. 

Still, I think this shouldn't be necessary...the error should tell me roughly what I need to fix.

**Comment by andreaslancom** [comment]
Thanks a lot. As @jongunter said I create new app and merge package.js and it's working now.

**Comment by MoxxNull** [comment]
I had the same error. I hat to go through @MartinFreire 's steps and (don't ask me why) delete package.-ock.json .

**Comment by filipesilva** [comment]
I looked into this during the weekend and have to say that @toverux explanation in https://github.com/angular/angular-cli/issues/3781#issuecomment-272284110 is spot on.

For projects using `@angular/cli` (and not `@ngtools/webpack` directly), this error happens if you have multiple versions of `@ngtools/webpack` in your dependencies. You can check if you do by running `npm ls @ngtools/webpack` (or `yarn list @ngtools/webpack`). You should remove any extra copies from your dependencies and make sure that your lock files are updated accordingly.

**Comment by MrToasty97** [comment]
@filipesilva Thank you. `npm prune` saved this for me.

**Comment by jdrake3** [comment]
I believe I've tried all the above.  I may just pave the box and start over.  So sad.

**Comment by jdrake3** [comment]
Still receiving this error, despite having only one version of @ngtools/webpack installed.

`npm ls @ngtools/webpack
+-- @angular/cli@1.0.0
| `-- @ngtools/webpack@1.3.0
`-- @ngtools/webpack@1.3.0`

**Comment by deshak9** [comment]
OS : Windows with Angular 4

"@angular/cli": "1.2.1",
"@angular/material": "2.0.0-beta.6",

I just removed the caret from above two dependencies and performed following steps, everything started working perfectly.
1. Remove node_module
2. Uninstall angular cli from local and global
3. Install the same version of angular cli in both
4. Do "npm install"
5. "ng serve"

**Comment by chikehenderson** [comment]
ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/home/user/Documents/projects/ayo6/node_modules/typescript/lib/typescript.js:9618:20)
    at Object.createCompilerHost (/home/user/Documents/projects/ayo6/node_modules/typescript/lib/typescript.js:66867:26)
    at Object.ngcLoader (/home/user/Documents/projects/ayo6/node_modules/@ngtools/webpack/src/loader.js:202:31)
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/polyfills.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/home/user/Documents/projects/ayo6/node_modules/typescript/lib/typescript.js:9618:20)
    at Object.createCompilerHost (/home/user/Documents/projects/ayo6/node_modules/typescript/lib/typescript.js:66867:26)
    at Object.ngcLoader (/home/user/Documents/projects/ayo6/node_modules/@ngtools/webpack/src/loader.js:202:31)
 @ multi ./src/polyfills.ts
webpack: Failed to compile.

I'm getting this when I run "ng serve"..  Is this just a typescript error or more?

**Comment by macandcheese** [comment]
OK, as many others have mentioned this is due to version mismatches, but never seems to be fixed by deleting the node_modules folder or re-installing / uninstalling packages.

I FINALLY managed to get this working by deleting node_modules folder AND the package-lock.json file... Then running npm install seemed to fix this for me.

**Comment by chikehenderson** [comment]
If I remember correctly my fix to the issue went something like this..

rm -r npm_modules
sudo -i npm clear cache
sudo npm -g uninstall @angular/cli
perhaps "npm uninstall @angular/cli" locally if need be..
then install with npm again, I realised my problem was that somehow.. I
managed to have a local version
that was different that the global version and the older one was being
used..

check versions ng -v, etc..also I used npm3 not npm ;)

**Comment by skiminock** [comment]
Hey, guys, my problem was solved due @macandcheese comment - 
`
I FINALLY managed to get this working by deleting node_modules folder AND the package-lock.json file... Then running npm install seemed to fix this for me.
`
the @filipesilva rightly explained the reason of issue - 

`
I looked into this during the weekend and have to say that @toverux explanation in #3781 (comment) is spot on.

For projects using @angular/cli (and not @ngtools/webpack directly), this error happens if you have multiple versions of @ngtools/webpack in your dependencies. You can check if you do by running npm ls @ngtools/webpack (or yarn list @ngtools/webpack). You should remove any extra copies from your dependencies and make sure that your lock files are updated accordingly.
`
