### ISSUE TITLE
Cannot set property 'stack' of undefined 

### ISSUE THREAD

**Issue by sprider** [angular/angular-cli#3975]
### OS?
> Windows 7

### Versions.
> v6.9.2

### Repro steps.
> Yes, Auth0 implementation

Hi,

I am new to angularjs 2. Any idea about this error? 

![error](https://cloud.githubusercontent.com/assets/21008316/21911824/1c1bc7f2-d8e8-11e6-9488-53b135e7f579.PNG)

**Comment by beeman** [comment]
@sprider can you please give some more information about the version you are using and the repro  steps? For instance which steps you took to implement Auth0?

**Comment by deebloo** [comment]
@sprider so there seems to be a bug in zone.js. Try fixing the version to 0.7.2 and see if the error message is more explicit

**Comment by scttcper** [comment]
@deebloo thanks thats working for me.

**Comment by beeman** [comment]
I can confirm that I have the issue too on 1.0.0-beta.25, freshly installed app with `ng new`.

Downgrading zone.js one minor version seems to fix it: `npm install --save zone.js@0.7.4`

**Comment by sprider** [comment]
npm install --save zone.js@0.7.4 fixed the problem for me

**Comment by goto1** [comment]
I can also confirm that `zone.js@0.7.4` fixed the problem

### OS?
> macOS Sierra 10.12.2

### Versions.
> angular-cli: 1.0.0-beta.24
> node: 6.9.1
> os: darwin x64
> @angular/common: 2.4.3
> @angular/compiler: 2.4.3
> @angular/core: 2.4.3
> @angular/forms: 2.4.3
> @angular/http: 2.4.3
> @angular/platform-browser: 2.4.3
> @angular/platform-browser-dynamic: 2.4.3
> @angular/router: 3.4.3
> @angular/compiler-cli: 2.4.3

### The log given by the failure.
> TypeError: Cannot set property 'stack' of undefined
	    at SyntaxError.set [as stack] (webpack:///~/@angular/compiler/src/facade/errors.js:64:31 <- src/test.ts:55573:61)
	    at assignAll (webpack:///~/zone.js/dist/zone.js:704:0 <- src/test.ts:71100:29)
	    at SyntaxError.ZoneAwareError (webpack:///~/zone.js/dist/zone.js:775:0 <- src/test.ts:71171:16)
	    at SyntaxError.BaseError [as constructor] (webpack:///~/@angular/compiler/src/facade/errors.js:26:0 <- src/test.ts:55535:16)
	    at new SyntaxError (webpack:///~/@angular/compiler/src/util.js:151:0 <- src/test.ts:5508:16)
	    at DirectiveNormalizer.normalizeLoadedTemplate (webpack:///~/@angular/compiler/src/directive_normalizer.js:127:0 <- src/test.ts:13379:19)
	    at DirectiveNormalizer.normalizeTemplateSync (webpack:///~/@angular/compiler/src/directive_normalizer.js:104:0 <- src/test.ts:13356:21)
	    at DirectiveNormalizer.normalizeTemplate (webpack:///~/@angular/compiler/src/directive_normalizer.js:81:0 <- src/test.ts:13333:43)
	    at CompileMetadataResolver._loadDirectiveMetadata (webpack:///~/@angular/compiler/src/metadata_resolver.js:207:29 <- src/test.ts:14575:75)
	    at webpack:///~/@angular/compiler/src/metadata_resolver.js:383:33 <- src/test.ts:14751:54
	    at Array.forEach (native)
	    at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (webpack:///~/@angular/compiler/src/metadata_resolver.js:382:0 <- src/test.ts:14750:41)
	    at webpack:///~/@angular/compiler/src/jit/compiler.js:170:0 <- src/test.ts:39012:58
	    at Array.forEach (native)
	    at JitCompiler._loadModules (webpack:///~/@angular/compiler/src/jit/compiler.js:169:0 <- src/test.ts:39011:43)
	TypeError: Cannot read property 'detectChanges' of undefined
	    at Object.<anonymous> (webpack:///src/app/banner/banner-inline.component.spec.ts:28:12 <- src/test.ts:72233:16)
	    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:242:0 <- src/test.ts:70638:26)
	    at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- src/test.ts:51715:39)
	    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:241:0 <- src/test.ts:70637:32)
	    at Zone.run (webpack:///~/zone.js/dist/zone.js:113:0 <- src/test.ts:70509:43)
	    at Object.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:102:0 <- src/test.ts:51430:34)
	    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- src/test.ts:51460:42)

**Comment by arunsn43** [comment]
Reverting to zone.js@0.7.4 fixed this problem **(^0.7.4)** 
Zone.js was referred earlier in package.json as ~0.7.4.

**Comment by luozt** [comment]
zone.js@0.7.5 really prevents Angular to display error message. Downgrading zone.js to version 0.7.4 helps.

**Comment by guneybilen** [comment]
Downgrading advice to 0.7.2 helped me. Thanks!

**Comment by istiti** [comment]
same error ü

**Comment by istiti** [comment]
same error

**Comment by rodneyjoyce** [comment]
Downgrading to 0.7.4 helped - 0.7.5 obscured it

**Comment by MatGhp** [comment]
Downgrading to 0.7.2 caused : 
`'Uncaught TypeError: Cannot set property stack of [object Object] which has only a getter' with Angular #427`
[zone.js issue](https://github.com/angular/zone.js/issues/427)

Packages : 
` "dependencies": {
    "@angular/common": "^2.4.3",
    "@angular/compiler": "^2.4.3",
    "@angular/core": "^2.4.3",
    "@angular/forms": "^2.4.3",
    "@angular/http": "^2.4.3",
    "@angular/platform-browser": "^2.4.3",
    "@angular/platform-browser-dynamic": "^2.4.3",
    "@angular/router": "^3.4.3",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.4.3",`

**Comment by aatinubu** [comment]
I got the same error earlier today. 

It was generated because I failed to import a module (ReactiveFormsModule)  in my app.module file.

Ensure you import every dependency in your app.module.

Cheers!

**Comment by beeman** [comment]
The issue has been fixed in zone.js version 0.7.6. 

`npm install --save zone.js@0.7.6` should fix this, and new apps created with `ng new` or `ng init` are now work out of the box again :)

**Comment by arunsn43** [comment]
Upgrading to ^0.7.6 worked !! Thank you!

**Comment by bluehenry** [comment]
npm install --save zone.js@0.7.4 fixed the problem for me

Thank you guys!

**Comment by Germcguire87** [comment]
I feel like this needs to be reopened. Certain errors are still obscured. I am getting an error that reads when using ^0.7.6

Error: Uncaught (in promise): Error: DI Error

when using  zone.js@0.7.4  is reads

Error: Uncaught (in promise): Error: No provider for RouterExtendedService!

which of course is much more helpful

**Comment by beeman** [comment]
@Germcguire87 I actually think that is an issue that should be opened here https://github.com/angular/zone.js as angular-cli can not change that behavior.

**Comment by bardiarastin** [comment]
switching to zone.js 0.7.4 solved my problem 
thank you @sprider

**Comment by CaliThemanDC** [comment]
You guys rock. This worked for me

**Comment by jrood** [comment]
reverting to 0.7.4 fixed this issue for me too

**Comment by beeman** [comment]
Please note that the most recent version of zone.js is 0.7.6 and that one fixes the issue too.

**Comment by jrood** [comment]
@beeman ah yes thanks, 0.7.6 works for me too

**Comment by damirkusar** [comment]
I had also to downgrade to 0.7.4 to make things work again.
