### ISSUE TITLE
Cannot read property 'kind' of undefined : AOT build with Beta 28.3 [TEMP FIX]

### ISSUE THREAD

**Issue by maxime1992** [angular/angular-cli#4343]
> Please provide us with the following information:
> ---------------------------------------------------------------

I had this error when I upgraded to beta 28.3 and found a way to build with AOT.
Here's the error and how to temporarily avoid breaking your AOT build until this get fixed.

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16.10 x64

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.28.3
node: 7.4.0
os: linux x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/flex-layout: 2.0.0-beta.4
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Upgrade from angular-cli BETA 26 to 28.3

### The log given by the failure.
> Normally this include a stack trace and some more information.
```
ERROR in ./src/app/app.component.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at /home/maxime/Documents/petals-cockpit/frontend/node_modules/@ngtools/webpack/src/loader.js:93:31
    at Array.map (native)
    at _addCtorParameters (/home/maxime/Documents/petals-cockpit/frontend/node_modules/@ngtools/webpack/src/loader.js:92:46)
    at /home/maxime/Documents/petals-cockpit/frontend/node_modules/@ngtools/webpack/src/loader.js:114:17
    at Array.forEach (native)
    at _removeDecorators (/home/maxime/Documents/petals-cockpit/frontend/node_modules/@ngtools/webpack/src/loader.js:109:10)
    at /home/maxime/Documents/petals-cockpit/frontend/node_modules/@ngtools/webpack/src/loader.js:280:48
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/$$_gendir/app/app.component.ngfactory.ts 12:0-51
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

### Mention any other details that might be useful.
When I first upgraded to beta 28.3, my AOT build was broken.

I remembered having issues with `yarn` blocking the update of deps with `^` and I thought I would just `yarn upgrade` every time I update the cli.

But this time it was the opposite.

### TEMP FIX
In order to fix that, once I had run `ng init` I had to remove the current `yarn.lock` and restore the latest one before the update of angular-cli.

Then run `yarn` and it's now working again.

There must have some sub deps breaking the AOT build and using yarn to avoid the update of those deps is helpful here :+1:

**Comment by intellix** [comment]
Also getting a few 'kind' of undefined errors but I don't believe it's related to `yarn` as I'm getting it with NPM and after cleaning alsorts of caches etc.

I believe this used to happen with ZoneJS 0.7.5 where errors were hidden behind this error. I've tried 0.7.4 to no luck and will have to debug a little further but it takes some time as an AOT isn't quick :)

**Comment by intellix** [comment]
ok so I've narrowed down the issue to components where I'm injecting via tokens like:

```typescript
import { OpaqueToken } from '@angular/core';

export const currenciesToken = new OpaqueToken('currencies');
export const currencies = [{...}];
```

And getting errors in components that do:

```typescript
constructor(@Inject(currrenciesToken) currencies)
```

**Comment by Meligy** [comment]
Have you tried specifying a type for the `currencies` argument (even if `any`)?

**Comment by maxime1992** [comment]
@intellix it's not related to yarn (not **because of yarn**).
On the contrary. What am saying is that yarn allows us not to update sub dep with `^` and as you mentionned
>I believe this used to happen with ZoneJS 0.7.5

Using yarn maybe it was not updated and that's why I'm still able to build with AOT flag (even tho it's not a fix, just a way to stick with beta 28.3).

**Comment by intellix** [comment]
Yep you're right Meligy, it's fixed by specifying a type on my injects

**Comment by maxime1992** [comment]
@intellix @Meligy Thanks for debug/tips it's also working on my end when upgrading all the deps and giving `any` as a type on every inject :smile: 

I let the issue open tho because maybe this needs a fix or at list a precise warning

**Comment by filipesilva** [comment]
Closing as it seems like it's fixed.

**Comment by born2net** [comment]
I still see the issue in .30 build

```
$ ng serve --port 4208 --aot true
** NG Live Development Server is running on http://localhost:4208. **
Hash: 58d5ddf1e574295b454f
Time: 59751ms
chunk    {0} 0.chunk.js, 0.bundle.map 910 kB {1} {2} {3} {4} {5} {6} {7} [rendered]
chunk    {1} 1.chunk.js, 1.bundle.map 65.7 kB {0} {2} {3} {4} {5} {6} {7} [rendered]
chunk    {2} 2.chunk.js, 2.bundle.map 173 kB {0} {1} {3} {4} {5} {6} {7} [rendered]
chunk    {3} 3.chunk.js, 3.bundle.map 72.6 kB {0} {1} {2} {4} {5} {6} {7} [rendered]
chunk    {4} 4.chunk.js, 4.bundle.map 173 kB {0} {1} {2} {3} {5} {6} {7} [rendered]
chunk    {5} 5.chunk.js, 5.bundle.map 25.1 kB {0} {1} {2} {3} {4} {6} {7} [rendered]
chunk    {6} 6.chunk.js, 6.bundle.map 26.8 kB {0} {1} {2} {3} {4} {5} {7} [rendered]
chunk    {7} main.bundle.js, main.bundle.map (main) 757 kB {10} [initial] [rendered]
chunk    {8} styles.bundle.js, styles.bundle.map (styles) 339 kB {11} [initial] [rendered]
chunk    {9} scripts.bundle.js, scripts.bundle.map (scripts) 1.63 MB {11} [initial] [rendered]
chunk   {10} vendor.bundle.js, vendor.bundle.map (vendor) 5.85 MB [initial] [rendered]
chunk   {11} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/services/StoreService.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:93:31
    at Array.map (native)
    at _addCtorParameters (C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:92:46)
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:114:17
    at Array.forEach (native)
    at _removeDecorators (C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:109:10)
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:282:48
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/locale/app/app-module.ngfactory.ts 85:0-56
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4208/ ./src/main.ts

ERROR in ./src/store/effects/appdb.effects.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:93:31
    at Array.map (native)
    at _addCtorParameters (C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:92:46)
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:114:17
    at Array.forEach (native)
    at _removeDecorators (C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:109:10)
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:282:48
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/locale/app/app-module.ngfactory.ts 65:0-62
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4208/ ./src/main.ts

ERROR in ./src/store/effects/msdb.effects.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:93:31
    at Array.map (native)
    at _addCtorParameters (C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:92:46)
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:114:17
    at Array.forEach (native)
    at _removeDecorators (C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:109:10)
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:282:48
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/locale/app/app-module.ngfactory.ts 66:0-61
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4208/ ./src/main.ts

ERROR in ./src/comps/sliderpanel/Sliderpanel.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:93:31
    at Array.map (native)
    at _addCtorParameters (C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:92:46)
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:114:17
    at Array.forEach (native)
    at _removeDecorators (C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:109:10)
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:282:48
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/modules/shared.module.ts 2:0-63
 @ ./src/locale/app/app-module.ngfactory.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4208/ ./src/main.ts
webpack: Failed to compile.
```


versions

```
@angular/cli: 1.0.0-beta.30
node: 6.9.5
os: win32 x64
@angular/cli: 1.0.0-beta.30
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/language-service: 2.4.6
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
@ngtools/webpack: 1.2.7
```

repo:   git clone https://github.com/born2net/studioweb.git

**Comment by born2net** [comment]
can you please re-open

**Comment by born2net** [comment]
I am not sure which injects to fix as the issue is from the loader (.30 latest)

```
ERROR in ./src/store/effects/appdb.effects.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:93:31
    at Array.map (native)
    at _addCtorParameters (C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:92:46)
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:114:17
    at Array.forEach (native)
    at _removeDecorators (C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:109:10)
    at C:\Temp\ia\studioweb\node_modules\@ngtools\webpack\src\loader.js:282:48
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/locale/app/app-module.ngfactory.ts 65:0-62
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Comment by born2net** [comment]
so I can confirm removing every single @inject "fixes" the issues as a workaround
hope we can get it fixed as I still need to @inject 
for example
```
 @Inject(DOCUMENT) private doc
```
regards
