### ISSUE TITLE
Getting Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable

### ISSUE THREAD

**Issue by xtianus79** [angular/angular-cli#4647]
### OS?
MacOS Sierre

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 6.2.2
os: darwin x64

### Repro steps.
Getting this error with using Angular CLI

    Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/mbp06/Repos/multiple-date-picker-a2/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/mbp06/Repos/multiple-date-picker-a2/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Users/mbp06/Repos/multiple-date-picker-a2/node_modules/@angular/core/src/di/opaque_token.d.ts

**Comment by myGuruPitka** [comment]
same here.
i've fixed that by extracting to a function. 
but it didn't happen before. 
any better fix?

so this:
```
TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (http: Http) => new TranslateStaticLoader(http, '/assets/i18n', '.json'),
      deps: [Http]
    })
```
become this:
```
function httpFactory(http: Http) {
  return new TranslateStaticLoader(http, '/assets/i18n', '.json');
}

TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: httpFactory,
      deps: [Http]
    })
```

here is my fix:
![image](https://cloud.githubusercontent.com/assets/2412543/22877607/da52ae0c-f1de-11e6-94d6-457c6d4b215b.png)

**Comment by myGuruPitka** [comment]
also re-opened at #3707

**Comment by martin-siden** [comment]
I'm getting this error on `FlexLayoutModule` when trying to run my app. 
If I do a dummy edit in some file and hit "ctrl + s" again, it compiles but console dumps out:

> FlexLayoutModule.forRoot() has been deprecated and is no longer needed

I'm using Angular v2.4.7 and Angular CLI v1.0.0-beta.31.

**Comment by marioleed** [comment]
I also found some strange things: https://github.com/angular/angular-cli/issues/3674#issuecomment-279977533

**Comment by zagros** [comment]
Getting the exact same issue with a brand new application I just made now.

When I do 

`./node_modules\.bin/ng-xi18n -p ./src/tsconfig.json`

I get this:

```
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exp
ed function, resolving symbol Injectable in D:/Temp/newprj--fe/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in D:/Temp/newprj--fe/node_modules/@angular/core/src
/opaque_token.d.ts, resolving symbol OpaqueToken in D:/Temp/newprj--fe/node_modules/@angular/core/src/di/opaque_token.d.ts
    at SyntaxError.BaseError [as constructor] (D:\Temp\newprj--fe\node_modules\@angular\compiler\bundles\compiler.umd.js:1597:31)
    at new SyntaxError (D:\Temp\newprj--fe\node_modules\@angular\compiler\bundles\compiler.umd.js:1795:20)
    at simplifyInContext (D:\Temp\newprj--fe\node_modules\@angular\compiler\bundles\compiler.umd.js:25783:27)
    at StaticReflector.simplify (D:\Temp\newprj--fe\node_modules\@angular\compiler\bundles\compiler.umd.js:25795:17)
    at StaticReflector.annotations (D:\Temp\newprj--fe\node_modules\@angular\compiler\bundles\compiler.umd.js:25291:64)
    at NgModuleResolver.resolve (D:\Temp\newprj--fe\node_modules\@angular\compiler\bundles\compiler.umd.js:17771:86)
    at CompileMetadataResolver.getNgModuleMetadata (D:\Temp\newprj--fe\node_modules\@angular\compiler\bundles\compiler.umd.js:18272:64)
    at addNgModule (D:\Temp\newprj--fe\node_modules\@angular\compiler\bundles\compiler.umd.js:25053:62)
    at D:\Temp\newprj--fe\node_modules\@angular\compiler\bundles\compiler.umd.js:25064:18
    at Array.forEach (native)
Extraction failed
```

Here's my package.json


```
"dependencies": {
    "@angular/common": "^2.4.8",
    "@angular/compiler": "^2.4.8",
    "@angular/compiler-cli": "^2.4.8",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.8",
    "@angular/http": "^2.4.8",
    "@angular/platform-browser": "^2.4.8",
    "@angular/platform-browser-dynamic": "^2.4.8",
    "@angular/router": "^3.4.8",
    "angular-cli": "^1.0.0-beta.28.3",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "ng2-bootstrap": "^1.3.3",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-beta.31",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.0"
  }
```

**Comment by da45** [comment]
I got the following message: 
ERROR in Error encountered resolving symbol values statically. Calling function 'FlexLayoutModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/(....)/src/app/app.module.ts, resolving symbol AppModule in C:/(....)/src/app/app.module.ts

but application works fine,

**Comment by 1-0-1** [comment]
This error can also be thrown by referencing modules outside of your project directory.  If you have a shared folder that you keep re-usable modules and are referencing modules in that directory through relative references you will get this error, also.  Using a symbolic link to the shared directory fixed this issue for me.

**Comment by filipesilva** [comment]
Heya, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

The CLI always runs statical analysis on code to ensure it will run when compiled with AOT. This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

A good resource on how to to debug these errors is https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts.

**Comment by 1-0-1** [comment]
Why am I being blindsided?  When I run the build with the --dev flag, everything works.  Running it with the --prod flag breaks the build.  WHY?!?!?!  I'm getting really tired of error messages that don't help.  If it is in @angular, it shouldn't be my concern.  Tell me what in my code is now magically breaking when it was working fine in non-production mode.
Thanks for letting me vent.  Onto 12 hours today and I've got to get the production build done with no clue as to why it is breaking before I can break for the day...

Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in .../node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in .../node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in .../node_modules/@angular/core/src/di/opaque_token.d.ts

**Comment by dehru** [comment]
I find it very "Opaque"

**Comment by uitgewis** [comment]
I believe this to be a bug as well. I get the warning, but once I save a source file the error disappears and the build completes successfully.

**Comment by snaikaw** [comment]
I was getting this error just now, but it turned out that the syntax error was in my HTML file. I had a messed up HEAD tag without a proper closing tag. Once I fixed that, the compile happened fine. So look out for errors in HTML too.

**Comment by kareljuricka** [comment]
@snaikaw same happened to me but when I run ng serve again, the error returned but after some onChange recompilation disappeared with success.

**Comment by code-tree** [comment]
> or upgrading for older versions where we didn't run this kind of analysis.

@filipesilva What older versions are you referring to here? I'm trying to upgrade from 2.3 to 4.0 and am getting below. Since it doesn't reference any of my own code I have no idea what is causing it. Have the AOT rules changed between 2.3 and 4.0 at all? Thanks

```Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /project/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /project/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /project/node_modules/@angular/core/core.d.ts```

**Comment by scote1977** [comment]
@1-0-1 ng build -prod now enables aot by default if I'm not mistaken. You can still use ng build -prod -aot=false.

**Comment by gnesher** [comment]
@filipesilva don't you think that after 6-7 months of the initial release it's time to have an official document on how to get AOT working? I love the work the Rangle.io guys have done and it's super helpful, but it's not complete and still leaves quite a bit of guesswork...

**Comment by n4uoase** [comment]
Why is this issue closed? Seems that lot of people running in the very same error.
So do I, I exactly get the error:
`Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in client-app/node_modules/ng2-breadcrumb/node_modules/@angular/core/core.d.ts`

Anybody able to help with this?

**Comment by gnesher** [comment]
@n4uoase  I do believe the Angular team does not consider this a "problem" more like a community challenge...

**Comment by Orodan** [comment]
+1 getting the same error when trying to update from 2.4 to 4.0.

**Comment by microchip78** [comment]
Same with me ... upgarded angular-cli from beta to release ... and problem appearing in one of the angular module ...

**Comment by n4uoase** [comment]
@gnesher I do not hope so. We have enough challenges in our code, we don't need challenges in foreign code also :-)
So what can we do? I need to compile the code to get in running on our server.

**Comment by gnesher** [comment]
@n4uoase you can try to reach out to the developers through gitter, they are usually responsive and will try to help - though frankly that fact that they've not updated the docs to reflect these problems after 7 months means this can't be a mistake. Personally I've decided to switch frameworks on all new projects. I'm only here trying to maintain a single legacy application. It's funny how an Angular2 application became legacy after 6 months of use...

**Comment by Simon-Briggs** [comment]
I got the same error upgrading from angular 2.4 to angular 4.0.

The library I was relying on had angular 2.4  as a dependency in their package.json. Changing that to a more relaxed peerDependency >2.4 or devDependency >2.4, fixed the issue for me.

**Comment by chinenyem** [comment]
Simon could you explain in detail what you did? I am getting the same error. it would be a great help.

**Comment by Simon-Briggs** [comment]
In the failing library's package.json I changed: 
```
"dependencies": {
    "@angular/common": "^2.3.1",
    etc....
}
```
to
```
"peerDependencies": {
    "@angular/common": ">=2.3.1",
    etc....
}
```

**Comment by Orodan** [comment]
Fix it with thanks to the post of @Simon-Briggs. Of course  this implies to be able to update the module causing the problem.

**Comment by code-tree** [comment]
Are these third party modules you are referring to? Could you give an example of one? My app doesn't use any non-official Angular modules, so I can't imagine this solves it for me.

**Comment by bammadamma** [comment]
Hi, I think this bug is teasing us one by one. 
- I am running angular 4; (after experiencing the problem updated all my node modules dependencies to latest see at the end the versions I am using)
- my editor is VS code;
-  all is running fine this morning (and I might ass I was seeing for the first time my app running as intended end to end). Then I was prompted to update VSC which I did.
- And started getting the error 

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 24:10 in the original .ts file), resolving symbol Model_Instance_Generator .....

I am injecting the model factory using an exported def from model_factory.ts file.
If I remove the provider injected at module level it builds but this is not a solution for me. 
I spent the last 4 hours struggling to solve this with no avail ... 
Please if someone knows why we started experiencing this I appreciate the help  ... 


 / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0 (e)
node: 7.7.4
os: win32 x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/compiler-cli: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/platform-server: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0

**Comment by chinenyem** [comment]
Can u provide the entire error message?

**Comment by bammadamma** [comment]
@chinenyem  thank you below is the full error message ...

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 24:10 in the original .ts file), resolving symbol Model_Instance_Generator in D:/projectfinmal/finmal_poc/fml-new/fmlpoc/src/services/wp/model_factory.ts, resolving symbol Model_Instance_GeneratorDef in D:/projectfinmal/finmal_poc/fml-new/fmltest/src/services/wp/model_factory.ts, resolving symbol Model_Instance_GeneratorDef in D:/projectfinmal/finmal_poc/fml-new/fmlpoc/src/services/wp_service.ts, resolving symbol AppModule in D:/projectfinmal/finmal_poc/fml-new/fmlpoc/src/app/app-module.ts, resolving symbol AppModule in D:/projectfinmal/finmal_poc/fml-new/fmlpoc/src/app/app-module.ts

**Comment by chinenyem** [comment]
Thanks now can u provide the code for model_factory.ts.

**Comment by bammadamma** [comment]
Hi,
@chinenyem

removed node_module  and reinstalled again afresh;
tried to npm run build. It failed with the same error message;
then removed the factory provider, it built but can not run it as it is buggy because of the removed instance generator;
finally put back the provider and this time started it using npm start ( I am using custom webpack after ejecting hence the npm start rather than ng server)

to my surprise, it worked no more the error.  I am very puzzled, when I know why it worked I will post but for the time being  with all my confusion I will keep on developing  and keep an eye on it.

**Comment by FrancescoMussi** [comment]
Same error happening here after upgrading Ionic 2 to Ionic 3. Why has been this issue closed?

**Comment by sabrio** [comment]
Any solution so far?!

**Comment by manjot-cams** [comment]
@Simon-Briggs that worked for me dude! Thank you!!! 🌚

**Comment by sabrio** [comment]
Using `ng build --prod --aot=false` you wont face this problems hopefully and I also went throw all of the errors and fixed them which took me about a day and in the end the results are as follow: 
`ng build --prod` 4.20MB
`ng build --prod --aot=false` 4.19MB
Angular: 4.0.2 CLI: 1.0.0
Hope u find it useful.

**Comment by larssn** [comment]
@sabrio This will use the JiT compiler, which will give a bigger and slower app - something AoT is designed to avoid.

**Comment by sabrio** [comment]
@larssn It may decrease the performance (I am not sure about this) but in term of size it is almost the same, I have at least 20 component and huge app and the result are the same.

**Comment by larssn** [comment]
Well when using JiT, the templates are compiled dynamically at runtime, by the client. AoT compiles them at compile-time.

**Comment by larssn** [comment]
And if you use AoT you should be able to remove the dependency on "@angular/platform-browser-dynamic".

**Comment by yoojene** [comment]
@Simon-Briggs's solution worked for me also using Angular 4.
```
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
```
```
  "peerDependencies": {
    "@angular/common": ">=4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": ">=4.0.0",
    etc
```

**Comment by trekhleb** [comment]
I had the same issue with error "_ERROR in Error encountered resolving symbol values statically. Calling function ɵmakeDecorator_". In my case it was happening when I linked [custom Angular library](https://github.com/trekhleb/angular-library-seed) (that was developed locally) to Angular CLI project via `yarn link` and then ran `ng build --prod` to test AOT build. For some reason having `node_modules` folder in my linked library caused that error.

The following workaround https://github.com/angular/angular-cli/issues/3854#issuecomment-274344771 has saved my day. Specifying `paths` to `@angular` inside AngularCLI's `tsconfig.json` prevented the error from happening.

`"paths": { "@angular/*": ["../node_modules/@angular/*"] }` 

More details here https://github.com/angular/angular-cli/issues/3854#issuecomment-274344771 and here https://github.com/angular/angular-cli/issues/3854#issuecomment-299109237.

**Comment by pandaen** [comment]
Troubleshooting for several days and here is the solution. you save my career.
Thanks.

**Comment by MrToasty97** [comment]
@trekhleb you saved my day too, thanks!

**Comment by sollenne** [comment]
@trekhleb answer is the correct answer... everybody stop looking for it.

**Comment by aleixsuau** [comment]
Similar to @webernir case, in my case what worked out was extract all the provider configuration object to the provider file:

**custom-http.service.ts**
`
@Injectable()
export class CustomHttpService extends Http { ... }

export **function customHttpFactory** (backend: XHRBackend, defaultOptions: RequestOptions) {
    return new CustomHttpService(backend, defaultOptions);
};

export let customHttpProvider = {
  provide: CustomHttpService,
  useFactory: customHttpFactory,
  deps: [ XHRBackend, RequestOptions ]
};`

**app.module.ts**
`
import { customHttpProvider } from './shared/services/custom-http/custom-http.service';
@NgModule({
providers: [
    customHttpProvider
 ],
...
}
`
**Don't use a arrow function** when exporting the Factory (customHttpFactory in this case), it will fail.

**Comment by amolpshinde07** [comment]
facing below issue when importing function from module as 'RiaCommonsModule.forRoot()'

ERROR in Error encountered resolving symbol values statically. Calling function 'RiaCommonsModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol getRiaCommonsModule in D:/SureCall/Angular-CLI/AnC-Client/src/app/app.module.lib.ts, resolving symbol AppModuleLib in D:/SureCall/Angular-CLI/AnC-Client/src/app/app.module.lib.ts, resolving symbol AppModuleLib in D:/SureCall/Angular-CLI/AnC-Client/src/app/app.module.lib.ts

**Comment by Yugloocamai** [comment]
@trekhleb helped me too.  Not really sure why this works though... :thinking:

**Comment by Mumumurilo** [comment]
@trekhleb 's solution did not work for me, unfortunately. I have the exact same error as him, and I don't have any yarn-linked projects (although I have one external project being referenced in a lot of components).

I still receive the same error:

`Error: Error encountered resolving symbol values statically. Calling function 'makeParamDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/muriloromera/Documents/Git Repos/reserva-de-espacos/Shared/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/muriloromera/Documents/Git Repos/reserva-de-espacos/Shared/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Users/muriloromera/Documents/Git Repos/reserva-de-espacos/Shared/node_modules/@angular/core/src/di/opaque_token.d.ts`

**Comment by sciborrudnicki** [comment]
@trekhleb for me it is working too ... thank you.

**Comment by lukeclifton** [comment]
Adding `"paths": { "@angular/*": ["../node_modules/@angular/*"] },` in `tsconfig.json` file worked for me too. Thanks @trekhleb.

**Comment by trickmeyer** [comment]
I followed @Simon-Briggs April 4 suggestion, and in addition removed the dependency's node_modules folder.  Working fine now.

**Comment by Fiv38** [comment]
@trekhleb 's solution didnt work for me too. I added path in tsconfig.json file but still receive the same error

**Comment by ilia5050** [comment]
I've got ng2-translate modul TranslateStaticLoader problem like @webernir. his solution can't fixed my problem, but after I add "export" keyword to his httpFactory function error fixed, like this: 
...
export function httpFactory(http: Http) {
  return new TranslateStaticLoader(http, '/assets/i18n', '.json');
}
...
hope this helps someone

**Comment by sukainarizvi** [comment]
Try: npm install --save @angular/cdk

**Comment by Fiv38** [comment]
Thank you for your reply, hey the problem was solved,

I add you on Github k?


2017-08-04 20:19 GMT+07:00 Sukaina Rizvi <notifications@github.com>:

**Comment by deepthan** [comment]
I made this mistake when I created a new project, but tried all the solutions failed, what should I do?

**Comment by leticiafatimaa** [comment]
@trekhleb for me it is working too :D

**Comment by martinsik** [comment]
Just FYI there's now official troubleshooting guide for this error https://angular.io/guide/metadata#function-calls-are-not-supported.

None of the things listed there helped me. It turned out the problem was that the library I'm developing didn't specify `typings` in its `package.json`.

**Comment by qasimraza1979** [comment]
@trekhleb your solution does not work for me. I am getting following error message when trying to import angular-seed-libary into a ionic project.

1: I have tried "paths": { "@angular/*": ["../node_modules/@angular/*"] } in both tsconfig of angular-seed-library and also in ionic project no solution still the same error.
2: This error appears if I do _**yarn link**_ and then run _**ionic-app-scripts build --prod**_ 
3: its over a month now since I am struck with this error. I do hope you understand my position here now :(  I will really appreciate, if any one can help on this.

```
$ yarn build:aot
yarn build:aot v0.27.5
$ ionic-app-scripts build --prod
[23:38:18]  ionic-app-scripts 2.1.4
[23:38:18]  build prod started ...
[23:38:18]  clean started ...
[23:38:18]  clean finished in 1 ms
[23:38:18]  copy started ...
[23:38:18]  ngc started ...
[23:38:21]  ionic-app-script task: "build"
[23:38:21]  Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider  replacing the function or lambda with a reference to an exported function 
(position 756:18 in the original .ts file),

resolving symbol Component in C:/Monsenso-Source/administration/node_modules/@monsenso/ 
components/node_modules/@angular/core/core.d.ts,

resolving symbol LoginComponent in C:/Monsenso-Source/administration/node_modules/@monsenso/
components/lib/components/login/login.component.d.ts,

resolving symbol LoginComponent in C:/Monsenso-Source/administration/node_modules/@monsenso/ 
components/lib/components/login/login.component.d.ts

Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider 
replacing the function or lambda with a reference to an exported function (position 756:18 in the original
 .ts file), resolving symbol Component in 
C:/Monsenso-Source/administration/node_modules/@monsenso/components/node_modules/ 
@angular/core/core.d.ts,

resolving symbol LoginComponent in C:/Monsenso-Source/administration/node_modules/@monsenso/
 components/lib/components/login/login.component.d.ts, 
resolving symbol LoginComponent in C:/Monsenso-Source/administration/node_modules/@monsenso/ 
components/lib/components/login/login.component.d.ts

    at positionalError (C:\Monsenso-Source\administration\node_modules\@angular\compiler\bundles\ 
compiler.umd.js:25266:35)

    at simplifyInContext (C:\Monsenso-Source\administration\node_modules\@angular\compiler\ 
bundles\compiler.umd.js:25109:27)

    at StaticReflector.simplify (C:\Monsenso-Source\administration\node_modules\@angular\compiler\ 
bundles\ compiler.umd.js:25123:13)

    at StaticReflector.annotations (C:\Monsenso-ource\administration\node_modules\@angular\compiler\ 
bundles\compiler.umd.js:24553:41)

    at NgModuleResolver.resolve (C:\Monsenso-Source\administration\node_modules\@angular\ 
compiler\ bundles\compiler.umd.js:14891:70)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Monsenso-Source\administration\node_modules\@angular\compiler\bundles\compiler.umd.js:15546:60)
    at addNgModule (C:\Monsenso-Source\administration\node_modules\@angular\compiler\bundles\compiler.umd.js:24403:58)
    at C:\Monsenso-Source\administration\node_modules\@angular\compiler\bundles\compiler.umd.js:24414:14
    at Array.forEach (native)
    at _createNgModules (C:\Monsenso-Source\administration\node_modules\@angular\compiler\bundles\compiler.umd.js:24413:26)
error Command failed with exit code 1.

```

**Comment by qasimraza1979** [comment]
I found the solution and will share here below
placed following two line into the tsConfig.json into the Angular CLI project (in my case my ionic project)

![image](https://user-images.githubusercontent.com/1721866/31439193-9d151952-ae8b-11e7-8352-468e12638bc9.png)

saved my life. It was a tough journey for a month now but nailed it ;-) 
I placed earlier in a wrong place, which indeed was a mistake.

**Comment by jbeckton** [comment]
wow, I wonder if React developers are dealing with issues like this?
