### ISSUE TITLE
ERROR in AppModule is not an NgModule and TS 2.2.1

### ISSUE THREAD

**Issue by coryrylan** [angular/angular-cli#5548]
## ERROR in AppModule is not an NgModule

- [x] bug report 

### Versions.
@angular/cli: 1.0.0-rc.4
node: 6.9.1
os: win32 x64
@angular/animations: 4.0.0-rc.5
@angular/common: 4.0.0-rc.5
@angular/compiler: 4.0.0-rc.5
@angular/core: 4.0.0-rc.5
@angular/forms: 4.0.0-rc.5
@angular/http: 4.0.0-rc.5
@angular/platform-browser: 4.0.0-rc.5
@angular/platform-browser-dynamic: 4.0.0-rc.5
@angular/router: 4.0.0-rc.5
@angular/cli: 1.0.0-rc.4
@angular/compiler-cli: 4.0.0-rc.5

### Repro steps.
Running Angular RC5 and CLI RC2 a `ng build` works. Updating to CLI RC 4 with yarn it fails with 
`ERROR in AppModule is not an NgModule` if TypeScript is set to `2.2.1`.  If installed with NPM everything works as normal. 

### The log given by the failure.
`ERROR in AppModule is not an NgModule`

### Mention any other details that might be useful.
Location of bug: I had typescript pinned to version `2.2.1` (latest) but for some reason after upgrading to CLI RC4 that fails when using Yarn. Moving the version back down to `2.1.x` solves this bug. This happens on Mac and Windows. Create a new CLI project and pin typescript to `2.2.1` to get the error.

**Comment by coryrylan** [comment]
After further investigation it is most definitely something in package json that is causing the issue. I'll narrow it down and report back for anyone who runs into this as well.

**Comment by jmesa-sistel** [comment]
If you delete node_modules and  use "npm i" instead yarn everything works fine.

**Comment by antonybudianto** [comment]
same error here, even after cleaning node_modules and yarn.lock, downgrading TS to 2.1.x is a good workaround for now

**Comment by jmesa-sistel** [comment]
@antonybudianto
after cleaning node_modules , have you installed the modules using "npm install" ?

**Comment by asadsahi** [comment]
I did reimraf node_modules, then did npm install. Getting same error.

Using 
```
"@angular/cli": "1.0.0-rc.4",
 "@angular/*: "4.0.0-rc.6",
```

**Comment by filipesilva** [comment]
I *think* this is fixed by https://github.com/angular/angular-cli/pull/5586.

**Comment by antonybudianto** [comment]
@jmesa-sistel I used yarn for installation

**Comment by TwanoO67** [comment]
I just updated to typescript ~2.3.0 to fix this

**Comment by nhnb** [comment]
I still can confirm this issue with yarn, while npm works. Comparing the license-checker output of npm (-) with yarn (+), I get the followings result:

```
-├─ coa@1.0.1
+├─ coa@1.0.2
+├─ esprima@3.1.3
+├─ js-yaml@3.8.4
+├─ minimist@0.0.10
-├─ os-tmpdir@1.0.2
-├─ postcss-modules-extract-imports@1.1.0
+├─ postcss-modules-extract-imports@1.2.0
-├─ q@1.5.0
+├─ sprintf-js@1.1.0
-├─ tmp@0.0.24
-├─ tmp@0.0.30
-├─ tmp@0.0.31
+├─ ws@1.1.4
```
But none of them is an obvious candidate for the root cause of this issue.

"@angular/core": "^4.1.3",
"@angular/cli": "^1.0.4",
"@angular/compiler-cli": "^4.1.3",
"typescript": "^2.3.3"

**Comment by maximelafarie** [comment]
Neither npm or yarn is working for me. The errors still here : 
![image](https://user-images.githubusercontent.com/5319267/28323308-b0090820-6bd8-11e7-85b2-9ba762bdd223.png)

My project package.json:
```
{
  "name": "nsm-test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "ngx-smart-modal": "^1.0.2",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.1.3",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
```

Is this issue coming from the project itself or from the package (`ngx-smart-modal`)?

**Comment by sumavr** [comment]
Any resolution on this? I am also getting the same error, suddenly

**Comment by kavi87** [comment]
The error is not solved, I'm still getting the error with "@ngtools/webpack": "1.7.2", "typescript": "2.2.2", and yarn 1.0.1

**Comment by Nasruddin** [comment]
I solved the issue by updating Typescript version to "~2.3.0"

**Comment by zhaoyi0113** [comment]
This issue still happens with `~2.3.0` typescript.
