### ISSUE TITLE
Error : ng build -prod => The Broccoli Plugin: [BundlePlugin] failed

### ISSUE THREAD

**Issue by choucry13** [angular/angular-cli#718]
When i want build my project in production mode (ng build -prod), The Broccoli Plugin can't found a file. However, the command ng build work normaly. 
--------------------------------------------------------------------------
1. OS => Windows 7
2. Versions : 
    - angular-cli: 1.0.0-beta.1
    - node: 6.1.0
    - os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code?
I update my project from angular cli v0.37 to 1.0.0 beta. 1 . My current project work fine.

4. Logs: 
D:\projects\PocNewBad\src\new-bad\aix\base-project-angular-cli>ng build -prod
(node:8768) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent
version.
| Building(node:8768) DeprecationWarning: 'root' is deprecated, use 'global'
(node:8768) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
Build failed.
The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for app/index.js at file:///D:/base-project-angular-cli/tmp/bundle_plugin-input_base_path-KQb5d
Vmu.tmp/0/app/index.js
        Error: ENOENT: no such file or directory, open 'D:\\base-project-angular-cli\tmp\bundle_plugin-input_ba
se_path-KQb5dVmu.tmp\0\app\index.js'
    at Error (native)

The broccoli plugin was instantiated at:
    at BundlePlugin.Plugin (D:\\base-project-angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (D:\\base-project-angular-cli\node_modules\broccoli-caching-
writer\index.js:21:10)
    at BundlePlugin (D:\\base-project-angular-cli\node_modules\angular-cli\lib\broccoli\angular-broccoli-bundle
.js:11:5)
    at Angular2App._getBundleTree (D:\\base-project-angular-cli\node_modules\angular-cli\lib\broccoli\angular2-
app.js:375:55)
    at Angular2App._buildTree (D:\projects\PocNewBad\src\new-bad\aix\base-project-angular-cli\node_modules\angular-cli\lib\broccoli\angular2-app.
js:137:21)
    at new Angular2App (D:\projects\PocNewBad\src\new-bad\aix\base-project-angular-cli\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:2
3)
    at module.exports (D:\projects\PocNewBad\src\new-bad\aix\base-project-angular-cli\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\projects\PocNewBad\src\new-bad\aix\base-project-angular-cli\node_modules\angular
-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\projects\PocNewBad\src\new-bad\aix\base-project-angular-cli\node_modules\angular-cli\lib\models\
builder.js:89:10)
    at new Class (D:\projects\PocNewBad\src\new-bad\aix\base-project-angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\projects\PocNewBad\src\new-bad\aix\base-project-angular-cli\node_modules\angular-cli\lib\tasks\bu
ild.js:15:19)
    at D:\projects\PocNewBad\src\new-bad\aix\base-project-angular-cli\node_modules\angular-cli\lib\commands\build.js:32:24
    at lib$rsvp$$internal$$tryCatch (D:\projects\PocNewBad\src\new-bad\aix\base-project-angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\projects\PocNewBad\src\new-bad\aix\base-project-angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)

    at lib$rsvp$$internal$$publish (D:\\base-project-angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\\base-project-angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

I will check if i found something, I post my solve.
Thank a lot :-)

**Comment by choucry13** [comment]
We have solve the problem by init all project :-)

**Comment by arunas-smala** [comment]
ng build -prod
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Build failed.
Same here. Nothing helps.

without `-prod` everything works fine. But with `-prod` I get:

```The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for ng2-bootstrap/ng2-bootstrap at file:///Users/arunassmaliukas/Projects/angularattack2016-smala/tmp/bundle_plugin-input_base_path-swarpJzu.tmp/0/ng2-bootstrap/ng2-bootstrap
	Loading app/template-builder.component.js
	Loading app/index.js
	Loading main.js
	Error: ENOENT: no such file or directory, open '/Users/arunassmaliukas/Projects/angularattack2016-smala/tmp/bundle_plugin-input_base_path-swarpJzu.tmp/0/ng2-bootstrap/ng2-bootstrap'
    at Error (native)```

Have tried remove node_modules dist tmp folders, `ng init`, etc.. nothing helps :(

**Comment by immysl** [comment]
Is this a known issue? `ng build` works fine and my package file gets created inside the `vendor` folder. However, `ng build -prod` does not work. It seems weird as it works with one command and not with the other. Hope someone can enlighten us about this :smile:

**Comment by pontusr** [comment]
Yes, I can also reproduce this with beta 4. ng build works fine whereas ng build -prod gives [BundlePlugin] error.

**Comment by hmrc87** [comment]
Same problem with the newest rc1

**Comment by AhsanAyaz** [comment]
Facing the same issue.. +1

Build failed.
The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for main.js at file:///Projects/wanna-web/tmp/bundle_plugin-input_base_path-fvVJG6ng.tmp/0/main.js
	Error: ENOENT: no such file or directory, open '/Projects/wanna-web/tmp/bundle_plugin-input_base_path-fvVJG6ng.tmp/0/main.js.map'
    at Error (native)

**Comment by ifaouibadi** [comment]
You get this error only when you change the default ng-cli structure .
src/app/main.ts will work fine
src/new-folder/app/main.ts you will get that error while build -prod

Hope this can help to slove it.

**Comment by hmrc87** [comment]
I left the original structure alone and it does not work :(

my main.ts is under projectname/frontend/src/maint.ts and underneath src there is /app. That is how the ng init created the structure. I might moved the whole folder around, but that should not be a problem, right?

**Comment by ifaouibadi** [comment]
can you make it  projectname/src/maint.ts
that will fix it.

if you want to compile it to a different location "ng build -prod --output-path dist/frontend-app"

**Comment by AhsanAyaz** [comment]
@ifaouibadi I have kept the original structure and it doesn't work :)

**Comment by dottodot** [comment]
Same problem is happening for me too. I've not changed the structure, the only thing I've done is added angular2-google-maps. It works fine when just using build but the -prod flag gice the error of

```
The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for angular2-google-maps/core.js at file:///Users/marcuswilliams/Hosts/bailey_hunt/tmp/bundle_plugin-input_base_path-6rPioF0w.tmp/0/angular2-google-maps/core.js
	Loading main.js
	Error: ENOENT: no such file or directory, open '/Users/marcuswilliams/Hosts/bailey_hunt/tmp/bundle_plugin-input_base_path-6rPioF0w.tmp/0/angular2-google-maps/core.js'
    at Error (native)

The broccoli plugin was instantiated at: 
    at BundlePlugin.Plugin (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BundlePlugin (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/lib/broccoli/angular-broccoli-bundle.js:11:10)
    at Angular2App._getBundleTree (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/lib/broccoli/angular2-app.js:421:22)
    at Angular2App._buildTree (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/lib/broccoli/angular2-app.js:159:21)
    at new Angular2App (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/marcuswilliams/Hosts/bailey_hunt/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/marcuswilliams/Hosts/bailey_hunt/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by koppor** [comment]
This seems to be https://github.com/angular/angular-cli/issues/847#issuecomment-220944072, isn't it?

**Comment by dottodot** [comment]
The version I'm using already has those changes

**Comment by julienboulay** [comment]
Same issue with angular2-material :

```
Error on fetch for vendor/@angular2-material/icon/icon-registry.js at file:///home/jboulay/Projets/MoiChef/easynov-web/tmp/bundle_plugin-input_base_path-jWv3cwsx.tmp/0/vendor/@angular2-material/icon/icon-registry.js
        Loading main.js
        Error: ENOENT: no such file or directory, open '/home/jboulay/Projets/MoiChef/easynov-web/tmp/bundle_plugin-input_base_path-jWv3cwsx.tmp/0/vendor/@angular2-material/icon/usr/local/google/home/jelbourn/material2/tmp/broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp/0/components/icon/icon-registry.js.map'
    at Error (native)

The broccoli plugin was instantiated at: 
    at BundlePlugin.Plugin (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BundlePlugin (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/lib/broccoli/angular-broccoli-bundle.js:10:36)
    at Angular2App._getBundleTree (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/lib/broccoli/angular2-app.js:421:22)
    at Angular2App._buildTree (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/lib/broccoli/angular2-app.js:159:21)
    at new Angular2App (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/home/jboulay/Projets/MoiChef/easynov-web/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/build.js:15:19)
    at /home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/node_modules/angular-cli/lib/commands/build.js:32:24
    at lib$rsvp$$internal$$tryCatch (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/jboulay/Projets/MoiChef/easynov-web/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by julienboulay** [comment]
I've found many issues regarding build failing with `-prod` option.
One of them gives a fix for issues with angular2-material lib : https://github.com/angular/angular-cli/issues/940#issuecomment-222265264

**Comment by datrinh** [comment]
I still have the same issue with RC1. Why is this closed?

angular-cli: 1.0.0-beta.5
node: 5.4.1
os: darwin x64 (OS X)

**Comment by filipesilva** [comment]
@datrinh this issue is closed because it was already solved and the solution was found. In your case, it looks like you upgraded a project, see https://github.com/angular/angular-cli/issues/847#issuecomment-220944072 .

**Comment by vargalas** [comment]
Seemingly the same issue here.
I'm using Angular Rc 1

angular-cli: 1.0.0-beta.5
node: 6.2.1
os: win32 x64
- "make sourcemaps relative in tsconfig.json by removing mapRoot:" my tsconfid didn't include mapRoot
- "configure angular-cli-build.js to also copy vendor map files:" it was also there already.
- "update local project angular-cli version to 1.0.0-beta.5." It's already that version

**Comment by hmrc87** [comment]
- Try deleting tmp and dist before trying again
- How does your system-config.ts look?

**Comment by vargalas** [comment]
Thnx. I deleted tmp and dist.

You gave me an idea to test: I'll try to remove theinternal packages.
My system-config.ts is:

`/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
  "changedName": "node_modules/changedName"
};

/** User packages configuration. */
const packages: any = {
  "changedName": {
    format: "cjs",
    defaultExtension: "js"
  }
};

////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
 * Everything underneath this line is managed by the CLI.
 **********************************************************************************************/
const barrels: string[] = [
  // Angular specific barrels.
  '@angular/core',
  '@angular/common',
  '@angular/compiler',
  '@angular/http',
  '@angular/router',
  '@angular/router-deprecated',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic',

  // Thirdparty barrels.
  'rxjs',

  // App specific barrels.
  'app',
  'app/shared',
  /** @cli-barrel */
];

const cliSystemConfigPackages: any = {
  "node_modules/changedName/*":"node_modules/changedName/*/dist/index.js"
};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});

/** Type declaration for ambient System. */
declare var System: any;

// Apply the CLI SystemJS configuration.
System.config({
  map: {
    '@angular': 'vendor/@angular',
    'rxjs': 'vendor/rxjs',
    'main': 'main.js',
    "changedName": "node_modules/changedName"
  },
  packages: cliSystemConfigPackages
});

// Apply the user's configuration.
System.config({ map, packages });`

**Comment by vargalas** [comment]
I removed the internal packages (I referenced them by 'changedName' above). 
ng build --prod still fails for me.

**Comment by Lightw3ight** [comment]
Just installed angular-cli 2 days ago and have the same/similar problem

Error on fetch for app/models/IArtist.js at file:///C:/Data/PlayMeExtension/tmp/bundle_plugin-input_base_path-VZeniFqQ.tmp/0/app/models/IArtist.js
        Loading app/models/index.js
        Error: ENOENT: no such file or directory, open 'C:\Data\PlayMeExtension\tmp\bundle_plugin-input_base_path-VZeniFqQ.tmp\0\app\models\IArtist.js'

However, IArtist is a definition file (IArtist.d.ts) - i wonder if that has something to do with it?

build without -prod works file

**Comment by hmrc87** [comment]
I had a lot of problems with the prod built. My angular-cli project was built with beta 4 and the first thing I did was to migrate all the blueprinted-files manually. Since I am using external libraries like ng2-bootstrap or regular ones like chart.js it was even more difficult to get the prod-built running. A good thing to start is to create the simplest angular-cli project you can imagine and test the prod-built. Then add something you added in your real project and try the prod built again until it breaks. You can also try figuring out the difference between the "simplest angular-cli" project and your project by comparing them in an editor. With this technique I could upgrade my project files pretty easy from v4 to v5

Right now I am looking through my file changes in git, that I did after this in order to get the prod-built working. I hope you will find the solution for your problem:

**angular-cli.build.js**
Make sure, that all the needed libraries include the .map files, especially for your custom added ones.(like this:  ` @angular/**/*.+(ts|js|js.map) ` ). Also make sure, that you choose the right folder of the package. In my case of "chart.js" I had to include every folder and subfolder to make it work ( `chart.js/**/*.+(js|js.map) `). Well, this does not seem right, but it works for right now

**system-config.ts**
Make sure to set the right format for the package. An example of my system-config is here:

```
/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
  "ng2-bootstrap" : "vendor/ng2-bootstrap",
  "moment"        : "vendor/moment/moment.js",
  "ng2-table"     : "vendor/ng2-table",
  "ng2-charts"    : "vendor/ng2-charts",
  "ng2-uploader"  : "vendor/ng2-uploader",
  'chartjs'       : 'vendor/chart.js/dist/Chart.bundle.js',
  "dragula"       : "vendor/dragula/dist/dragula.js",
  "ng2-dragula"   : "vendor/ng2-dragula"
};

/** User packages configuration. */
const packages: any = {
  'ng2-bootstrap':{ format: "cjs", main: 'ng2-bootstrap.js',"defaultExtension": "js" },
  'ng2-table':{ format: "cjs", main: 'ng2-table.js',"defaultExtension": "js" },
  'ng2-charts':{ format: "cjs", main: 'ng2-charts.js',"defaultExtension": "js" },
  'ng2-uploader':{ format: "register", main: 'ng2-uploader.js',"defaultExtension": "js" },
  'dragula':{ format: "global" },
  'ng2-dragula':{ format: "cjs", main: "ng2-dragula", "defaultExtension": "js" },
  'chartjs':{ format: "global" },
  'moment':{ format: "cjs", defaultExtension: "js" }

};

////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
 * Everything underneath this line is managed by the CLI.
 **********************************************************************************************/
const barrels: string[] = [
  // Angular specific barrels.
  '@angular/core',
  '@angular/common',
  '@angular/compiler',
  '@angular/http',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic',
  '@angular/router',
  // Thirdparty barrels.
  'rxjs',

  // App specific barrels.
  'app',
  'app/shared',
  'app/dashboard',
  'app/folio',
  'app/folio/foliodetail',
  'app/competence',
  'app/export',
  'app/product',
  'app/system',
  'app/appcontent',
  'app/competence/competencedetail',
  'app/folio/foliolist',
  'app/appcontent/appcontent-tab',
  'app/listboxes',
  /** @cli-barrel */
];

const cliSystemConfigPackages: any = {};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});

/** Type declaration for ambient System. */
declare var System: any;

// Apply the CLI SystemJS configuration.
System.config({
  map: {
    '@angular': 'vendor/@angular',
    'rxjs': 'vendor/rxjs',
    'main': 'main.js'
  },
  packages: cliSystemConfigPackages
});

// Apply the user's configuration.
System.config({ map, packages });


```

** main component ts **
In my main component file I had to add an import for chartjs and dragula so that the SystemJS-Builder knows about them

```
import 'chartjs'; 
import  'dragula'; 

```

I also added the typings for those Standard/Global libraries, but I guess this is more important for the IDE.

**Comment by ghpabs** [comment]
@hmrc87 I've done all the changes you suggested - still no luck :-(

```
Build failed.
The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for main.js at file:///C:/my-folder/tmp/bundle_plugin-input_base_path-YFP4tyEM.tmp/0/main.js
        Error: ENOENT: no such file or directory, open 'C:\my-folder\tmp\bundle_plugin-input_base_path-YFP4tyEM.tmp\0\main.js.map'
    at Error (native)

The broccoli plugin was instantiated at:
    at BundlePlugin.Plugin (C:\my-folder\node_modules\broccoli-plugin\index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (C:\my-folder\node_modules\broccoli-caching-writer\index.js:21:10)
    at BundlePlugin (C:\my-folder\node_modules\angular-cli\lib\broccoli\angular-broccoli-bundle.js:10:36)
    at Angular2App._getBundleTree (C:\my-folder\node_modules\angular-cli\lib\broccoli\angular2-app.js:375:55)
    at Angular2App._buildTree (C:\my-folder\node_modules\angular-cli\lib\broccoli\angular2-app.js:137:21)
    at new Angular2App (C:\my-folder\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
    at module.exports (C:\my-folder\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\my-folder\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\my-folder\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\my-folder\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\my-folder\node_modules\angular-cli\lib\tasks\build.js:15:19)
    at C:\my-folder\node_modules\angular-cli\lib\commands\build.js:32:24
    at lib$rsvp$$internal$$tryCatch (C:\my-folder\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\my-folder\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\my-folder\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\my-folder\node_modules\rsvp\dist\rsvp.js:1198:9)
```

**Comment by filipesilva** [comment]
@ghpabs it looks like your project was created with an old version of the CLI. See https://github.com/angular/angular-cli#updating-angular-cli for a way to upgrade your local files.

**Comment by ghpabs** [comment]
@filipesilva you're absolutely right. Updating `angular-cli` to @latest did the trick.

**Comment by hareeshav** [comment]
Hi,
i'm able to serve the files with http server, ng serve. But I want to deploy to tomcat server, I ran the command ng build -prod and got the dist folder created. I need to place the dist folder content inside project folder of webapps. Let say, sampleapp is my project folder, I copied all the contents ,generated in dist folder to sampleapp folder. When i access the application in getting lot of 404 error(
http://localhost:8080/vendor/systemjs/dist/system.src.js). It seems Angular is looking in root direectory. How can i customize the build to read it from my project directory?
like 
http://localhost:8080/sampleapp/vendor/systemjs/dist/system.src.js
I tried editing the index.html tag , <base href="/sampleapp"> and then built. No luck

Which file I have to look out for the ng-build command. Please help me out in finding the solution
