### ISSUE TITLE
Support TypeScript 2.4+

### ISSUE THREAD

**Issue by omouse** [angular/angular-cli#7578]
forgot to update the package.json for newly generated projects: https://github.com/angular/angular-cli/blob/128187e4c1b20aa5e6231099f1cb80e094a2d8d9/packages/%40angular/cli/blueprints/ng/files/package.json#L50

somehow was missed in this commit: https://github.com/angular/angular-cli/commit/7b9fc285e3a9f6d06aa4a42c4b5e550c929888d7

also there's a weirder issue related to this. I updated the package.json in my angular-cli generated project to 2.4.x for typescript and whenever I run `ng serve` and `ng build` it seems to always use 2.3.3, while when I run `$(npm bin)/tsc` it is the correct version that matches what I put in the package.json.

**Comment by clydin** [comment]
This was intentional; note the description of the linked commit.

**Comment by omouse** [comment]
@clydin this description?

> This PR doesn't change new projects to use 2.4 since I have seen some reports of possible problems in `@angular/*`.
> 
> Instead, it:
> - removes the dependency restrictions on <2.3
> - bumps related dependencies to the minimum that supports 2.4 (`rxjs@^5.4.2`, `ts-node@~3.2.0`)
> - builds the CLI itself using 2.4
> 
> So if you want to install ts 2.4 in your new project, the CLI itself won't stop you.

I installed typescript 2.4 in my angular project that uses angular-cli and it *still looked like it was using 2.3 because it reported an error that would only happen with 2.3 installed*. As noted, when I ran `ng build` it appeared to still use 2.3 while the node_modules directory definitely contained tsc 2.4.x and when I ran `$(npm bin)/tsc` it was running 2.4.x.

**Comment by clydin** [comment]
That part is definitely not  intentional and is most likely a package manager related.  Try removing the lock file and node modules directory and re installing.  My guess is the lock file has TS 2.3 associated with the CLI.

**Comment by filipesilva** [comment]
Closing as answered by @clydin. You can use `npm list typescript` (or `yarn list typescript`) to see what version you have installed as well if you suspect the right one isn't being installed.

**Comment by omouse** [comment]
is there a way to do this in angular-cli *as it is building* the package? can I drop in "tsc --version" right before it builds and right when it fails?

**Comment by clydin** [comment]
An `npm ls typescript` within the project root should show only one instance of typescript and it should be at the desired version (2.4.x in this case).  If the version is wrong or there are multiple instances, then either package.json doesn't have the right version; or the package manager is trying to be helpful but failing, in which case removing the lock file should fix the issue.

**Comment by omouse** [comment]
@clydin ok cool, will give that a go.

**Comment by omouse** [comment]
removing the lock file did not fix my issue.

someone else was able to replicate the issue that caused me to report this: https://github.com/swimlane/ngx-datatable/issues/927#issuecomment-329428316

What is interesting is that angular-cli had one version of typescript and seemed to ignore the version of typescript used by the project.

>+-- @ angular/cli@ 1.3.2
>| -- typescript@ 2.4.2
>-- typescript@ 2.5.2

**Comment by clydin** [comment]
@omouse , CLI version 1.3 only supports up to TS 2.4.  You'll need to use CLI 1.4 or higher to support TS 2.5.
