### ISSUE TITLE
Styling source maps not working

### ISSUE THREAD

**Issue by scooterguthrie** [angular/angular-cli#8314]
ng serve -sm -ec

Source Maps do not work in CLI version 1.5.0.... however they work fine in 1.4.7

**Comment by asteriskdothmg** [comment]
Source maps is linked only to the generated style.bundle.css

Settings for my angular-cli.json is this

![image](https://user-images.githubusercontent.com/8002580/32645573-d49b3056-c622-11e7-9dba-c2f50f7c54bb.png)

Here's what I am getting:

![image](https://user-images.githubusercontent.com/8002580/32645483-6d768b28-c622-11e7-96dc-a6fedf8449eb.png)

Here's my package

![image](https://user-images.githubusercontent.com/8002580/32645512-8d5dcb72-c622-11e7-981e-2d20f7f0d9a0.png)

**Comment by scooterguthrie** [comment]
Yes, same issue I'm getting. Thanks for taking the time to give the additional details!

**Comment by ermcgrat** [comment]
Same.

I'm using the cli version 1.5.0. 

ng new test-app
cd test-app
ng serve -sm -sc -v

Confirm no source maps generated. Older versions of the cli seem to work fine.

**Comment by asteriskdothmg** [comment]
Any update with this issue?

**Comment by ermcgrat** [comment]
Still an issue with the @angular/cli version 1.5.4

**Comment by isiegel** [comment]
Would love to get source maps working again for Angular CLI; very helpful.

**Comment by kareljan** [comment]
Same issue here version 1.5.5

**Comment by ermcgrat** [comment]
Hey, it looks like it is fixed now in version 1.6.0!!

**Comment by isiegel** [comment]
Oh sweet!

**Comment by ermcgrat** [comment]
I stand corrected. It looks like if your components have any styles defined with "styleUrls", those will be mapped. However, if you have any global "styles" defined in your angular-cli.json, those will not get mappings. 

Essentially, you can still reproduce this easily by creating a new project:

ng new --style scss test-app
cd test-app
ng serve -sm -ec -v

Now any style you define in the main styles.scss will not be mapped. However, any style you define in app.component.scss will be mapped.

**Comment by isiegel** [comment]
Oh well, usually I don't have any styles defined within components. Maybe a future release.

**Comment by rukshandangalla** [comment]
Still have the issue in `"@angular/cli": "^1.6.3"`
Any update on this?

**Comment by smlombardi** [comment]
Just updated to 1.6.4 to move our app to Angular 5.  Now source maps no longer working.

Running with `"ng serve --sourcemap --extractCss -o --hmr -e=hmr --proxy-config proxy.config.json"`

**Comment by clabough** [comment]
Wow, I spent a lot of time tracking my build issue down to [styleUrls].

This is still an issue with 1.7.3.

> ng new test
> cd test
> ng build --prod -sm

^This will complete

Put any style in the app.component.css

> ng build --prod -sm

^ this will hang at 95% emitting

This looks related to #9099

**Comment by smlombardi** [comment]
@clabough Your issue is completely different from the posted issue, which is that source maps are not linking to their scss files.

**Comment by Brookke** [comment]
I seem to be having the same issue with version 1.7.3

**Comment by ermcgrat** [comment]
Source maps still don't work correctly in version 6 of the Angular CLI.

Additionally, it looks like --extract-css has been removed as a parameter to "ng serve", and only works with "ng build"

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided. In an ng new application it looks like it's working correctly.
![image](https://user-images.githubusercontent.com/17563226/46793452-0c25aa80-cd46-11e8-8a54-107c7a1f8bb2.png)


Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
