### ISSUE TITLE
ng test fails Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by TKul6** [angular/angular-cli#8357]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Angular CLI: 1.5.0
Node: 9.0.0
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1

### Repro steps.
ng test

Omits the following error:

ERROR in ./node_modules/fs.realpath/index.js
Module not found: Error: Can't resolve 'fs' in XXXX\node_modules\fs.realpath'
 @ ./node_modules/fs.realpath/index.js 8:9-22
 @ ./node_modules/jasmine/node_modules/glob/sync.js
 @ ./node_modules/jasmine/node_modules/glob/glob.js
 @ ./node_modules/jasmine/lib/jasmine.js
 @ ./src/client/app/account/login/login.component.spec.ts
 @ ./src/client \.spec\.ts$
 @ ./src/client/test.ts

ERROR in ./node_modules/fs.realpath/old.js
Module not found: Error: Can't resolve 'fs' in 'XXXX\node_modules\fs.realpath'
 @ ./node_modules/fs.realpath/old.js 24:9-22
 @ ./node_modules/fs.realpath/index.js
 @ ./node_modules/jasmine/node_modules/glob/sync.js
 @ ./node_modules/jasmine/node_modules/glob/glob.js
 @ ./node_modules/jasmine/lib/jasmine.js
 @ ./src/client/app/account/login/login.component.spec.ts
 @ ./src/client \.spec\.ts$
 @ ./src/client/test.ts

ERROR in ./node_modules/jasmine/node_modules/glob/sync.js
Module not found: Error: Can't resolve 'fs' in 'XXXX\node_modules\jasmine\node_modules\glob'
 @ ./node_modules/jasmine/node_modules/glob/sync.js 4:9-22
 @ ./node_modules/jasmine/node_modules/glob/glob.js
 @ ./node_modules/jasmine/lib/jasmine.js
 @ ./src/client/app/account/login/login.component.spec.ts
 @ ./src/client \.spec\.ts$
 @ ./src/client/test.ts

ERROR in ./node_modules/jasmine/node_modules/glob/glob.js
Module not found: Error: Can't resolve 'fs' inXXXX\node_modules\jasmine\node_modules\glob'
 @ ./node_modules/jasmine/node_modules/glob/glob.js 43:9-22
 @ ./node_modules/jasmine/lib/jasmine.js
 @ ./src/client/app/account/login/login.component.spec.ts
 @ ./src/client \.spec\.ts$
 @ ./src/client/test.ts

ERROR in ./node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core.js
Module not found: Error: Can't resolve 'fs' in 'XXXX\node_modules\jasmine\node_modules\jasmine-core\lib'
 @ ./node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core.js 5:9-22
 @ ./node_modules/jasmine/lib/jasmine.js
 @ ./src/client/app/account/login/login.component.spec.ts
 @ ./src/client \.spec\.ts$
 @ ./src/client/test.ts

### Desired functionality.
Run the tests

### Mention any other details that might be useful.
It happened when I upgraded from cli 1.47 to 1.5.0.

Jasmine packages:
"jasmine": "^2.8.0",
"jasmine-core": "~2.5.2",
"jasmine-spec-reporter": "~3.2.0"

Karma packages:

 "karma": "~1.5.0",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.0.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.2.0",
    "karma-mocha": "^1.3.0",
    "karma-phantomjs-launcher": "^1.0.4",

**Comment by Scipionh** [comment]
Same here

**Comment by derekaug** [comment]
I've spent some time trying to debug this, and no matter what, if I update the `@angular/cli` package to `1.5.0`, this happens to me. I thought maybe it was something in the `karma.conf.js` and compared my current project's config to a new project's config and it was nearly identical. Even after matching things up as much as possible and disabling some of our plugins this still happens.

**Comment by Scipionh** [comment]
Any news on this issue ?

**Comment by lammers** [comment]
I got the same problem with the jsonpath (npm: "jsonpath": "^1.0.0") library.
ng serve and ng build --prod is working. ng test fails.

ERROR in ./node_modules/jsonpath/lib/grammar.js
Module not found: Error: Can't resolve 'fs' in '/home/m500040/gitrepo/lvm-core-components-client-lib/node_modules/jsonpath/lib'
 @ ./node_modules/jsonpath/lib/grammar.js 2:9-22
 @ ./node_modules/jsonpath/lib/parser.js
 @ ./node_modules/jsonpath/lib/index.js
 @ ./node_modules/jsonpath/index.js
 @ ./src/app/core/services/json-handler/json-handler.service.ts
 @ ./src/app/core/services/json-handler/json-handler.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

**Comment by adamlubek** [comment]
same problem here

**Comment by lammers** [comment]
for my little problem with the jsonpath library a workaround for the issue is using:
import * as jsonPath from 'jsonpath/jsonpath';
instead of
import * as jsonPath from 'jsonpath';
...
jsonPath.query(this._document, path || this.path);

**Comment by michelre** [comment]
Same problem, any news?

**Comment by Stradivario** [comment]
Hello guys same problem here any news ?

**Comment by phamhaibkit** [comment]
same problem,need someone has been resolved

**Comment by phong-kite** [comment]
I had the same error after running `ng test` that went away after removing `import 'jasmine';` from `*.spec.ts.` files.

If the editor is complaining about missing types for jasmine functions, you can fix them by including them in `tsconfig.spec.json` file:
```
{
  "compilerOptions": {
    "types": [
      "jasmine",
      ...
    ]
  },
 ...
}
```

**Comment by RadouaneRoufid** [comment]
Same problem here !! Any news ??

**Comment by kevinkuszyk** [comment]
This went away for me after updating to angular@5.1.0 & angular-cli@1.6.0 and following these steps:

```
remove node_modules
remove package-lock.json
npm cache clean -f
```

(thanks to @istiti for the [comment](https://github.com/angular/angular-cli/issues/7966#issuecomment-338186092) on #7966).

**Comment by SearchingSoul** [comment]
thanks @kevinkuszyk,  😢 didn't work for me. Still get multiple "Can't resolve 'fs' in...." with angular-cli@1.6.0.

**Comment by RadouaneRoufid** [comment]
I had a `"import 'jasmine'"` in one of my tests. Removing it solved the problem.

**Comment by derekaug** [comment]
I believe a stray `import 'jasmine';` was my issue as well.

**Comment by SearchingSoul** [comment]
I have no "import 'jasmine'" in my tests 😒.  tsconfig file is like @phong-kite's comment above.

Perhaps the issue is still open & marked as broken/urgent so probably need to wait..? 🤔

**Comment by TMaster** [comment]
After upgrading to angular `5.0.1` and the cli to `1.6` **And removing the** `import 'jasmine'` everything is working fine.

**Comment by SearchingSoul** [comment]
What worked for me is  adding the following to karma.conf.js

`
webpack: {
     node: {
        fs: 'empty',
      }
    }
`

Hope it helps someone.

**Comment by phamhaibkit** [comment]
@SearchingSoul ,I would like to sincerely thank you for your help.It's work for me

**Comment by Arnaud73** [comment]
Here, with Angular 5.2, Angular CLI 1.6.4, with no reference to `import 'jasmine'`, I had to modify the Karma configuration as described here-before.

Cleaning caches and reinstalling NPM modules did not help.

**Comment by xmeng1** [comment]
I think this is the issue of Webpack, see this issue https://github.com/webpack-contrib/css-loader/issues/447 , and @SearchingSoul 's configuration solves it.

**Comment by sbyrne-sugarcrm** [comment]
@SearchingSoul can you please clarify if there is any specific location your webpack: line goes?  I.e. should it be at the same level as port:, colors:, autoWatch:, or should it be nested inside something that hasn't been mentioned?

**Comment by DenisVuyka** [comment]
I have suddenly started getting the same issue today after removing lock files, with CLI 1.6.6. The only thing that helped me is the trick with "karma.conf.js" mentioned above:

```
webpack: { node: { fs: 'empty', } }
```

**Comment by TMaster** [comment]
I had the same error today **AGAIN**. 
The root cause was in the `beforeEach()` hook when I created the testing module without providing all the necessary mocks.

Now, I get the code shouldn't wok in this scenario, but it would be nice to have more indicative message.

**Comment by ravivit9** [comment]
@SearchingSoul the webpack: { node: { fs: 'empty', } } sort of get rid of the fs error but when I run ng test the chrome test window simply not starting.
08 03 2018 11:28:26.966:INFO [launcher]: Launching browser Chrome with unlimited concurrency
08 03 2018 11:28:26.981:INFO [launcher]: Starting browser Chrome                                                         08 03 2018 11:29:26.985:WARN [launcher]: Chrome have not captured in 60000 ms, killing.   
08 03 2018 11:29:27.092:INFO [launcher]: Trying to start Chrome again (1/2).

And the ng test will keep trying to start again and again endlessly.  Any thoughts?

**Comment by SearchingSoul** [comment]
@ravivit9 , its only supposed to take care of the 'fs' error. Other errors could be due to other reasons. Yours looks like something to do with your karma 😬.

**Comment by havart** [comment]
Hi All,
I had the same error.
The error was that I imported the wrong HttpClient **(import { HttpClient } from 'selenium-webdriver/http';)** module into the component.

**Comment by splincode** [comment]
https://github.com/amwmedia/node-plop/issues/81

**Comment by splincode** [comment]
Can't resolve 'child_process' it too have problem

```
ERROR in ./packages/cli/node_modules/external-editor/main/index.js
Module not found: Error: Can't resolve 'child_process' in '/Users/splincode/Documents/Develop/store/packages/cli/node_modules/external-editor/main'
 @ ./packages/cli/node_modules/external-editor/main/index.js 17:14-38 19:10-34
 @ ./packages/cli/node_modules/inquirer/lib/prompts/editor.js
 @ ./packages/cli/node_modules/inquirer/lib/inquirer.js
 @ ./packages/cli/node_modules/node-plop/lib/node-plop.js
 @ ./packages/cli/node_modules/node-plop/lib/index.js
 @ ./packages/cli/tests/cli.spec.ts
 @ ./packages sync \.spec\.ts$
 @ ./test.ts
```

**Comment by kblestarge** [comment]
@havart pointed me in the right direction. My errors were caused by importing the wrong EventEmitter in a component:
changed
`import { EventEmitter } from 'selenium-webdriver';`
to
`import { EventEmitter } from `@angular/core';`
and the problem is fixed :)

**Comment by StanislavChankov** [comment]
> @havart pointed me in the right direction. My errors were caused by importing the wrong EventEmitter in a component:
> changed
> `import { EventEmitter } from 'selenium-webdriver';`
> to
> `import { EventEmitter } from '@angular/core';`
> and the problem is fixed :)

This fixes the following errors:
For each node module
**ERROR in ./node_modules/...**
![image](https://user-images.githubusercontent.com/35253870/49228895-5debc800-f3ba-11e8-92e0-8c49118e75ba.png)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by Pradhan10** [comment]
> I had the same error after running `ng test` that went away after removing `import 'jasmine';` from `*.spec.ts` files.
> 
> If the editor is complaining about missing types for `jasmine` functions, you can fix that by editing `tsconfig.spec.json` file:
> 
> ```
> {
>   "compilerOptions": {
>     "types": [
>       "jasmine",
>       ...
>     ]
>   },
>  ...
> }
> ```

This worked for me
