### ISSUE TITLE
CLI 1.6.4 runtime error on bootstrap in prod bundle

### ISSUE THREAD

**Issue by dklmuc** [angular/angular-cli#9186]
### Versions
```
Angular CLI: 1.6.4
Node: 8.9.0
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.37
@angular-devkit/core: 0.0.24
@angular-devkit/schematics: 0.0.45
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.12
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
serve/build prod and open app, no errors on build and not reproducable with new empty app

### Observed behavior
Final Bundle produces:
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at e (main.5021b2f83dc3e2c2c047.bundle.js:1)
    at Object.t.exports (main.5021b2f83dc3e2c2c047.bundle.js:1)
    at e (main.5021b2f83dc3e2c2c047.bundle.js:1)
    at Object.t.exports (main.5021b2f83dc3e2c2c047.bundle.js:1)
    at e (main.5021b2f83dc3e2c2c047.bundle.js:1)
    at Object.t.exports (main.5021b2f83dc3e2c2c047.bundle.js:1)
    at e (main.5021b2f83dc3e2c2c047.bundle.js:1)
    at Object.t.exports (main.5021b2f83dc3e2c2c047.bundle.js:1)
    at e (main.5021b2f83dc3e2c2c047.bundle.js:1)
    at Object.<anonymous> (main.5021b2f83dc3e2c2c047.bundle.js:1)
```

### Desired behavior
worked in 1.6.3

### Mention any other details that might be useful (optional)
tried to track it down, but:
* `ng serve --prod` => ERROR
* `ng serve --prod --sourcemaps=true` => FINE
* `ng serve --prod --build-optimizer=false` => FINE

**Comment by clydin** [comment]
can you try with the following: `ng serve --aot --build-optimizer`?

**Comment by dklmuc** [comment]
thanks for the quick reply:
* `ng serve --aot=true --build-optimizer=true` => FINE

**Comment by Blar1975** [comment]
Same issue by: ng build --target=production --env=staging --stats-json
@angular/cli: 1.6.3
@angular/compiler-cli: 5.1.3
typescript: 2.5.3

**Comment by danielsogl** [comment]
I'm facing the same error with the latest Angular and ANgular-CLI release.  I fixed the build errors by adding --sourcemaps=true

**Comment by Blar1975** [comment]
@danielsogl 
the --sourcemaps=true isn't good idea in production

**Comment by danielsogl** [comment]
@Blar1975 my product is still in development so its "okay" at this moment.

**Comment by korzh** [comment]
We are experiencing a similar issue with the latest CLI (1.6.5) and the latest Angular core packages (5.2.1)

My app does not work if it's built with `ng build --prod`. 
Shows "Cannot find 'call' of undefined" in Developer Tools console right on webapp start. 
After few experiments we found out that the build configuration that works was:
``` 
ng build --prod --aot=false
```

I see this issue is closed already, so there must be some solution for this problem.

**Comment by benjamincombes** [comment]
Still having this problem with 1.6.5, is the supposed to be fixed?

**Comment by dklmuc** [comment]
@clydin problem is not fixed with CLI 1.6.5

```
`-- @angular/cli@1.6.5
  `-- @angular-devkit/build-optimizer@0.0.41
```

**Comment by benjamincombes** [comment]
This time it works with last updates 👍 !
