### ISSUE TITLE
"ERROR in Error: No NgModule metadata found for 'AppModule'." After Angular 5.2.1 and CLI 1.6.5 update

### ISSUE THREAD

**Issue by jtsom** [angular/angular-cli#9292]
### Versions

```
Angular CLI: 1.6.5
Node: 9.4.0
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.5
@angular/material: 5.1.0
@ngtools/json-schema: 1.1.0
typescript: 2.5.3
webpack: 3.10.0

```

### Repro steps

* Update npm packages
* Update CLI
* Start app - `ng s`

### Observed behavior
```
ERROR in Error: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver.resolve (/Users/John/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@angular/compiler/bundles/compiler.umd.js:20277:23)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/John/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@angular/compiler/bundles/compiler.umd.js:15230:60)
    at visitLazyRoute (/Users/John/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@angular/compiler/bundles/compiler.umd.js:31169:104)
    at AotCompiler.listLazyRoutes (/Users/John/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@angular/compiler/bundles/compiler.umd.js:31137:20)
    at AngularCompilerProgram.listLazyRoutes (/Users/John/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@angular/compiler-cli/src/transformers/program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/John/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/Users/John/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:248:66)
    at Promise.resolve.then.then (/Users/John/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:565:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

### Desired behavior
App run normally

### Mention any other details that might be useful (optional)
Application built and ran just fine before update.

Did try rm -rf node_modules and reinstall, no change.

**Comment by keyant** [comment]
I have faced same error. solved it: clean and reinstall global angular-cli and local  angular.

**Comment by hassaniftikhar** [comment]
@keyant 
can you put steps

**Comment by keyant** [comment]
steps: 
```
npm uninstall -g @angular/cli
npm cache verify
npm install -g @angular/cli@latest
rm -rf node_modules dist
npm install --save-dev @angular/cli@latest
npm install
```

**Comment by vupham2909** [comment]
Tried @keyant 's steps but still got the error No NgModule metadata found for 'AppModule'

**Comment by Albejr** [comment]
New projects created in this version work normally.

**Comment by ottosson** [comment]
I get this error seemingly random. Can't really see that I've changed anything and suddenly it just stops working and throws that error.

As an example: I had a branch in Visual Studio Team Services that built correctly, and when I re-queued the same build, without any changes, the build didn't work anymore...

**Comment by FA-tvonmoll** [comment]
What happens if you upgrade typescript to 2.6.0?

**Comment by x2361** [comment]
Got the same error, in my case it is caused by an import statement:
`import NgModule = core.NgModule;`

For instance following code report error when build.

`import core = require("@angular/core");`
`import NgModule = core.NgModule;`
`@NgModule( {....})`
`export class AppModule {}`

And the error is gone if rewrite the code like below:
`import core = require("@angular/core");`
`@core.NgModule( {....})`
`export class AppModule {}`

**Comment by Albejr** [comment]
same error
```
Angular CLI: 1.6.5
Node: 8.9.4
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.5
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.6.2
webpack: 3.10.0
```

**Comment by Albejr** [comment]
Unbelievable! It works after just editing the "app.component.ts" file.

![cli](https://user-images.githubusercontent.com/24717256/35341624-38a9c24a-010d-11e8-9183-0aaa89082a41.gif)

**Comment by hansl** [comment]
Hi @jtsom and @Albejr,

Could you provide a project we can use to reproduce this? A github repo would be great.

**Comment by Albejr** [comment]
It is fixed in version 1.6.6

**Comment by ottosson** [comment]
@Albejr which pr covers this problem?

https://github.com/angular/angular-cli/releases/tag/v1.6.6
* @angular/cli: add karma-cli as dependency when ejecting (f17c2b3)
* @angular/cli: allow colon separated schematic name in generate (f9a9d75)
* @angular/cli: allow for schema-less schematics to be generated (d4dc2e3)
* @angular/cli: delete node_modules on eject e2e (5c00e1f)
* @angular/cli: eject now remove all hardcoded paths (53e84fe), closes #9335
* @angular/cli: exclude nodejs built-ins from process.cwd() resolve (bf87508)
* @angular/cli: maintain autoprefixer backward compatibility (0f82564)
* @angular/cli: only force CommonJS if module kind is ES2015 (369f361)
* @angular/cli: replaced bullet character due to unwanted beeping sounds on windows systems (38db84c)

**Comment by bytech-ca** [comment]
Had the same experience earlier as Albejr, but with forEach. TS would fail to compile the code saying something like 'foreach is not a method of <object>'... but if I left the hang compiler stuck, and changed any TS file, the compile after the failed one would work.

In other words, I could never run the program on the first compile. I got around it in other ways (sounds like foreach can have unpredictable results, so TS doesn't like it). The compiler behaviour made troubleshooting a problem more difficult...

**Comment by captivea-yho** [comment]
@x2361
You are incredible, it works with your fix.

**Comment by brendanairvuz** [comment]
I still have this problem with angular 5.2.4 and cli 1.6.7. I did npm cache clean --force, rm -rf node modules and package lock, remove webpack from package.json, fresh npm install and build. Still the problem persists.

**Comment by vapits** [comment]
Update typescript of project to 2.6.2 solved it for us.

`npm install --save-dev typescript@2.6.2`.

Took sooooo much time to figure out as the solution of deleting cli and cache and reinstalling them was working only partially.

**Comment by tingtingli911** [comment]
@vapits this solved my problem,  excellent !

**Comment by hnmmallesh** [comment]
OMG i can't believe @Albejr solution worked for me.

**Comment by csrssrinivas** [comment]
I finally resolved this issue. Resolution below. :-)

Update the Angular CLI version to latest – as of today it’s 1.7.4

How to check the version of @angular/cli
ng --version
Go to the folder and type the following commands to update CLI.
npm remove @angular/cli
npm install —save-dev @angular/cli@latest
Make sure that the Webpack version is 3.11.0
How to check the version of Webpack
npm list webpack
How to update webpack
npm remove webpack
npm install webpack@3.11.0

**Comment by achmedzhanov** [comment]
I have same problem ...

I solved this problem only when remove globaly installed webpack.

`npm uninstall -g webpack`

**Comment by Amryn** [comment]
I had the same problem and the problem was that I imported a module that was already exported via another imported module, like this (where ModulaASub is exported by ModuleA already):

```
imports: [
        BrowserModule,
        ModuleA,
        ModuleASub
    ],
```

It's strange in how many different cases this error message appears. More detailed error messages would be highly appreciated.

**Comment by pumpersonda** [comment]
I had the same problem, but my problem was the name of the module when I was trying to load the module with _lazy load._ The first letter was in lowercase.

`path/to/projects.module#projectsModule`

so I changed it like this and it works:
`path/to/projects.module#ProjectsModule`

**Comment by czetsuya** [comment]
In my case, what caused the problem was a wrongly defined module. I created a SecuredModule and lazy load that module. But I forgot that when you create a module in cli, it will also append the Module word. But sadly this error does not popup in 1.7.x version, instead I have to downgrade to 1.6.x to be able to figure out the problem.

**Comment by aelkoussy** [comment]
In my case, solved by deleting the node_modules folder , then running:
`npm i`

**Comment by huyinghuan** [comment]
I have the same issue when i update angular 2.x -> 6.x . I delete the package-lock.json and reinstall node_modules,  it work fine now

**Comment by xclayl** [comment]
For me, I had an APP_INITIALIZER function/factory where the function was not "export"ed.   Once I exported the function, it started working again.

**Comment by sri15941** [comment]
Hi
   I have faced same error please solve it

compiler.js:11792 Uncaught Error: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.NgModuleResolver.resolve (compiler.js:11792)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:10429)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (compiler.js:22567)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:22548)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync (compiler.js:22508)
    at CompilerImpl.push../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:143)
    at PlatformRef.push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule (core.js:4285)
    at Object../src/app/app.module.ts (app.module.ts:141)
    at __webpack_require__ (bootstrap:76)
    at Object../src/main.ts (environment.ts:15)

**Comment by JackNguyen-zz** [comment]
sudo npm install typescript@'>=2.4.2 <2.7.0'
Worked

**Comment by JackHitcher** [comment]
@Albejr your solution worked for me as well.

Even programming languages works with horoscope magics!!!!

**Comment by madbonez** [comment]
@Albejr wth?? how i can llive now with this... helps me too! but its looks bad

**Comment by madbonez** [comment]
huge black box and no 'eject' available.. dance with a red eyes  and daemons. sorry i am stucked for a while)

**Comment by ramvirsingh** [comment]
can you post your 'tsconfig.app.json'

**Comment by benwinding** [comment]
`ng update @angular/cli`

Worked for me

**Comment by michahell** [comment]
After having tried everything related to NPM, I got past this problem by `not declaring platformBrowserDynamic` as mentioned here:
https://stackoverflow.com/questions/39685179/angular-2-no-ngmodule-metadata-found

which to me, totally makes zero sense  😬 👍

**Comment by raphaelcrv** [comment]
> Unbelievable! It works after just editing any ".ts" file.
> 
> ![cli](https://user-images.githubusercontent.com/24717256/35341624-38a9c24a-010d-11e8-9183-0aaa89082a41.gif)

Same problem as @Albejr tks for the temp workaround 

This thinks make my job a special job, it's pretty like y car not start for a engine problem and y open and close the door and the car start work again. LOL

**Comment by zzmmbb** [comment]
> 难以置信的！只需编辑任何“.ts”文件即可。
> 
> ![CLI](https://user-images.githubusercontent.com/24717256/35341624-38a9c24a-010d-11e8-9183-0aaa89082a41.gif)

me too

**Comment by westonpace** [comment]
I ran into this exact error.  One of the angular modules I was importing (my own custom module) was being built with ng-packagr and was not exporting all of its services in `public_api.ts`.  After adding those services to `public_api.ts` and reinstalling the module this error went away.

**Comment by qmphan** [comment]
I upgraded my project to Angular7 yesterday and have spent almost a day trying all possible solution but nothing works. I keep seeing thie message *ERROR in No NgModule metadata found for 'AppModule'.*

The error happens after the success compilation of all assets. Changes made to tsconfig.json doesn't seem to affect the result in any way.

```
ng build --project=admin --no-progress

Date: 2018-10-31T09:01:37.961Z
Hash: c852709f74070d0f5f6c
Time: 40952ms
chunk {main} main.js, main.js.map (main) 643 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 105 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 232 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.62 MB [initial] [rendered]

ERROR in No NgModule metadata found for 'AppModule'.
```

**Comment by alex7egli** [comment]
Just got this error. I upgraded angular-cli, core, and material to v7 to try out a new feature. Then I needed to switch to a branch that was still on v6 of everything. I did the following:

1. deleted node_modules
2. switched to the branch
3. uninstalled angular-cli globally
4. install angular-cli at the same version that branch had set in package.json globally
5. ran ng build
Got the error "ERROR in No NgModule metadata found for 'AppModule'.". Editing a ts file does not fix it. I don't understand, none of my code has changed, how can the cli just randomly stop working?

**Comment by Surya4DevOps** [comment]
> Unbelievable! It works after just editing any ".ts" file.
> 
> ![cli](https://user-images.githubusercontent.com/24717256/35341624-38a9c24a-010d-11e8-9183-0aaa89082a41.gif)

This worked for me, Thanks a ton Albejr, you saved my day.

**Comment by aboudard** [comment]
Hello !
I had the same issue, but it was related to a tsconfig.json.
I'm testing cypress, and I did put a config in the root tsconfig file :

"include": ["./node_modules/cypress"]

I removed it, following cypress recommendations, havint a file in the dedicated /cypress folder with that kind of content :

{
	"extends": "../tsconfig.json",
	"include": [
		"integration/*.ts",
		"support/*.ts",
		"../node_modules/cypress"
	]
}

And now it does compile !
Hope that can help anyone.

**Comment by moises291202** [comment]
> Unbelievable! It works after just editing any ".ts" file.
> 
> ![cli](https://user-images.githubusercontent.com/24717256/35341624-38a9c24a-010d-11e8-9183-0aaa89082a41.gif)

@Albejr thank you very much bro!
