### ISSUE TITLE
Cannot read property NullLogger or dasherize of undefined

### ISSUE THREAD

**Issue by dwilson14** [angular/angular-cli#9662]
### Versions
```
<!--
Output from: `ng --version`.
@angular/animations: 5.2.5
@angular/cli: 1.6.1
@angular/compiler-cli: 5.2.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.17
typescript: 2.7.1
webpack-concat-plugin: 2.4.2
webpack-dev-server: 2.7.1
webpack: 3.10.0
node: 8.6.0
npm: 5.3.0
Windows10
```

### Repro steps
using ng g c <new component name>
get error first 'Cannot read property 'NullLogger' of undefined. and I have two versions of webpack, both the same (3.10.0) one under the CLI and one not. When I address that issue I get ERROR: cannot read property 'dasherize' of undefined.

### Observed behavior
```
    at SchematicEngine.createContext (C:\Code\Repos\Physician Links\Web\PhysicianLinks.Application\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:75:38)
    at SchematicImpl.call (C:\Code\Repos\Physician Links\Web\PhysicianLinks.Application\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\schematic.js:35:38)
    at Promise (C:\Code\Repos\Physician Links\Web\PhysicianLinks.Application\node_modules\@angular\cli\tasks\schematic-run.js:73:23)
    at Promise (<anonymous>)
    at Class.run (C:\Code\Repos\Physician Links\Web\PhysicianLinks.Application\node_modules\@angular\cli\tasks\schematic-run.js:72:16)
    at Class.run (C:\Code\Repos\Physician Links\Web\PhysicianLinks.Application\node_modules\@angular\cli\commands\generate.js:161:33)
    at resolve (C:\Code\Repos\Physician Links\Web\PhysicianLinks.Application\node_modules\@angular\cli\ember-cli\lib\models\command.js:261:20)
    at Promise (<anonymous>)
    at Class.validateAndRun (C:\Code\Repos\Physician Links\Web\PhysicianLinks.Application\node_modules\@angular\cli\ember-cli\lib\models\command.js:240:12)
    at Promise.resolve.then.then (C:\Code\Repos\Physician Links\Web\PhysicianLinks.Application\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:140:24)
```

### Desired behavior
would like to be able to create component using cli

**Comment by dwilson14** [comment]
resolved that issue with a lot of uninstalling and re-installing and only issue remaining is when running ng generate component get error 'cannot read property 'dasherize' of undefined. Any direction would be helpful; there seems to be nothing about this out on stack

**Comment by Jackysi** [comment]
How did you fix this? i have same issue and tried to reinstall stuff 2x and still same issue...  
``
Error: Cannot read property 'dasherize' of undefined

**Comment by dwilson14** [comment]
Sorry Jackysi,  I inadvertantly closed this but did not resolve the issue.

**Comment by ekstremedia** [comment]
I have the same issue: 

Angular CLI: 1.7.0
Node: 8.9.0
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.2.1
@angular/cli: 1.7.0
@angular/language-service: 4.4.6
@angular/material: 5.2.1
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.46
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
@schematics/schematics: 0.0.13
typescript: 2.7.2
webpack: 3.11.0

$ ng g c test
Error: Cannot read property 'dasherize' of undefined
Cannot read property 'dasherize' of undefined

**Comment by ManuBermu** [comment]
I have the same problema. I try to reinstall and and still same issue.

**Comment by Jackysi** [comment]
I solved it yesterday by running:
`npm install --save @angular/cli@latest`

**Comment by bulkasamurai** [comment]
I have the same issue
Angular CLI: 1.7.0
Node: 8.9.4
Angular: 5.2.5
@angular/cli: 1.7.0

**Comment by jainmitesh09** [comment]
I am running into the same issue.

First, to get ride of below error,  I changed `@angular-devkit/core` from `0.0.27` to `0.0.29`.

```
core_1.PriorityQueue is not a constructor
TypeError: core_1.PriorityQueue is not a constructor
    at new TaskScheduler (/work/tionodeweb/node_modules/@angular-devkit/schematics/src/engine/task.js:20:23)
    at SchematicEngine.createContext (/work/tionodeweb/node_modules/@angular-devkit/schematics/src/engine/engine.js:102:31)
    at SchematicImpl.call (/work/tionodeweb/node_modules/@angular-devkit/schematics/src/engine/schematic.js:35:38)
    at Promise (/work/tionodeweb/node_modules/@angular/cli/tasks/schematic-run.js:80:23)
    at Class.run (/work/tionodeweb/node_modules/@angular/cli/tasks/schematic-run.js:79:16)
    at Class.run (/work/tionodeweb/node_modules/@angular/cli/commands/generate.js:173:33)
    at resolve (/work/tionodeweb/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at Class.validateAndRun (/work/tionodeweb/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/work/tionodeweb/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)
```

I resolved that but now have below error

```
Error: Cannot read property 'dasherize' of undefined
Cannot read property 'dasherize' of undefined
```

I tried to update angular cli to latest `1.7.0` but it doesnt help.

**Comment by OrganicCat** [comment]
I'm getting the same thing right now. 

```
(ran this) ng g c cats/component-palico

Error: Cannot read property 'dasherize' of undefined
```

**Comment by JakobSegerslatt** [comment]
I fixed it by updating;

@angular-devkit/core 
from "0.0.23" to "0.4.2"

@angular-devkit/schematics
from"0.0.42" to "0.4.2"

**Comment by ekstremedia** [comment]
When its like @JakobSegerslatt says in package.json, 
```
  "dependencies": {
    "@angular-devkit/core": "^0.4.2",
    "@angular-devkit/schematics": "^0.4.2",
}
```
it now works again. Thanks.

**Comment by ngolforoushan** [comment]
npm install --save @angular/cli@latest

Fixed the issue. Thanks Jackysi!

**Comment by jai-rathore** [comment]
npm uninstall -g @angular/cli
npm install -g @angular/cli@latest
npm install --save @angular/cli@latest

**Comment by cmckni3** [comment]
I had to go back to ng cli version 1.3.2 because I wanted to generate an Angular v4 project.

**Comment by Prashanth-Thomas** [comment]
I had a similar issue, i solved it by adding the following dependency

`npm install @angular-devkit/core@0.0.29`

the version number may vary, but i assume it should be enough.

**Comment by bluelightning2k** [comment]
This did not fix the issue for me. Seen so many errors related to Angular different package versions - it's literally every couple of weeks for every Angular user.

These issue like halve the satisfaction of the average user.

**Comment by Villanuevand** [comment]
@jai-rathore  this work fine for me...

thanks a lot.

**Comment by tranthaihoang** [comment]
npm i -D @angular-devkit/core@0.4.2
This work for me! tks JakobSegerslatt

**Comment by NabinKhatiwada** [comment]
thanks @ekstremedia ..
npm i --save-dev @angular-devkit/core@latest
npm i --save-dev @angular-devkit/schematics@latest

**Comment by oushuintern** [comment]
tks NabinKhatiwada,these work fine for me

**Comment by Reactman** [comment]
thanks @JakobSegerslatt , it work for me!

**Comment by chrismoutray** [comment]
thanks @NabinKhatiwada , installing latest angular-devkit/core worked for me

**Comment by ppenan** [comment]
I got the same error with this version con agular/cli, but I need this version, and I don´t new the latest version of cli. How to fix this, any ideas without upgrading the cli verison?

@angular/cli: 1.4.7
node: 8.11.2
os: win32 x64

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
