### ISSUE TITLE
[Bug] cli needs to be reloaded when a lazy loaded module is added in routes

### ISSUE THREAD

**Issue by michaeljota** [angular/angular-cli#9825]
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.1
Node: 8.9.4
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

* Run `ng serve` to start the application bundle
* Create a new lazy module
* Modify the routes in the main module to do lazy load of the new module

### Observed behavior
```
null: ERROR
null: Error: Uncaught (in promise): TypeError: __webpack_require__.e is not a function
message: "Uncaught (in promise): TypeError: __webpack_require__.e is not a function
TypeError: __webpack_require__.e is not a function
    at webpackAsyncContext (eval at ./src/$$_lazy_route_resource lazy recursive (http://localhost:4200/main.bundle.js:13:1), <anonymous>:11:29)
    at SystemJsNgModuleLoader.loadAndCompile (webpack-internal:///./node_modules/@angular/core/esm5/core.js:6774:82)
    at SystemJsNgModuleLoader.load (webpack-internal:///./node_modules/@angular/core/esm5/core.js:6758:60)
    at RouterConfigLoader.loadModuleFactory (webpack-internal:///./node_modules/@angular/router/esm5/router.js:4626:122)
    at RouterConfigLoader.load (webpack-internal:///./node_modules/@angular/router/esm5/router.js:4606:52)
    at MergeMapSubscriber.eval [as project] (webpack-internal:///./node_modules/@angular/router/esm5/router.js:2098:115)
    at MergeMapSubscriber._tryNext (webpack-internal:///./node_modules/rxjs/_esm5/operators/mergeMap.js:133:27)
    at MergeMapSubscriber._next (webpack-internal:///./node_modules/rxjs/_esm5/operators/mergeMap.js:123:18)
    at MergeMapSubscriber.Subscriber.next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:97:18)
    at ScalarObservable._subscribe (webpack-internal:///./node_modules/rxjs/_esm5/observable/ScalarObservable.js:53:24)"
promise: ZoneAwarePromise {__zone_symbol__state: 0, __zone_symbol__value: TypeError: __webpack_require__.e is not a function…}
rejection: TypeError: __webpack_require__.e is not a function
stack: "Error: Uncaught (in promise): TypeError: __webpack_require__.e is not a function
TypeError: __webpack_require__.e is not a function
    at webpackAsyncContext (eval at ./src/$$_lazy_route_resource lazy recursive (http://localhost:4200/main.bundle.js:13:1), <anonymous>:11:29)
    at SystemJsNgModuleLoader.loadAndCompile (webpack-internal:///./node_modules/@angular/core/esm5/core.js:6774:82)
    at SystemJsNgModuleLoader.load (webpack-internal:///./node_modules/@angular/core/esm5/core.js:6758:60)
    at RouterConfigLoader.loadModuleFactory (webpack-internal:///./node_modules/@angular/router/esm5/router.js:4626:122)
    at RouterConfigLoader.load (webpack-internal:///./node_modules/@angular/router/esm5/router.js:4606:52)
    at MergeMapSubscriber.eval [as project] (webpack-internal:///./node_modules/@angular/router/esm5/router.js:2098:115)
    at MergeMapSubscriber._tryNext (webpack-internal:///./node_modules/rxjs/_esm5/operators/mergeMap.js:133:27)
    at MergeMapSubscriber._next (webpack-internal:///./node_modules/rxjs/_esm5/operators/mergeMap.js:123:18)
    at MergeMapSubscriber.Subscriber.next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:97:18)
    at ScalarObservable._subscribe (webpack-internal:///./node_modules/rxjs/_esm5/observable/ScalarObservable.js:53:24)
    at resolvePromise (webpack-internal:///./node_modules/zone.js/dist/zone.js:809:31)
    at resolvePromise (webpack-internal:///./node_modules/zone.js/dist/zone.js:775:17)
    at eval (webpack-internal:///./node_modules/zone.js/dist/zone.js:858:17)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:421:31)
    at Object.onInvokeTask (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4956:33)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:420:36)
    at Zone.runTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:188:47)
    at drainMicroTaskQueue (webpack-internal:///./node_modules/zone.js/dist/zone.js:595:35)
    at <anonymous>"
task: ZoneTask {_zone: Zone, runCount: 0, _zoneDelegates: null, …}
zone: Zone {_properties: Object, _parent: Zone, _name: "angular", …}
__proto__: Object {constructor: , name: "Error", message: "", …}
```

### Desired behavior

There should be no errors.

### Mention any other details that might be useful (optional)
Just reloading the serving makes the lazy loaded module to work.

**Comment by seaBubble** [comment]
I have the same issue

**Comment by FirassKoubaa** [comment]
+1

**Comment by emanuelet** [comment]
+1

**Comment by ironstine** [comment]
+1 

Confirming that restarting 'ng serve' fixes the issue.

**Comment by michaeljota** [comment]
Update: This also happen when the lazy module throws an error in the first build.

**Comment by escorter** [comment]
+1

**Comment by matiasfessia** [comment]
+1 same problem here!

**Comment by FARHANE** [comment]
+1

**Comment by hermbit** [comment]
+1 same issue, restarting fixes it for me too

**Comment by AianaM** [comment]
+1

**Comment by denyo** [comment]
Duplicate of #9488.

**Comment by lowbit** [comment]
+1

**Comment by lishichao1002** [comment]
+1

**Comment by danielleburgess** [comment]
+1

**Comment by denyo** [comment]
Possibly duplicate of #9488.

**Comment by lazarohcm** [comment]
+1

**Comment by gsbraga** [comment]
+1

**Comment by avhincu** [comment]
+1

**Comment by stanleyeosakul** [comment]
+1

**Comment by alexsantosfilho** [comment]
+1

**Comment by krunal-thakur** [comment]
+1

**Comment by Mani2693** [comment]
Same issue here below is the error message I am getting 


![typeerror](https://user-images.githubusercontent.com/11607412/37242342-f01cc30c-248d-11e8-98e7-1a5dade21eb3.PNG)

**Comment by dkarski** [comment]
I recomended change
`{
    path: 'user-panel',
    loadChildren: './user-panel/user-panel.module#UserPanelModule',
  },`

to 

`{
    path: 'user-panel',
    loadChildren: () => UserPanelModule,
  },`

**Comment by michaeljota** [comment]
@dkarski does that work with AoT?

**Comment by hermbit** [comment]
The above solution from @dkarski fixed this for me.

However, @michaeljota it doesnt work with AoT.

**Comment by michaeljota** [comment]
@karol-depka, that's not a solution, it's just a work around. The only real solution is to reload the CLI.

You only can use the string version for AoT. So if you aren't using AoT for anything, sure, you can do this. But, still, it is recommended to use the string version.

**Comment by hermbit** [comment]
For some reason, the string version stopped working for me even after reloading the CLI. This happened after I updated to @angular/cli@1.7.3 from v1.6...

**Comment by michaeljota** [comment]
@hermbit Try to load the string from root. 
`loadChildren: 'app/feature/feature.module#FeatureModule'`

Sometimes this works, something the other works. IDKW.

**Comment by pf-guilhermechiara** [comment]
For me, that's not working either (even after restarting the CLI).

**Comment by ravindranath143** [comment]
downgrade your @angular/cli to '1.6.8' and load your module like this 
loadChildren: 'app/modules/fleet/fleet.module#FleetModule'
I am trying fix this issue from last two days and finally cli version trick worked for me

**Comment by lovesora** [comment]
updated to @angular/cli@1.7.3 and restart `ng serve`, it works.

**Comment by puttputt** [comment]
Using full path:
 loadChildren: 'app/registration/registration.module#RegistrationModule'

and ng serve --aot resolves this issue temporarily for me.

**Comment by NapkinHD** [comment]
Same Problem with Angular 5.2.8 and CLI v1.7.3
Resolved that Issue by downgrading the CLI to v1.6.8. 
Alternate Workaround is using `ng serve --aot` suggested by @stanleyeosakul

**Comment by michaeljota** [comment]
Reloading the CLI didn't work?

**Comment by NapkinHD** [comment]
Unfortunately it did not resolve the issue (Including re-install all node_modules and clearing the npm cache). I'll wait until the bug is fixed and then update my CLI.

**Comment by cecotw** [comment]
Either 1.7.3 + ng serve --aot or
1.6.8 + ng serve 
as temp fixes worked. I had to downgrade to 5.2.7 due to the issue 5.2.8 has with oidc-client.

**Comment by MonirTuhin** [comment]
restarting the server with ng-serve fixes my problem too.

**Comment by mingtaocao** [comment]
+1

**Comment by mingtaocao** [comment]
@NapkinHD +1

**Comment by asponda** [comment]
Same problem here using Angular CLI 1.7.2. 

I'm using ng serve --aot to fixes and now worked.

**Comment by embryologist** [comment]
same issue here, eveing with using `AoT`

**Comment by alan994** [comment]
+1

**Comment by Sakuni** [comment]
Had the same issue with 

Angular CLI: 1.7.3
Node: 8.10.0
OS: linux x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

and reloading the serving made the lazy loaded modules to work.

**Comment by FARHANE** [comment]
For all person how did ng serve --aot 
did ng build (npm run build) worked for you ?

**Comment by FARHANE** [comment]
For me I was making import module for my leazy loded module so that was wrong.
I delete all this declarations but I had webpack error for my own created library something like webpack error e._ is not function ( I don't remember the exactly the error).
So i make ng --eject and all think work perfectly, but you must do npm run build to create production js code.

**Comment by netlander** [comment]
+1

**Comment by vitherain** [comment]
Downgrading to @angular/cli v 1.6.8 worked for me too.

**Comment by karthikchintala64** [comment]
Above solution from @Dercetech to use a const worked for me. Thanks @Dercetech !

**Comment by EcoFreak** [comment]
I'm runing @angular/cli v 1.7.3 and @Dercetech's solution didn't work.
Any solutions?

**Comment by michaeljota** [comment]
Have you try to turn it off and on again?

**Comment by Paweleksltzn** [comment]
Exporting the const with childrenLoad saved my life

**Comment by splincode** [comment]
Problem reproduce: https://stackblitz.com/edit/angular-n6pt2q

**Comment by trsh** [comment]
Restarting CLI solved issue

**Comment by Bryght7** [comment]
Relaunching my `ng serve` command did solve this error. Thanks.

**Comment by gustavogsimas** [comment]
Relaunching ng serve also solved this error.

`--aot` raised a bunch of errors for me.

**Comment by nabiinChhetri** [comment]
It was working fine till morning Same error occured ,  relaunching `ng serve` didnt solve  this error, 
Any one with solution ?

**Comment by arshu16** [comment]
@dkarski 's solution worked for me. Import your module 
``` import { Awesome } from './awesome/awesome.module';```
 and do ``` loadChildren: () => Awesome```

**Comment by fxck** [comment]
I'd be afraid that would include it in the main bundle, rendering lazy loading useless. Not sure though.

**Comment by michaeljota** [comment]
Well, that too. But this is ineffective with AoT as well.

**Comment by arshu16** [comment]
@fxck Well, Now that I think of it, you might be correct. Let's hope this is fixed soon.

**Comment by EcoFreak** [comment]
Hello guys, managed to fix my problem.
I was importing the ChildModule with the routes after the AppRoutingModule in AppModule.
Just by swapping the order everything worked nicely.

Hope it helps ;)

**Comment by michaeljota** [comment]
@EcoFreak what do you mean with _importing the ChildModule_ after the AppRoutingModule? Can you provide the code example of before and after?

**Comment by Meziano** [comment]
I had the same issue with:
`Angular CLI: 1.7.4
Node: 9.5.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/animation: 4.0.0-beta.8
@angular/cdk: 5.2.4
@angular/cli: 1.7.4
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
`
A down-grad to angular-cli 1.7.3 solved this problem.

**Comment by EcoFreak** [comment]
@michaeljota Even when downgrading the version, the problem remained in my case.
The problem in my case was the order of imports of the main module.
The `AppRoutingModule` defines the main routes and loads the remaining with `loadChildren`.
The `EquipmentsModule` defined extra routes and it's imported by `AppRoutingModule`.
**Before:**
 _`(AppRoutingModule` was imported before `EquipmentsModule`)_

```
@NgModule({
  declarations: [
    AppComponent,
    LocationsComponent,
  ],
  imports: [
    HttpClientModule,
    BrowserModule,
    FormsModule,
    LayoutModule,
    AppRoutingModule,
    EquipmentsModule, //imported after
  ],
```
**After:**
 _`(AppRoutingModule` was imported after `EquipmentsModule`)_

```
@NgModule({
  declarations: [
    AppComponent,
    LocationsComponent,
  ],
  imports: [
    HttpClientModule,
    BrowserModule,
    FormsModule,
    LayoutModule,
    EquipmentsModule, //imported before
    AppRoutingModule,
  ],
```

Hope it helps!

**Comment by michaeljota** [comment]
@EcoFreak if you are using Lazy Loading you should never import the lazy module in your application, neither in AppModule, nor AppRoutingModule. You should only reference it by a string that points to the module class of that Lazy Module.

**Comment by qpdian** [comment]
I used @angular/cli@next :
npm uninstall -g @angular/cli
npm install -g @angular/cli@next

**Comment by ptomaszi** [comment]
+1

**Comment by Antoniossss** [comment]
+1 
Using ng serve --aot fixes the issue. IDK is it a fix or rather workaround

**Comment by EddWills95** [comment]
I've had this problem and my solution was to change the CLI version back to `1.6.5` which meant I could still use the `loadChildren: 'modulePath#moduleName'`.

**Comment by user3323** [comment]
+1

**Comment by ronaldohoch** [comment]
+1

Angular CLI: 1.7.3
Node: 6.11.4
OS: win32 x64
Angular: 5.2.0

**Comment by Ismaestro** [comment]
After downgrading to 1.7.3 everything works again.[Here](https://angularexampleapp.com/).

```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.3
Node: 8.9.1
OS: darwin x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/flex-layout: 5.0.0-beta.14
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

**Comment by jdk339** [comment]
@EcoFreak As annoying and weird as it is, your solution solved the error for me! Thanks!

@michaeljota That makes sense since you don't get the benefits of lazy loading if you're importing the module in your app/app routing module, but then I have a question. If I want to have a component in the lazily-loaded module with a directive, eg. `[siteTitle]`, how am I supposed to achieve that?

Concrete Example:
Let's say I have `AuthModule` with a component `nav-bar` and I want to include it in my app like so: `<app-nav-bar [siteTitle]="My Site"> ... <app-nav-bar>`. How can I achieve that while following Angular's rules?

**Comment by michaeljota** [comment]
@jdk339 
You would probably need a `Layout` or `Shell` component as a root view for your lazy modules, and change the state of the title with a service or using `ngrx`.

**Comment by duynb** [comment]
I'm now in **Angular CLI: 6.0.0-rc.5**

And it still error  (This error not happended in my Angular 4 project):
Code:
`{ path: 'dashboard', loadChildren: 'app/dashboard/dashboard.module#DashboardModule' },`

ng serve => `ERROR in Could not resolve module app/dashboard/dashboard.module relative to /var/www/html/test/src/app/app.routing.ts`

But if code:
{ path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardModule' },
ng serve => success
but it error in browser
`ERROR RangeError: Maximum call stack size exceeded`

If I use const as Dercetech said for both path above
ng serve => success
but it error in browser
`Error: Cannot find module "app/dashboard/dashboard.module"`

**Comment by Kalpesh300** [comment]
I was facing same issue. I am using latest version of Angular-CLI. I was facing issue because I forgot to add pathMatch: 'full' to my lazy loading module's route.

**Comment by michaeljota** [comment]
@duynb Can you check if your `ERROR RangeError: Maximum call stack size exceeded` is not about recursive components? I have face that kind of errors when a component call itself in an infinite loop. If not, just check for infinite loops in general.

**Comment by duynb** [comment]
I think that my code is not `recursive components`
Just a router config and a module
I simplified the route to be like this, and it still happen:
```
const appRoutes: Routes =
[
  { path: '', loadChildren: './dashboard/dashboard.module#DashboardModule' },
];
```

Here is the loop:
```
platform-browser.js:224 Router Event: RouteConfigLoadStart
platform-browser.js:219 RouteConfigLoadStart(path: )
platform-browser.js:219 RouteConfigLoadStart {route: {…}}
platform-browser.js:224 Router Event: RouteConfigLoadEnd
platform-browser.js:219 RouteConfigLoadEnd(path: )
platform-browser.js:219 RouteConfigLoadEnd {route: {…}}
platform-browser.js:224 Router Event: RouteConfigLoadStart
```

**Comment by czetsuya** [comment]
Just thought it might help. In my case, what caused the problem was a wrongly defined module. I created a SecuredModule and lazy load that module. But I forgot that when you create a module in cli, it will also append the Module word. But sadly this error does not popup in 1.7.x version, instead I have to downgrade to 1.6.x to be able to figure out the problem.

**Comment by michaeljota** [comment]
Try to load the module in the old way, import it in AppModule, and load the component from you AppRoutingModule.

**Comment by sluglit** [comment]
I had the same problem then stumbled across this article: https://angular.io/guide/router#module-import-order-matters.

Also look at the example (links at the top of the article) it shows different techniques to import Modules.
E.g.:
HerosModule is loaded eagerly
CrisisCenterModule is loaded lazily

To solve the problem:

I upgraded @angular/cli to version 6.0.1 (not 100% sure if this made any difference)
I moved the order of my imports around. (Move the *RoutingModule to the bottom of the list of imports)
I also removed the lazy-loaded modules from the NgModule.imports property list
Using an absolute path value for 'loadChildren' still works for me:
loadChildren: 'app/dashboard/dashboard.module#DashboardModule'

**Comment by Naikno** [comment]
@dkarski  saved my day! thank you!

**Comment by dvhuy** [comment]
Same problem with above,
Im working witn ng/cli version 6.0.1

Shutdown and run `ng serve` again, it works, either for `--aot` mode

**Comment by michaeljota** [comment]
@sluglit do you have a working public repo of this example? If not, can you do one?

That would be very helpful. Thanks.

**Comment by sluglit** [comment]
There is already a working example https://angular.io/guide/router
Example link: https://angular.io/generated/zips/router/router.zip

**Comment by michaeljota** [comment]
Does this works well when you add a new module to the router module? Because, that's what this issue is about.

**Comment by sluglit** [comment]
@michaeljota 

- Eager Loaded Routing Modules: 
The modules must be defined in the NgModule.imports before your router module.

- Lazy Loaded Routing Modules:
Remove the Lazy loaded modules from NgModule.imports

Either way, just make sure that your RoutingModule is last in the list of NgModule.imports
E.g.: 
imports: [
  BrowserModule,
  FormsModule,
  HeroesModule,
  AppRoutingModule
],

**Comment by michaeljota** [comment]
I mean, I have it this way, still, when I'm running `ng serve` and add a new module, to be loaded as a lazy module, the error is still reproducible.

**Comment by MohitKS5** [comment]
In my case too, --aot solves the problem but only in development mode. When I build it ng build --prod --aot the app gives same error as 1st post of issue.

**Comment by kublaios** [comment]
As mentioned above, if you ran `ng serve` and the build failed but the task is still running, you fixed the error and it compiled successfully, this error still may persist so make sure you cancel the running `ng serve` task and run it again.

I am looking forward for more improved error messages from the CLI, like "Hey, your app has an error and I am not talking about it a single bit, go figure out or go mad."

**Comment by stefland** [comment]
@dkarski I've : 

> ERROR in Error during template compile of 'RoutingModule'
> Function expressions are not supported in decorators in 'ɵ0'
> 'ɵ0' contains the error at app/routing.module.ts(15,29)
>  Consider changing the function expression into an exported function.

**Comment by stefland** [comment]
Nerver mind. I make a `ng serve` and it's okay. 
Thx !

**Comment by lazarohcm** [comment]
`ng serve --aot` was not working for me on **Angular CLI: 6.0.3** (it was working fine on previous versions).
I Tried the following code _(going up one path)_ and it is workign now _(AOT only)_: 
`{ path: 'home', loadChildren: './../app/home/home.module#HomeModule'},`

**Comment by JoungPark** [comment]
I fixed it with just restarting.

**Comment by cnscorpions** [comment]
it works after restart by `ng serve -o`  lol

**Comment by abdulkareemnalband** [comment]
I'm also facing this issue with non prod non aot build, but with relative path is provided using `tsconfig path`
```
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cdk                      6.1.0
@angular/material                 6.1.0
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.2.0
typescript                        2.8.3
webpack                           4.8.3
```

**Comment by michaeljota** [comment]
@abdulkareemnalband `loadChildren` string path does not understand `baseUrl` and `path` configuration, as far I know. That maybe a feature request, but is not this same issue at all.

**Comment by abdulkareemnalband** [comment]
@michaeljota  Our project is configured as multiple  [apps](https://github.com/angular/angular-cli/wiki/stories-multiple-projects) , with a shred folder containing some shared modules
the `loadChildren` with `path` configuration is working with one app but not with other

**Comment by michaeljota** [comment]
This issue is actually quite specific, and I think it has been misunderstood. Please, check if your issue is about creating a new lazy module, or changing the string path when the cli is serving. That's cause, if not, then you should look for your issue to get proper help. 👍

**Comment by dlarr** [comment]
@sluglit solution worked.

I was importing lazy loaded modules in my AppModule. Removing them made it OK :)

Thanks buddy.

**Comment by Supamiu** [comment]
It seems like this is a regression introduced somewhere between 1.6.5 and 1.7.0, I didn't have the issue with cli@1.6.5 and now I have it with cli@1.7.4.

**Comment by speti43** [comment]
@sluglit Thanks, your solution is the true solution, works fine! Thanks!

**Comment by naichenardi** [comment]
@sluglit that works for me. Thanks

**Comment by Woutwo** [comment]
@sluglit you indeed have to make sure that AppRoutingModule is the last in line, that fixed my problems.

https://github.com/angular/angular-cli/issues/9825#issuecomment-390410427

**Comment by RafaelFronteira** [comment]
Hey @dkarski, can you explain this solution?
This worked for me, but I really did not understand how it works.

"{ path: 'user-panel', loadChildren: () => UserPanelModule, },"

I'm sorry if that's a silly question ...

**Comment by RafaelFronteira** [comment]
@Antoniossss thanks man, but have you found a solution without losing lazy loading?

**Comment by speti43** [comment]
@RafaelFronteira That worked for me what @sluglit suggested:

1. Move the order of my imports around. (Move the *RoutingModule to the bottom of the list of imports)
2. Remove the lazy-loaded modules from the NgModule.imports property list

The second one solved the problem for me.

And leave the lazy loading as it was:
loadChildren: 'app/dashboard/dashboard.module#DashboardModule'

**Comment by RafaelFronteira** [comment]
@speti43 It worked for me too. Thanks a lot!

**Comment by asmith2306** [comment]
@speti43 

> Remove the lazy-loaded modules from the NgModule.imports property list

This worked for me.  loadChildren loads the module dynamically.  No need to import the module in your app.module.

Cheers

**Comment by phutaneVinayak** [comment]
@speti43 
thanks for tips work for me.

no need for ng-cli downgrade and AOT

**Comment by wctiger** [comment]
The workaround by @sluglit @speti43 also worked for me running CLI v6.1.0
Few things may worth mentioning.. I tried continue using a relative path in loadChildren after remove module imports in AppModule/AppRoutingModule as well as moved routing module down. 
`{ path: 'home', loadChildren: './modules/home/home.module#HomeModule' }` -- this format worked

Also, if you're on Angular 6 and needs to use a absolute path you may try 
`{ path: 'home', loadChildren: 'src/app/modules/home/home.module#HomeModule' }` 
instead of only specify app at the beginning

**Comment by dercilima** [comment]
It worked for me:
[](https://github.com/angular/angular/issues/23412#issuecomment-422682849)

**Comment by shabinpshams** [comment]
> I recomended change
> `{ path: 'user-panel', loadChildren: './user-panel/user-panel.module#UserPanelModule', },`
> 
> to
> 
> `{ path: 'user-panel', loadChildren: () => UserPanelModule, },`

It works for me. Thanks. Cheers!!!

**Comment by speti43** [comment]
> > I recomended change
> > `{ path: 'user-panel', loadChildren: './user-panel/user-panel.module#UserPanelModule', },`
> > to
> > `{ path: 'user-panel', loadChildren: () => UserPanelModule, },`
> 
> It works for me. Thanks. Cheers!!!

Don't do that, prod build will fail, this is just a dirty workaround.
Correct solution is above.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version. As this should have been also addressed in https://github.com/angular/angular-cli/pull/12418

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by nickofthyme** [comment]
I had this same issue but was ***not*** importing the lazy module in my `app.module.ts` nor did any of the other of the aforementioned suggested solutions resolve the error.

I was lazy loading a module that was using a custom angular component library. This library worked fine in ng5 but as soon as we upgraded to ng6, this error started occurring.

The fix was **_COMPLETELY_** unrelated to the error message, in fact, the error was terribly misleading and useless! We had to start stripping modules from our app ONE BY ONE to finally see what was causing the error to get some clue as to what the _actual_ root cause was.

As it turns out in our custom library we were importing a few modules from an `index.js` (bucket) file which for whatever reason Angular compiler still can't figure out.

``` typescript
// This is BAD!
import { MyModule } from '../my-modules/index';

// This is GOOD?
import { MyModule } from '../my-modules/my.module';
```

Sounds like my case is rare given that most people were able to resolve their issue with the solutions listed above but I wanted to comment in hopes that this could help someone else.

**Comment by michaeljota** [comment]
Can confirm this issue is not longer reproducible. Thanks!

**Comment by basantkumarpogeyan** [comment]
> I recomended change
> `{ path: 'user-panel', loadChildren: './user-panel/user-panel.module#UserPanelModule', },`
> 
> to
> 
> `{ path: 'user-panel', loadChildren: () => UserPanelModule, },`

thanks @

**Comment by speti43** [comment]
@basantkumarpogeyan bad idea, that will fail in prod build. That's just a workaround, not the solution.
