### ISSUE TITLE
Uncaught (in promise) TypeError: e is not a constructor 

### ISSUE THREAD

**Issue by Mani2693** [angular/angular-cli#9929]
### Version:

![cliversion](https://user-images.githubusercontent.com/11607412/37246348-c7515e20-24cd-11e8-800e-bf37146e0af2.PNG)

### Error 

![typeerror](https://user-images.githubusercontent.com/11607412/37246386-4b605aae-24ce-11e8-9261-cf675c679840.PNG)

### Repro steps

- Create new angular-cli project with router enabled 
- Build project in production mode " ng build --prod " 
- Run the application and click on any router link to navigate 
- see the console for the issue 

### Package.json 

![packagejson](https://user-images.githubusercontent.com/11607412/37246404-7d717c94-24ce-11e8-98df-1c10b2b86d3e.PNG)

### Background 
* Issue exist from almost all the build I checked , from cli 1.6.3 + ( I can't check before this because it causes some other compile time error )
* Also the issue is only with production build , Development build works fine , I tired to debug both the build side by side , Below are the findings
### Mention any other details that might be useful (optional)
* It all starts from router.navigate['/url' ] and goes into router.js
* NavigationStart( URL ) function in router.js passes control into core.js pre-builder there seems to the issue 

Below function in zone.js is where the error thrown:

![zone-function](https://user-images.githubusercontent.com/11607412/37246502-cc09d4f4-24cf-11e8-9349-b597bf302cf5.PNG)

try catch which returns the error:

![zone-error2](https://user-images.githubusercontent.com/11607412/37250959-a5ebbce8-252d-11e8-814f-7a2d90ccbd81.PNG)

Hope the information helps, Please look into this issue ASAP since we need this to be sorted out very quickly 

Thanks in advance

**Comment by Mani2693** [comment]
Hi, 
Do we have any update regarding the above issue , We are facing hard time with this issue 

It will be so helpful if I get any clue 

Thanks

**Comment by quahkj** [comment]
I also encounter this issue with Angular CLI version 1.7.0. I remember I had a workaround by downgrading angular cli in package.json:  

 "devDependencies": {
    "@angular/cli": "1.6.7",
    ...

But now seem like downgrading above also didn't work for me.

**Comment by gfaganli** [comment]
waiting for solution.. 
this error happens when i run with prod mode  (ng build/serve  --prod),  ng build/serve does not generate this error

**Comment by matulkum** [comment]
+1

**Comment by abbatepabloo** [comment]
+1

**Comment by karan-intersoft** [comment]
Facing hard time with this issue.

Any update regarding this issue?
![image](https://user-images.githubusercontent.com/13096211/43076143-e7dfae34-8ea0-11e8-988d-5275e17fffc9.png)

**Comment by ChangAlanCL** [comment]
I'm having the same issue with CLI v6.0.7 and angular 6.0.3
![error_angular](https://user-images.githubusercontent.com/26290383/44192218-f21a8200-a171-11e8-87d6-b029cc3404f0.PNG)

**Comment by Behrad96** [comment]
same issue with Angular CLI v6.1.3
![](http://uupload.ir/files/01io_screen_shot_1397-05-25_at_12.33.11.jpg)

**Comment by Leanvitale** [comment]
Try for this..
> ng build --prod --optimization=false

**Comment by queejie** [comment]
Same problem.  Same result when compiling with --optimization=false.

![image](https://user-images.githubusercontent.com/1616827/44352642-efba6f80-a472-11e8-97b5-0200d4ae3495.png)

**Comment by medisoft** [comment]
I was able to run it with the --aot=false parameter too.

**Comment by CamielK** [comment]
Same issue. Fixed it by setting the --aot=false flag

**Comment by alejandromangione** [comment]
Hey! I was with the problem, you can try deleting node_modules and reinstalling the dependencies.

**Comment by danphilip** [comment]
+1 . Fixed with aot flag false but can't build in production mode without aot.

**Comment by Abdallah-khalil** [comment]
i can run `ng build`  and it works just fine but with `ng build --prod` i got an error  
`main.978c59b99705f7cbd36b.js:1 Uncaught TypeError: e is not a function
    at main.978c59b99705f7cbd36b.js:1
    at Array.reduceRight (<anonymous>)
    at main.978c59b99705f7cbd36b.js:1
    at new e (main.978c59b99705f7cbd36b.js:1)
    at main.978c59b99705f7cbd36b.js:1
    at Ir (main.978c59b99705f7cbd36b.js:1)
    at main.978c59b99705f7cbd36b.js:1
    at new t (main.978c59b99705f7cbd36b.js:1)
    at Object.na [as createNgModuleRef] (main.978c59b99705f7cbd36b.js:1)
    at e.create (main.978c59b99705f7cbd36b.js:1)`


any idea what is the cause of this

**Comment by pbachman** [comment]
i had the same issue with the dependencies
"@angular/core": "6.0.3",
"@angular/cli": "^6.1.5"

works fine with
"@angular/cli": "**^6.0.8**"

**Comment by Abdallah-khalil** [comment]
remove

> Hey! I was with the problem, you can try deleting node_modules and reinstalling the dependencies.

that's fixed it for me thanks @alejandromangione

**Comment by Arnie38** [comment]
These kinds of errors had plagued us for awhile. Yes you can turn off prod/aot compiles and you won't see the issue but then you won't have a minified/uglified/treeshaken optimized bits :)

The most sane fix for us is to simply export * from any components that are causing the "ctor is not a constructor" (or similar) errors. 
We haven't had the time to explore deeply but exporting your specific types (for .ts access) although should work doesn't seem to when you run bits that have been aot/prod compiled. 

So from your index.ts or however you do it you should say....
 "export * from ./mycomponents/mycomponent" 
...not... "export {MyComponent} from ./mycomponents/mycomponentfile"
This works everytime for us. 
Hopefully that is enough to go on.

**Comment by Abdallah-khalil** [comment]
Thanks @Mani2693 ,
actually i did so and found that `@ngrx/state`   was causing error for me 
and when i changed `extractLicenses: false` in **angular.json** file it fixed this error for me **though** the bundled file is bigger with about 1MB with that option but so far it's much better than before

**Comment by trewpog** [comment]
Fixed my problem, switching target at tsconfig.json to: `"target": "es5",`

**Comment by bgBond** [comment]
I have the same problem after upgrading to angular 7-

  "dependencies": {
    "@angular/animations": "^7.1.3",
    "@angular/cdk": "^7.1.1",
    "@angular/common": "^7.1.3",
    "@angular/compiler": "^7.1.3",
    "@angular/core": "^7.1.3",
    "@angular/flex-layout": "^7.0.0-beta.21",
    "@angular/forms": "^7.1.3",
    "@angular/http": "^7.1.3",
    "@angular/material": "^7.1.1",
    "@angular/material-moment-adapter": "^7.1.1",
    "@angular/platform-browser": "^7.1.3",
    "@angular/platform-browser-dynamic": "^7.1.3",
    "@angular/router": "^7.1.3",
    "@auth0/angular-jwt": "^2.1.0",
    "@netbasal/ngx-content-loader": "^2.0.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "core-js": "^2.5.7",
    "moment": "^2.23.0",
    "ngx-moment": "^3.2.0",
    "ngx-quill": "^4.4.2",
    "quill": "^1.3.6",
    "rxjs": "^6.3.3",
    "stickybits": "^3.5.7",
    "what-input": "^5.1.0", 
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.5",
    "@angular/cli": "~7.1.3",
    "@angular/compiler-cli": "^7.1.3",
    "@angular/language-service": "^7.1.3",
    "@types/jasmine": "^2.8.7",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.111",
    "codelyzer": "^4.5.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^2.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.4.3",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "modularscale-sass": "^3.0.8",
    "protractor": "~5.1.2",
    "sass-loader": "^6.0.7",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~3.1.6"
  }

Anybody can assist?

**Comment by mgechev** [comment]
It looks like not all reported errors here are the same. @Mani2693 would share minimum demo where we can reproduce the issue?

**Comment by mgechev** [comment]
@Mani2693 thanks for sharing your findings! Maybe you can work with @dherges on fixing the issue.

**Comment by gigallo** [comment]
Hi

I have the same problem with Angular7 and prod mode. If i don't compile with optimizations the error changes in "ctor is not a constructor". Any help?

**Comment by xyrus02** [comment]
Same here: --aot=false works but it is rather nasty to do. We are not sure since what change on our side the error occurs but if we find something, I will comment back here.

**Comment by petrifront** [comment]
I'm experiencing the exact same issue - some components cannot be created because of "is not a constructor" error in prod mode with 7.3. This should be reopened.

**Comment by svesax** [comment]
Same problem "o is not a constructor" when build without --aot=false --build-optimizer=false
Any news ?
Thanks!

**Comment by bgBond** [comment]
Just to update that after deleting the node modules directory and running npm install, it worked!

**Comment by kathygit** [comment]
I am still seeing this issue. This issue should be reopened.

**Comment by mgechev** [comment]
Looks like this is related to the bundle optimizer. @filipesilva any thoughts?

**Comment by kathygit** [comment]
The common theme is we can't run with the artifacts from build:production. 
All the fixes mentioned here and there didn't solve the issue. 
It is still an issue, even if you can't recreate it.

**Comment by filipesilva** [comment]
@kathygit we'd really like to fix the problem you're seeing but we can't do it without some sort of reproduction. We talk a little in https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue about why it's important to have a reproduction. 

Can you spare some time to open a new issue with a reproduction so we can dig in and fix the problem?

**Comment by krojew** [comment]
@filipesilva I've created a similar bug with some more info: https://github.com/angular/angular-cli/issues/13540 Mybe this can help.

**Comment by filipesilva** [comment]
@krojew reading through that issue it sounds like it was some sort of problem with `angular-resize-event`, and that it was subsequently fixed in that library?

I agree it would be nice if there was a build error for it instead of breaking at runtime, but that's not always possible. Sometimes code isn't statically analysable for errors. If I had to bet it was something that broke when using minification, which is part of prod builds.

**Comment by krojew** [comment]
@filipesilva yes - it was a AOT incompatibility which was fixed. But that gives you a repeatable case to see what's actually going on and if it's possible to catch it at compile time.

**Comment by dgo-angelo** [comment]
Same "TypeError: e is not a constructor" error here. Does anybody know how to solve this error?

**Comment by BBlackwo** [comment]
I had a similar issue with an NPM module I was consuming. The NPM module code was like this:

```js
// my-service.js
export default class MyService {} // <-- default export

// index.js
import MyService from './my-service'
export { MyService };
```

The fix was to export the class instead of exporting default:

```js
// my-service.js
export class MyService {} // <-- exporting the class

// index.js
import { MyService } from './myService'; // <-- destructured import
export { MyService };
```

**Comment by pconas-yschmidt** [comment]
I can support BBlackwo, in my case I had implemented a CustomUrlSerializer like so:

export default class CustomUrlSerializer implements UrlSerializer { ... }

Removing the default Keyword fixed the issue:

export class CustomUrlSerializer implements UrlSerializer { ... }

**Comment by Guilhermesfl** [comment]
Guys, if any of you still have this problem, I recommend checking your npm packages. In my case, I had a npm warn of a missing dependency and when I fixed this warn my problem was solved.
